import { DestroyRef, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { DataKeyConfigComponent } from '@home/components/widget/lib/settings/common/key/data-key-config.component';
import { ChartBarSettings, ChartLabelPosition, PieChartLabelPosition } from '@home/components/widget/lib/chart/chart.models';
import * as i0 from "@angular/core";
export declare class ChartBarSettingsComponent implements OnInit, ControlValueAccessor {
    protected store: Store<AppState>;
    private dataKeyConfigComponent;
    private fb;
    private destroyRef;
    chartLabelPositions: (ChartLabelPosition | PieChartLabelPosition)[];
    chartLabelPositionTranslations: Map<ChartLabelPosition | PieChartLabelPosition, string>;
    labelPreviewFn: any;
    disabled: boolean;
    series: boolean;
    pieLabelPosition: boolean;
    reportMode: boolean;
    private modelValue;
    private propagateChange;
    barSettingsFormGroup: UntypedFormGroup;
    constructor(store: Store<AppState>, dataKeyConfigComponent: DataKeyConfigComponent, fb: UntypedFormBuilder, destroyRef: DestroyRef);
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: ChartBarSettings): void;
    private updateValidators;
    private updateModel;
    private _labelPreviewFn;
    static ɵfac: i0.ɵɵFactoryDeclaration<ChartBarSettingsComponent, [null, { optional: true; }, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ChartBarSettingsComponent, "tb-chart-bar-settings", never, { "disabled": { "alias": "disabled"; "required": false; }; "series": { "alias": "series"; "required": false; }; "pieLabelPosition": { "alias": "pieLabelPosition"; "required": false; }; "reportMode": { "alias": "reportMode"; "required": false; }; }, {}, never, never, false, never>;
}
