import { ChangeDetectorRef, EventEmitter, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormControl, UntypedFormGroup } from '@angular/forms';
import { TimeSeriesChartThreshold, TimeSeriesChartYAxisId } from '@home/components/widget/lib/chart/time-series-chart.models';
import { TimeSeriesChartThresholdsPanelComponent } from '@home/components/widget/lib/settings/common/chart/time-series-chart-thresholds-panel.component';
import { IAliasController } from '@core/api/widget-api.models';
import { Datasource, DatasourceType, WidgetConfig } from '@shared/models/widget.models';
import { DataKeysCallbacks } from '@home/components/widget/config/data-keys.component.models';
import { DataKeyType } from '@shared/models/telemetry/telemetry.models';
import { ValueSourceType } from '@shared/models/widget-settings.models';
import * as i0 from "@angular/core";
export declare class TimeSeriesChartThresholdRowComponent implements ControlValueAccessor, OnInit, OnChanges {
    private fb;
    private thresholdsPanel;
    private cd;
    DataKeyType: typeof DataKeyType;
    DatasourceType: typeof DatasourceType;
    TimeSeriesChartThresholdType: typeof ValueSourceType;
    timeSeriesThresholdTypes: ValueSourceType[];
    timeSeriesThresholdTypeTranslations: Map<ValueSourceType, string>;
    get aliasController(): IAliasController;
    get dataKeyCallbacks(): DataKeysCallbacks;
    get datasource(): Datasource;
    get widgetConfig(): WidgetConfig;
    disabled: boolean;
    yAxisIds: TimeSeriesChartYAxisId[];
    hideYAxis: boolean;
    thresholdRemoved: EventEmitter<any>;
    thresholdFormGroup: UntypedFormGroup;
    modelValue: TimeSeriesChartThreshold;
    latestKeyFormControl: UntypedFormControl;
    entityKeyFormControl: UntypedFormControl;
    thresholdSettingsFormControl: UntypedFormControl;
    private propagateChange;
    constructor(fb: UntypedFormBuilder, thresholdsPanel: TimeSeriesChartThresholdsPanelComponent, cd: ChangeDetectorRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: TimeSeriesChartThreshold): void;
    private updateValidators;
    private updateModel;
    static ɵfac: i0.ɵɵFactoryDeclaration<TimeSeriesChartThresholdRowComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TimeSeriesChartThresholdRowComponent, "tb-time-series-chart-threshold-row", never, { "disabled": { "alias": "disabled"; "required": false; }; "yAxisIds": { "alias": "yAxisIds"; "required": false; }; "hideYAxis": { "alias": "hideYAxis"; "required": false; }; }, { "thresholdRemoved": "thresholdRemoved"; }, never, never, false, never>;
}
