import { OnInit } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { HasDirtyFlag } from '@core/guards/confirm-on-exit.guard';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ActivatedRoute } from '@angular/router';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import { UtilsService } from '@core/services/utils.service';
import { TranslateService } from '@ngx-translate/core';
import { ContentType } from '@shared/models/constants';
import { CustomMenu } from '@shared/models/custom-menu.models';
import { CustomMenuService } from '@core/http/custom-menu.service';
import { Observable } from 'rxjs';
import * as i0 from "@angular/core";
export declare class CustomMenuComponent extends PageComponent implements OnInit, HasDirtyFlag {
    protected store: Store<AppState>;
    private route;
    private customMenuService;
    private utils;
    private translate;
    private userPermissionsService;
    isDirty: boolean;
    readonly: boolean;
    contentType: typeof ContentType;
    customMenu: CustomMenu;
    customMenuJson: string;
    menuPlaceholder: string;
    constructor(store: Store<AppState>, route: ActivatedRoute, customMenuService: CustomMenuService, utils: UtilsService, translate: TranslateService, userPermissionsService: UserPermissionsService);
    ngOnInit(): void;
    getCurrentCustomMenu(): Observable<any>;
    save(): void;
    private parse;
    static ɵfac: i0.ɵɵFactoryDeclaration<CustomMenuComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CustomMenuComponent, "tb-custom-menu", never, {}, {}, never, never, false, never>;
}
