import { OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { PageComponent } from '@shared/components/page.component';
import { Router } from '@angular/router';
import { FormBuilder, FormGroup, FormGroupDirective } from '@angular/forms';
import { HasConfirmForm } from '@core/guards/confirm-on-exit.guard';
import { SelfRegistrationService } from '@core/http/self-register.service';
import { SelfRegistrationParams } from '@shared/models/self-register.models';
import { TranslateService } from '@ngx-translate/core';
import { EntityType } from '@shared/models/entity-type.models';
import { AttributeService } from '@core/http/attribute.service';
import * as i0 from "@angular/core";
export declare class SelfRegistrationComponent extends PageComponent implements OnInit, HasConfirmForm {
    protected store: Store<AppState>;
    private router;
    private selfRegistrationService;
    private attributeService;
    private translate;
    fb: FormBuilder;
    selfRegistrationFormGroup: FormGroup;
    selfRegistrationParams: SelfRegistrationParams;
    registerLink: string;
    deleteDisabled: boolean;
    entityTypes: typeof EntityType;
    tinyMceOptions: Record<string, any>;
    constructor(store: Store<AppState>, router: Router, selfRegistrationService: SelfRegistrationService, attributeService: AttributeService, translate: TranslateService, fb: FormBuilder);
    ngOnInit(): void;
    buildSelfRegistrationForm(): void;
    private updateDisabledState;
    private updateMobileSelfRegistration;
    save(): void;
    delete(form: FormGroupDirective): void;
    confirmForm(): FormGroup;
    onActivationLinkCopied(): void;
    private onSelfRegistrationParamsLoaded;
    private selfRegistrationParamsFromFormValue;
    private convertTextToHTML;
    private convertHTMLToText;
    static ɵfac: i0.ɵɵFactoryDeclaration<SelfRegistrationComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SelfRegistrationComponent, "tb-self-registration", never, {}, {}, never, never>;
}
