import { DestroyRef } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { PageComponent } from '@shared/components/page.component';
import { FormBuilder, FormGroup } from '@angular/forms';
import { AdminService } from '@core/http/admin.service';
import { HasConfirmForm } from '@core/guards/confirm-on-exit.guard';
import { MatDialog } from '@angular/material/dialog';
import { NotificationService } from '@core/http/notification.service';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import * as i0 from "@angular/core";
export declare class SmsProviderComponent extends PageComponent implements HasConfirmForm {
    protected store: Store<AppState>;
    private adminService;
    private notificationService;
    private dialog;
    private userPermissionsService;
    fb: FormBuilder;
    private destroyRef;
    smsProvider: FormGroup;
    private adminSettings;
    notificationSettingsForm: FormGroup;
    private notificationSettings;
    private readonly authUser;
    readonly: boolean;
    constructor(store: Store<AppState>, adminService: AdminService, notificationService: NotificationService, dialog: MatDialog, userPermissionsService: UserPermissionsService, fb: FormBuilder, destroyRef: DestroyRef);
    private setSmsProviderSettings;
    private setNotificationSettings;
    isTenantAdmin(): boolean;
    private buildSmsProviderForm;
    private updateValidators;
    sendTestSms(): void;
    save(): void;
    confirmForm(): FormGroup;
    private buildGeneralServerSettingsForm;
    private updatedNotificationSettings;
    saveNotification(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<SmsProviderComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SmsProviderComponent, "tb-sms-provider", never, {}, {}, never, never, false, never>;
}
