import { WidgetSettings, WidgetSettingsComponent } from '@shared/models/widget.models';
import { UntypedFormArray, UntypedFormBuilder, UntypedFormGroup, ValidatorFn } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ApiUsageSettingsContext } from '@home/components/widget/lib/settings/cards/api-usage-settings.component.models';
import { Observable } from 'rxjs';
import { MatDialog } from '@angular/material/dialog';
import { CdkDragDrop } from '@angular/cdk/drag-drop';
import * as i0 from "@angular/core";
export declare class ApiUsageWidgetSettingsComponent extends WidgetSettingsComponent {
    protected store: Store<AppState>;
    private dialog;
    private fb;
    apiUsageWidgetSettingsForm: UntypedFormGroup;
    context: ApiUsageSettingsContext;
    constructor(store: Store<AppState>, dialog: MatDialog, fb: UntypedFormBuilder);
    ngOnInit(): void;
    protected doUpdateSettings(settingsForm: UntypedFormGroup, settings: WidgetSettings): void;
    dataKeysFormArray(): UntypedFormArray;
    trackByDataKey(index: number): any;
    get dragEnabled(): boolean;
    layerDrop(event: CdkDragDrop<string[]>): void;
    removeDataKey(index: number): void;
    addDataKey(): void;
    protected settingsForm(): UntypedFormGroup;
    protected defaultSettings(): WidgetSettings;
    protected prepareInputSettings(settings: WidgetSettings): WidgetSettings;
    protected onSettingsSet(settings: WidgetSettings): void;
    private prepareDataKeysFormArray;
    protected validatorTriggers(): string[];
    protected updateValidators(): void;
    apiUsageDataKeyValidator: () => ValidatorFn;
    private editKey;
    private generateDataKey;
    fetchDashboardStates(searchText?: string): Observable<Array<string>>;
    static ɵfac: i0.ɵɵFactoryDeclaration<ApiUsageWidgetSettingsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ApiUsageWidgetSettingsComponent, "tb-api-usage-widget-settings", never, {}, {}, never, never, false, never>;
}
