import { ChangeDetectorRef } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { Dashboard, DashboardInfo } from '@shared/models/dashboard.models';
import { DashboardService } from '@core/http/dashboard.service';
import { GroupEntityComponent } from '@home/components/group/group-entity.component';
import { GroupEntityTableConfig } from '@home/models/group/group-entities-table-config.models';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import * as i0 from "@angular/core";
export declare class DashboardFormComponent extends GroupEntityComponent<DashboardInfo> {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    private dashboardService;
    protected entityValue: DashboardInfo;
    protected entitiesTableConfigValue: EntityTableConfig<DashboardInfo> | GroupEntityTableConfig<DashboardInfo>;
    protected fb: UntypedFormBuilder;
    protected cd: ChangeDetectorRef;
    protected userPermissionsService: UserPermissionsService;
    isPublic: boolean;
    publicLink: string;
    constructor(store: Store<AppState>, translate: TranslateService, dashboardService: DashboardService, entityValue: DashboardInfo, entitiesTableConfigValue: EntityTableConfig<DashboardInfo> | GroupEntityTableConfig<DashboardInfo>, fb: UntypedFormBuilder, cd: ChangeDetectorRef, userPermissionsService: UserPermissionsService);
    ngOnInit(): void;
    hideDelete(): boolean;
    buildForm(entity: DashboardInfo): UntypedFormGroup;
    updateForm(entity: Dashboard): void;
    prepareFormValue(formValue: any): any;
    onPublicLinkCopied($event: any): void;
    onDashboardIdCopied($event: any): void;
    private updateFields;
    static ɵfac: i0.ɵɵFactoryDeclaration<DashboardFormComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DashboardFormComponent, "tb-dashboard-form", never, {}, {}, never, never, false, never>;
}
