import { AfterViewInit, ElementRef, EventEmitter, OnChanges, OnDestroy, OnInit, Renderer2, SimpleChanges } from '@angular/core';
import { ComponentStyle } from '@shared/models/widget-settings.models';
import { UtilsService } from '@core/services/utils.service';
import { Observable } from 'rxjs';
import { WidgetContext } from '@home/models/widget-component.models';
import { MatButtonToggleChange } from '@angular/material/button-toggle';
import * as i0 from "@angular/core";
export declare class WidgetButtonToggleComponent implements OnInit, AfterViewInit, OnDestroy, OnChanges {
    private renderer;
    private elementRef;
    private utils;
    toggleGroupContainer: ElementRef<HTMLElement>;
    widgetButton: ElementRef<HTMLElement>;
    leftButtonContent: ElementRef<HTMLElement>;
    rightButtonContent: ElementRef<HTMLElement>;
    appearance: import("@home/components/widget/lib/button/segmented-button-widget.models").ButtonToggleAppearance;
    borderRadius: string;
    autoScale: boolean;
    value: boolean;
    disabled: boolean;
    hovered: boolean;
    disableEvents: boolean;
    ctx: WidgetContext;
    clicked: EventEmitter<MatButtonToggleChange>;
    leftLabel$: Observable<string>;
    rightLabel$: Observable<string>;
    leftIconStyle: ComponentStyle;
    rightIconStyle: ComponentStyle;
    leftLabelStyle: ComponentStyle;
    rightLabelStyle: ComponentStyle;
    computedBorderColor: string;
    computedBorderWidth: string;
    computedBorderRadius: string;
    private buttonResize$;
    private appearanceCssClass;
    constructor(renderer: Renderer2, elementRef: ElementRef, utils: UtilsService);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    validateSize(): void;
    private updateAppearance;
    private updateBorderRadius;
    private clearAppearanceCss;
    private updateAutoScale;
    private onResize;
    static ɵfac: i0.ɵɵFactoryDeclaration<WidgetButtonToggleComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<WidgetButtonToggleComponent, "tb-widget-button-toggle", never, { "appearance": { "alias": "appearance"; "required": false; }; "borderRadius": { "alias": "borderRadius"; "required": false; }; "autoScale": { "alias": "autoScale"; "required": false; }; "value": { "alias": "value"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "hovered": { "alias": "hovered"; "required": false; }; "disableEvents": { "alias": "disableEvents"; "required": false; }; "ctx": { "alias": "ctx"; "required": false; }; }, { "clicked": "clicked"; }, never, never, false, never>;
}
