import { Store } from '@ngrx/store';
import { AppState } from '../core.state';
import { HomeSection, MenuSection } from '@core/services/menu.models';
import { Observable } from 'rxjs';
import { CustomMenuService } from '@core/http/custom-menu.service';
import { Router } from '@angular/router';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import * as i0 from "@angular/core";
export declare class MenuService {
    private store;
    private router;
    private customMenuService;
    private userPermissionsService;
    private menuSections$;
    private homeSections$;
    private availableMenuLinks$;
    private currentMenuSections;
    private currentHomeSections;
    private currentCustomSection;
    private currentCustomChildSection;
    constructor(store: Store<AppState>, router: Router, customMenuService: CustomMenuService, userPermissionsService: UserPermissionsService);
    private buildMenu;
    private updateDisabledItems;
    private updateOpenedMenuSections;
    private buildSysAdminMenu;
    private buildSysAdminHome;
    private buildTenantAdminMenu;
    private buildTenantAdminHome;
    private buildCustomerUserMenu;
    private buildCustomerUserHome;
    private buildCustomMenu;
    private getCustomMenuStateId;
    private allMenuLinks;
    menuSections(): Observable<Array<MenuSection>>;
    homeSections(): Observable<Array<HomeSection>>;
    sectionActive(section: MenuSection): boolean;
    getCurrentCustomSection(): MenuSection;
    getCurrentCustomChildSection(): MenuSection;
    private updateCurrentCustomSection;
    private detectCurrentCustomSection;
    private detectCurrentCustomChildSection;
    private extractQueryParams;
    getRedirectPath(parentPath: string, redirectPath: string): Observable<string>;
    private findSectionByPath;
    availableMenuLinks(): Observable<Array<MenuSection>>;
    menuLinkById(id: string): Observable<MenuSection | undefined>;
    menuLinksByIds(ids: string[]): Observable<Array<MenuSection>>;
    static ɵfac: i0.ɵɵFactoryDeclaration<MenuService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<MenuService>;
}
