import { DestroyRef } from '@angular/core';
import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { Router } from '@angular/router';
import { DialogComponent } from '@shared/components/dialog.component';
import { CalculatedField, CalculatedFieldTestScriptFn, CalculatedFieldType } from '@shared/models/calculated-field.models';
import { EntityType } from '@shared/models/entity-type.models';
import { CalculatedFieldsService } from '@core/http/calculated-fields.service';
import { Observable } from 'rxjs';
import { EntityId } from '@shared/models/id/entity-id';
import { AdditionalDebugActionConfig } from '@home/components/entity/debug/entity-debug-settings.model';
import { BaseData } from '@shared/models/base-data';
import { CalculatedFieldFormService } from '@core/services/calculated-field-form.service';
import { FormGroup } from '@angular/forms';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import * as i0 from "@angular/core";
export interface CalculatedFieldDialogData {
    value?: CalculatedField;
    buttonTitle: string;
    entityId: EntityId;
    tenantId: string;
    entityName?: string;
    ownerId: EntityId;
    additionalDebugActionConfig: AdditionalDebugActionConfig<(calculatedField: CalculatedField) => void>;
    getTestScriptDialogFn: CalculatedFieldTestScriptFn;
    isDirty?: boolean;
    disabledSelectType?: boolean;
    readonly: boolean;
}
export declare class CalculatedFieldDialogComponent extends DialogComponent<CalculatedFieldDialogComponent, CalculatedField> {
    protected store: Store<AppState>;
    protected router: Router;
    data: CalculatedFieldDialogData;
    protected dialogRef: MatDialogRef<CalculatedFieldDialogComponent, CalculatedField>;
    private calculatedFieldsService;
    private destroyRef;
    private cfFormService;
    private userPermissionsService;
    fieldFormGroup: FormGroup;
    additionalDebugActionConfig: {
        action: () => void;
        title: string;
    };
    entityName: string;
    ownerId: EntityId;
    defaultEntityType: EntityType;
    disabledConfiguration: boolean;
    isLoading: boolean;
    readonly EntityType: typeof EntityType;
    readonly calculatedFieldsEntityTypeList: EntityType[];
    readonly CalculatedFieldType: typeof CalculatedFieldType;
    readonly fieldTypes: (CalculatedFieldType.SIMPLE | CalculatedFieldType.SCRIPT | CalculatedFieldType.GEOFENCING | CalculatedFieldType.PROPAGATION | CalculatedFieldType.RELATED_ENTITIES_AGGREGATION | CalculatedFieldType.ENTITY_AGGREGATION)[];
    readonly CalculatedFieldTypeTranslations: Map<CalculatedFieldType, import("@shared/models/calculated-field.models").CalculatedFieldTypeTranslate>;
    constructor(store: Store<AppState>, router: Router, data: CalculatedFieldDialogData, dialogRef: MatDialogRef<CalculatedFieldDialogComponent, CalculatedField>, calculatedFieldsService: CalculatedFieldsService, destroyRef: DestroyRef, cfFormService: CalculatedFieldFormService, userPermissionsService: UserPermissionsService);
    get fromGroupValue(): CalculatedField;
    cancel(): void;
    add(): void;
    onTestScript(expression?: string): Observable<string>;
    changeEntity(entity: BaseData<EntityId>): void;
    get entityId(): EntityId;
    private applyDialogData;
    static ɵfac: i0.ɵɵFactoryDeclaration<CalculatedFieldDialogComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CalculatedFieldDialogComponent, "tb-calculated-field-dialog", never, {}, {}, never, never, false, never>;
}
