import { AfterViewInit, ChangeDetectorRef, DestroyRef, OnInit } from '@angular/core';
import { TbPopoverComponent } from '@shared/components/popover.component';
import { FormBuilder, FormGroup } from '@angular/forms';
import { ArgumentEntityType, ArgumentType, CalculatedFieldArgumentValue } from '@shared/models/calculated-field.models';
import { EntityType } from '@shared/models/entity-type.models';
import { AttributeScope, DataKeyType } from '@shared/models/telemetry/telemetry.models';
import { DatasourceType } from '@shared/models/widget.models';
import { EntityId } from '@shared/models/id/entity-id';
import { EntityFilter } from '@shared/models/query/query.models';
import { BehaviorSubject } from 'rxjs';
import { AppState } from '@core/core.state';
import { Store } from '@ngrx/store';
import { EntityAutocompleteComponent } from '@shared/components/entity/entity-autocomplete.component';
import * as i0 from "@angular/core";
export declare class CalculatedFieldArgumentPanelComponent implements OnInit, AfterViewInit {
    private fb;
    private cd;
    private popover;
    private store;
    private destroyRef;
    buttonTitle: string;
    argument: CalculatedFieldArgumentValue;
    entityId: EntityId;
    tenantId: string;
    entityName: string;
    ownerId: EntityId;
    isScript: boolean;
    usedArgumentNames: string[];
    watchKeyChange: boolean;
    hiddenEntityTypes: boolean;
    hiddenEntityKeyTypes: boolean;
    hiddenDefaultValue: boolean;
    defaultValueRequired: boolean;
    hint: string;
    predefinedEntityFilter: EntityFilter;
    forbiddenNames: string[];
    argumentEntityTypes: ArgumentEntityType[];
    argumentNameContext: {
        [key: string]: string;
    };
    readonly: boolean;
    entityAutocomplete: EntityAutocompleteComponent;
    argumentsDataApplied: import("@angular/core").OutputEmitterRef<CalculatedFieldArgumentValue>;
    argumentType: import("@angular/forms").FormControl<ArgumentEntityType>;
    readonly maxDataPointsPerRollingArg: number;
    readonly defaultLimit: number;
    argumentFormGroup: FormGroup<{
        argumentName: import("@angular/forms").FormControl<string>;
        refEntityId: import("@angular/forms").FormControl<any>;
        refEntityKey: FormGroup<{
            type: import("@angular/forms").FormControl<ArgumentType>;
            key: import("@angular/forms").FormControl<string>;
            scope: import("@angular/forms").FormControl<AttributeScope>;
        }>;
        defaultValue: import("@angular/forms").FormControl<string>;
        limit: import("@angular/forms").FormControl<number>;
        timeWindow: import("@angular/forms").FormControl<number>;
    }>;
    argumentTypes: ArgumentType[];
    entityFilter: EntityFilter;
    entityNameSubject: BehaviorSubject<string>;
    enableAutocomplete: boolean;
    readonly ArgumentEntityTypeTranslations: Map<ArgumentEntityType, string>;
    readonly ArgumentType: typeof ArgumentType;
    readonly DataKeyType: typeof DataKeyType;
    readonly EntityType: typeof EntityType;
    readonly datasourceType: typeof DatasourceType;
    readonly ArgumentTypeTranslations: Map<ArgumentType, string>;
    readonly AttributeScope: typeof AttributeScope;
    readonly ArgumentEntityType: typeof ArgumentEntityType;
    readonly ArgumentEntityTypeParamsMap: Map<ArgumentEntityType, import("@shared/models/calculated-field.models").ArgumentEntityTypeParams>;
    private currentEntityFilter;
    constructor(fb: FormBuilder, cd: ChangeDetectorRef, popover: TbPopoverComponent<CalculatedFieldArgumentPanelComponent>, store: Store<AppState>, destroyRef: DestroyRef);
    get entityType(): ArgumentEntityType;
    get refEntityKeyFormGroup(): FormGroup;
    get enableAttributeScopeSelection(): boolean;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    saveArgument(): void;
    cancel(): void;
    private updatedFormValidators;
    private updatedArgumentType;
    private toggleByEntityKeyType;
    private updateEntityFilter;
    private observeEntityFilterChanges;
    private observeArgumentTypeChanges;
    private observeEntityKeyChanges;
    private setInitialEntityKeyType;
    private setInitialEntityType;
    private setWatchKeyChange;
    private updatedRefEntityIdState;
    static ɵfac: i0.ɵɵFactoryDeclaration<CalculatedFieldArgumentPanelComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CalculatedFieldArgumentPanelComponent, "tb-calculated-field-argument-panel", never, { "buttonTitle": { "alias": "buttonTitle"; "required": false; }; "argument": { "alias": "argument"; "required": false; }; "entityId": { "alias": "entityId"; "required": false; }; "tenantId": { "alias": "tenantId"; "required": false; }; "entityName": { "alias": "entityName"; "required": false; }; "ownerId": { "alias": "ownerId"; "required": false; }; "isScript": { "alias": "isScript"; "required": false; }; "usedArgumentNames": { "alias": "usedArgumentNames"; "required": false; }; "watchKeyChange": { "alias": "watchKeyChange"; "required": false; }; "hiddenEntityTypes": { "alias": "hiddenEntityTypes"; "required": false; }; "hiddenEntityKeyTypes": { "alias": "hiddenEntityKeyTypes"; "required": false; }; "hiddenDefaultValue": { "alias": "hiddenDefaultValue"; "required": false; }; "defaultValueRequired": { "alias": "defaultValueRequired"; "required": false; }; "hint": { "alias": "hint"; "required": false; }; "predefinedEntityFilter": { "alias": "predefinedEntityFilter"; "required": false; }; "forbiddenNames": { "alias": "forbiddenNames"; "required": false; }; "argumentEntityTypes": { "alias": "argumentEntityTypes"; "required": false; }; "argumentNameContext": { "alias": "argumentNameContext"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; }, { "argumentsDataApplied": "argumentsDataApplied"; }, never, never, false, never>;
}
