import { RequestConfig } from './http-utils';
import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { PageLink } from '@shared/models/page/page-link';
import { PageData } from '@shared/models/page/page-data';
import { Dashboard, DashboardInfo, HomeDashboard, HomeDashboardInfo } from '@shared/models/dashboard.models';
import { Router } from '@angular/router';
import { Operation } from '@shared/models/security.models';
import { EntityGroup, ShortEntityView } from '@shared/models/entity-group.models';
import * as i0 from "@angular/core";
export declare class DashboardService {
    private http;
    private router;
    private window;
    stDiffObservable: Observable<number>;
    currentUrl: string;
    constructor(http: HttpClient, router: Router, window: Window);
    getTenantDashboards(pageLink: PageLink, config?: RequestConfig): Observable<PageData<DashboardInfo>>;
    getTenantDashboardsByTenantId(tenantId: string, pageLink: PageLink, config?: RequestConfig): Observable<PageData<DashboardInfo>>;
    getDashboards(dashboardIds: string[], config?: RequestConfig): Observable<Array<DashboardInfo>>;
    getUserDashboards(userId: string, operation: Operation, pageLink: PageLink, config?: RequestConfig): Observable<PageData<DashboardInfo>>;
    getGroupDashboards(groupId: string, pageLink: PageLink, config?: RequestConfig): Observable<PageData<DashboardInfo>>;
    getDashboard(dashboardId: string, config?: RequestConfig): Observable<Dashboard>;
    getDashboardInfo(dashboardId: string, config?: RequestConfig): Observable<DashboardInfo>;
    saveDashboard(dashboard: Dashboard, entityGroupId?: string, config?: RequestConfig): Observable<Dashboard>;
    deleteDashboard(dashboardId: string, config?: RequestConfig): Observable<Object>;
    getPublicDashboardLink(dashboard: DashboardInfo | ShortEntityView, entityGroup: EntityGroup): string | null;
    getHomeDashboard(config?: RequestConfig): Observable<HomeDashboard>;
    getTenantHomeDashboardInfo(config?: RequestConfig): Observable<HomeDashboardInfo>;
    getCustomerHomeDashboardInfo(config?: RequestConfig): Observable<HomeDashboardInfo>;
    setTenantHomeDashboardInfo(homeDashboardInfo: HomeDashboardInfo, config?: RequestConfig): Observable<any>;
    setCustomerHomeDashboardInfo(homeDashboardInfo: HomeDashboardInfo, config?: RequestConfig): Observable<any>;
    getServerTimeDiff(): Observable<number>;
    static ɵfac: i0.ɵɵFactoryDeclaration<DashboardService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<DashboardService>;
}
