import { HttpClient } from '@angular/common/http';
import { PageLink } from '@shared/models/page/page-link';
import { RequestConfig } from '@core/http/http-utils';
import { Observable } from 'rxjs';
import { PageData } from '@shared/models/page/page-data';
import { ContactBased } from '@shared/models/contact-based.model';
import { EntityId } from '@shared/models/id/entity-id';
import { DeviceEntityGroupInfo, EntityGroup, EntityGroupInfo, ShareGroupRequest, ShortEntityView } from '@shared/models/entity-group.models';
import { EntityType } from '@shared/models/entity-type.models';
import { EntityGroupId } from '@shared/models/id/entity-group-id';
import { BaseData, HasId } from '@shared/models/base-data';
import { OtaPackageService } from '@core/http/ota-package.service';
import { DeviceGroupOtaPackage, OtaUpdateType } from '@shared/models/ota-package.models';
import { OtaPackageId } from '@shared/models/id/ota-package-id';
import { EntityInfoData } from '@shared/models/entity.models';
import * as i0 from "@angular/core";
export declare class EntityGroupService {
    private http;
    private otaPackageService;
    constructor(http: HttpClient, otaPackageService: OtaPackageService);
    getOwners(pageLink: PageLink, config?: RequestConfig): Observable<PageData<ContactBased<EntityId>>>;
    getOwnerInfos(pageLink: PageLink, config?: RequestConfig): Observable<PageData<EntityInfoData>>;
    getOwnerInfo(ownerId: EntityId, config?: RequestConfig): Observable<EntityInfoData>;
    getEntityGroup(entityGroupId: string, config?: RequestConfig): Observable<EntityGroupInfo>;
    getDeviceEntityGroup(entityGroupId: string, config?: RequestConfig): Observable<DeviceEntityGroupInfo>;
    fetchOtaPackageGroupInfo(group: EntityGroupInfo, config?: RequestConfig): Observable<DeviceEntityGroupInfo>;
    updateDeviceGroupOtaPackage(deviceGroupOtaPackage: DeviceGroupOtaPackage, otaPackageId: OtaPackageId | null, groupId: EntityGroupId, otaPackageType: OtaUpdateType, config?: RequestConfig): Observable<DeviceGroupOtaPackage>;
    saveDeviceGroupOtaPackage(deviceGroupOtaPackage: DeviceGroupOtaPackage, config?: RequestConfig): Observable<DeviceGroupOtaPackage>;
    saveDeviceEntityGroup(entityGroup: DeviceEntityGroupInfo, originalEntityGroup?: DeviceEntityGroupInfo, config?: RequestConfig): Observable<DeviceEntityGroupInfo>;
    deleteDeviceGroupOtaPackage(otaPackageId: string, config?: RequestConfig): Observable<null>;
    getEntityGroupEntityInfo(entityGroupId: string, config?: RequestConfig): Observable<EntityInfoData>;
    saveEntityGroup(entityGroup: EntityGroup, config?: RequestConfig): Observable<EntityGroupInfo>;
    deleteEntityGroup(entityGroupId: string, config?: RequestConfig): Observable<Object>;
    makeEntityGroupPublic(entityGroupId: string, config?: RequestConfig): Observable<any>;
    makeEntityGroupPrivate(entityGroupId: string, config?: RequestConfig): Observable<any>;
    shareEntityGroup(entityGroupId: string, shareGroupRequest: ShareGroupRequest, config?: RequestConfig): Observable<any>;
    getEntityGroups(pageLink: PageLink, groupType: EntityType, includeShared?: boolean, config?: RequestConfig): Observable<PageData<EntityGroupInfo>>;
    getEntityGroupEntityInfos(pageLink: PageLink, groupType: EntityType, includeShared?: boolean, config?: RequestConfig): Observable<PageData<EntityInfoData>>;
    getAllEntityGroups(pageSize: number, groupType: EntityType, includeShared?: boolean, config?: RequestConfig): Observable<Array<EntityGroupInfo>>;
    private getAllEntityGroupsByPageLink;
    getSharedEntityGroups(pageLink: PageLink, groupType: EntityType, config?: RequestConfig): Observable<PageData<EntityGroupInfo>>;
    getSharedEntityGroupEntityInfos(pageLink: PageLink, groupType: EntityType, config?: RequestConfig): Observable<PageData<EntityInfoData>>;
    getEntityGroupIdsForEntityId(entityType: EntityType, entityId: string, config?: RequestConfig): Observable<Array<EntityGroupId>>;
    getEntityGroupsByIds(entityGroupIds: Array<string>, config?: RequestConfig): Observable<Array<EntityGroupInfo>>;
    getEntityGroupEntityInfosByIds(entityGroupIds: Array<string>, config?: RequestConfig): Observable<Array<EntityInfoData>>;
    getEntityGroupsHierarchyByOwnerId(pageLink: PageLink, ownerType: EntityType, ownerId: string, groupType: EntityType, config?: RequestConfig): Observable<PageData<EntityGroupInfo>>;
    getEntityGroupEntityInfosHierarchyByOwnerId(pageLink: PageLink, ownerType: EntityType, ownerId: string, groupType: EntityType, config?: RequestConfig): Observable<PageData<EntityInfoData>>;
    getEntityGroupsByOwnerIdAndPageLink(ownerType: EntityType, ownerId: string, groupType: EntityType, pageLink: PageLink, config?: RequestConfig): Observable<PageData<EntityGroupInfo>>;
    getEntityGroupsByOwnerId(ownerType: EntityType, ownerId: string, groupType: EntityType, config?: RequestConfig): Observable<Array<EntityGroupInfo>>;
    getEntityGroupEntityInfosByOwnerId(pageLink: PageLink, ownerType: EntityType, ownerId: string, groupType: EntityType, config?: RequestConfig): Observable<PageData<EntityInfoData>>;
    getAllEntityGroupsByOwnerId(pageSize: number, ownerType: EntityType, ownerId: string, groupType: EntityType, config?: RequestConfig): Observable<Array<EntityGroupInfo>>;
    private getAllEntityGroupsByOwnerIdAndPageLink;
    getEntityGroupsByPageLink(pageLink: PageLink, groupType: EntityType, config?: RequestConfig): Observable<PageData<EntityGroupInfo>>;
    getEntityGroupAllByOwnerId(ownerType: EntityType, ownerId: string, groupType: EntityType, config?: RequestConfig): Observable<EntityGroupInfo>;
    addEntityToEntityGroup(entityGroupId: string, entityId: string, config?: RequestConfig): Observable<any>;
    addEntitiesToEntityGroup(entityGroupId: string, entityIds: string[], config?: RequestConfig): Observable<any>;
    changeEntityOwner(ownerId: EntityId, entityId: EntityId, entityGroupIds?: string[], config?: RequestConfig): Observable<any>;
    removeEntityFromEntityGroup(entityGroupId: string, entityId: string, config?: RequestConfig): Observable<any>;
    removeEntitiesFromEntityGroup(entityGroupId: string, entityIds: string[], config?: RequestConfig): Observable<any>;
    getEntityGroupEntity(entityGroupId: string, entityId: string, config?: RequestConfig): Observable<ShortEntityView>;
    getEntityGroupEntities<T extends BaseData<HasId> | ShortEntityView>(entityGroupId: string, pageLink: PageLink, entityType?: EntityType, config?: RequestConfig): Observable<PageData<T>>;
    getEdgeEntityGroups(pageLink: PageLink, edgeId: string, groupType: EntityType, config?: RequestConfig): Observable<PageData<EntityGroupInfo>>;
    getAllEdgeEntityGroups(pageSize: number, edgeId: string, groupType: EntityType, config?: RequestConfig): Observable<Array<EntityGroupInfo>>;
    private getAllEdgeEntityGroupsByPageLink;
    assignEntityGroupToEdge(edgeId: string, entityGroupId: string, groupType: string, config?: RequestConfig): Observable<EntityGroup>;
    unassignEntityGroupFromEdge(edgeId: string, entityGroupId: string, groupType: string, config?: RequestConfig): Observable<EntityGroup>;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityGroupService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<EntityGroupService>;
}
