import { Observable } from 'rxjs';
import { HttpClient } from '@angular/common/http';
import { PageLink } from '@shared/models/page/page-link';
import { AliasEntityType, EntityType } from '@shared/models/entity-type.models';
import { BaseData, HasId } from '@shared/models/base-data';
import { EntityId } from '@shared/models/id/entity-id';
import { DeviceService } from '@core/http/device.service';
import { TenantService } from '@core/http/tenant.service';
import { CustomerService } from '@core/http/customer.service';
import { UserService } from './user.service';
import { DashboardService } from '@core/http/dashboard.service';
import { PageData } from '@shared/models/page/page-data';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { AssetService } from '@core/http/asset.service';
import { EntityViewService } from '@core/http/entity-view.service';
import { DataKeyType } from '@shared/models/telemetry/telemetry.models';
import { RequestConfig } from '@core/http/http-utils';
import { RuleChainService } from '@core/http/rule-chain.service';
import { AliasInfo, StateParams, SubscriptionInfo } from '@core/api/widget-api.models';
import { DataKey, Datasource } from '@app/shared/models/widget.models';
import { UtilsService } from '@core/services/utils.service';
import { AliasFilterType, EntityAlias, EntityAliasFilter, EntityAliasFilterResult } from '@shared/models/alias.models';
import { EntitiesKeysByQuery, EntityInfo, ImportEntitiesResultInfo, ImportEntityData } from '@shared/models/entity.models';
import { EntityRelationService } from '@core/http/entity-relation.service';
import { AttributeService } from '@core/http/attribute.service';
import { ConverterService } from '@core/http/converter.service';
import { IntegrationService } from '@core/http/integration.service';
import { SchedulerEventService } from '@core/http/scheduler-event.service';
import { BlobEntityService } from '@core/http/blob-entity.service';
import { RoleService } from '@core/http/role.service';
import { EntityGroupService } from '@core/http/entity-group.service';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import { Operation } from '@shared/models/security.models';
import { CustomerId } from '@shared/models/id/customer-id';
import { AlarmData, AlarmDataQuery, EntityData, EntityDataQuery, EntityFilter } from '@shared/models/query/query.models';
import { EdgeService } from '@core/http/edge.service';
import { EdgeEvent } from '@shared/models/edge.models';
import { OtaPackageService } from '@core/http/ota-package.service';
import { RuleChainMetaData } from '@shared/models/rule-chain.models';
import { WidgetService } from '@core/http/widget.service';
import { DeviceProfileService } from '@core/http/device-profile.service';
import * as i0 from "@angular/core";
export declare class EntityService {
    private http;
    private store;
    private deviceService;
    private assetService;
    private entityViewService;
    private edgeService;
    private tenantService;
    private customerService;
    private userService;
    private ruleChainService;
    private dashboardService;
    private entityRelationService;
    private attributeService;
    private otaPackageService;
    private widgetService;
    private deviceProfileService;
    private converterService;
    private integrationService;
    private schedulerEventService;
    private blobEntityService;
    private roleService;
    private entityGroupService;
    private userPermissionsService;
    private utils;
    constructor(http: HttpClient, store: Store<AppState>, deviceService: DeviceService, assetService: AssetService, entityViewService: EntityViewService, edgeService: EdgeService, tenantService: TenantService, customerService: CustomerService, userService: UserService, ruleChainService: RuleChainService, dashboardService: DashboardService, entityRelationService: EntityRelationService, attributeService: AttributeService, otaPackageService: OtaPackageService, widgetService: WidgetService, deviceProfileService: DeviceProfileService, converterService: ConverterService, integrationService: IntegrationService, schedulerEventService: SchedulerEventService, blobEntityService: BlobEntityService, roleService: RoleService, entityGroupService: EntityGroupService, userPermissionsService: UserPermissionsService, utils: UtilsService);
    private getEntityObservable;
    private saveEntityObservable;
    getEntity(entityType: EntityType, entityId: string, config?: RequestConfig): Observable<BaseData<EntityId>>;
    saveEntity(entity: BaseData<EntityId>, config?: RequestConfig): Observable<BaseData<EntityId>>;
    private saveGroupEntityObservable;
    saveGroupEntity(entity: BaseData<EntityId>, entityGroupId: string, config?: RequestConfig): Observable<BaseData<EntityId>>;
    private getEntitiesObservable;
    getEntities(entityType: EntityType, entityIds: Array<string>, config?: RequestConfig): Observable<Array<BaseData<EntityId>>>;
    private getSingleTenantByPageLinkObservable;
    private getEntitiesByPageLinkObservable;
    private getEntitiesByPageLink;
    getEntitiesByNameFilter(entityType: EntityType, entityNameFilter: string, pageSize: number, subType?: string, config?: RequestConfig): Observable<Array<BaseData<EntityId>>>;
    private getEntityGroupEntitiesByPageLink;
    getEntityGroupEntities(entityGroupId: string, entityGroupType: EntityType, pageSize: number, config?: RequestConfig): Observable<Array<BaseData<EntityId>>>;
    getEntitiesByGroupName(entityType: EntityType, entityNameFilter: string, pageSize: number, stateEntityId?: EntityId, config?: RequestConfig): Observable<Array<BaseData<EntityId>>>;
    findEntityDataByQuery(query: EntityDataQuery, config?: RequestConfig): Observable<PageData<EntityData>>;
    findEntityKeysByQuery(query: EntityDataQuery, attributes?: boolean, timeseries?: boolean, config?: RequestConfig): Observable<EntitiesKeysByQuery>;
    findAlarmDataByQuery(query: AlarmDataQuery, config?: RequestConfig): Observable<PageData<AlarmData>>;
    findEntityInfosByFilterAndName(filter: EntityFilter, searchText: string, config?: RequestConfig): Observable<PageData<EntityInfo>>;
    findSingleEntityInfoByEntityFilter(filter: EntityFilter, config?: RequestConfig): Observable<EntityInfo>;
    getAliasFilterTypesByEntityTypes(entityTypes: Array<EntityType | AliasEntityType>): Array<AliasFilterType>;
    filterAliasByEntityTypes(entityAlias: EntityAlias, entityTypes: Array<EntityType | AliasEntityType>): boolean;
    private filterAliasFilterTypeByEntityTypes;
    private filterAliasFilterTypeByEntityType;
    prepareAllowedEntityTypesList(allowedEntityTypes: Array<EntityType | AliasEntityType>, useAliasEntityTypes?: boolean, operation?: Operation): Array<EntityType | AliasEntityType>;
    private getEntityFieldKeys;
    private getAlarmKeys;
    getEntityKeys(entityId: EntityId, query: string, type: DataKeyType, config?: RequestConfig): Observable<Array<string>>;
    getEntityKeysByEntityFilter(filter: EntityFilter, types: DataKeyType[], config?: RequestConfig): Observable<Array<DataKey>>;
    createDatasourcesFromSubscriptionsInfo(subscriptionsInfo: Array<SubscriptionInfo>): Array<Datasource>;
    createAlarmSourceFromSubscriptionInfo(subscriptionInfo: SubscriptionInfo): Datasource;
    resolveAlias(entityAlias: EntityAlias, stateParams: StateParams): Observable<AliasInfo>;
    resolveAliasFilter(filter: EntityAliasFilter, stateParams: StateParams): Observable<EntityAliasFilterResult>;
    checkEntityAlias(entityAlias: EntityAlias): Observable<boolean>;
    saveEntityParameters(customerId: CustomerId, entityType: EntityType, entityGroupId: string, entityData: ImportEntityData, update: boolean, config?: RequestConfig): Observable<ImportEntitiesResultInfo>;
    private getSaveEntityObservable;
    private getUpdateEntityTasks;
    saveEntityData(entityId: EntityId, entityData: ImportEntityData, config?: RequestConfig): Observable<any>;
    private getStateEntityInfo;
    private resolveAliasEntityId;
    private createDatasourceFromSubscriptionInfo;
    private validateSubscriptionInfo;
    private prepareEntityFilterFromSubscriptionInfo;
    private createDatasourceKeys;
    getAssignedToEdgeEntitiesByType(edgeId: string, entityType?: EntityType, pageLink?: PageLink): Observable<any>;
    getEdgeEventContent(entity: EdgeEvent): Observable<BaseData<HasId> | RuleChainMetaData | string>;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<EntityService>;
}
