import { OnInit } from '@angular/core';
import { UserService } from '@core/http/user.service';
import { User } from '@shared/models/user.model';
import { Authority } from '@shared/models/authority.enum';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { HasConfirmForm } from '@core/guards/confirm-on-exit.guard';
import { TranslateService } from '@ngx-translate/core';
import { ActivatedRoute } from '@angular/router';
import { AuthService } from '@core/auth/auth.service';
import { UnitSystem } from '@shared/models/unit.models';
import { UnitService } from '@core/services/unit.service';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import * as i0 from "@angular/core";
export declare class ProfileComponent extends PageComponent implements OnInit, HasConfirmForm {
    protected store: Store<AppState>;
    private route;
    private userService;
    private authService;
    private translate;
    private unitService;
    private fb;
    private userPermissionsService;
    authorities: typeof Authority;
    profile: UntypedFormGroup;
    user: User;
    languageList: [locelCode: string, localeLanguage: string];
    UnitSystems: UnitSystem[];
    authState: import("../../../../core/public-api").AuthState;
    readonly: boolean;
    constructor(store: Store<AppState>, route: ActivatedRoute, userService: UserService, authService: AuthService, translate: TranslateService, unitService: UnitService, fb: UntypedFormBuilder, userPermissionsService: UserPermissionsService);
    ngOnInit(): void;
    private buildProfileForm;
    save(): void;
    private userLoaded;
    confirmForm(): UntypedFormGroup;
    static ɵfac: i0.ɵɵFactoryDeclaration<ProfileComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ProfileComponent, "tb-profile", never, {}, {}, never, never, false, never>;
}
