import { EventEmitter } from '@angular/core';
import { AppState, NodeScriptTestService } from '@core/public-api';
import { Store } from '@ngrx/store';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { MatChipInputEvent } from '@angular/material/chips';
import { RuleNodeConfiguration, RuleNodeConfigurationComponent, ScriptLanguage } from '@app/shared/models/rule-node.models';
import type { JsFuncComponent } from '@app/shared/components/js-func.component';
import { AlarmSeverity } from '@app/shared/models/alarm.models';
import { DebugRuleNodeEventBody } from '@shared/models/event.models';
import * as i0 from "@angular/core";
export declare class CreateAlarmConfigComponent extends RuleNodeConfigurationComponent {
    protected store: Store<AppState>;
    private fb;
    private nodeScriptTestService;
    private translate;
    jsFuncComponent: JsFuncComponent;
    tbelFuncComponent: JsFuncComponent;
    alarmSeverities: string[];
    alarmSeverityTranslationMap: Map<AlarmSeverity, string>;
    createAlarmConfigForm: UntypedFormGroup;
    separatorKeysCodes: number[];
    tbelEnabled: boolean;
    scriptLanguage: typeof ScriptLanguage;
    changeScript: EventEmitter<void>;
    readonly hasScript = true;
    readonly testScriptLabel = "rule-node-config.test-details-function";
    constructor(store: Store<AppState>, fb: UntypedFormBuilder, nodeScriptTestService: NodeScriptTestService, translate: TranslateService);
    protected configForm(): UntypedFormGroup;
    protected onConfigurationSet(configuration: RuleNodeConfiguration): void;
    protected validatorTriggers(): string[];
    protected updateValidators(emitEvent: boolean): void;
    protected prepareInputConfig(configuration: RuleNodeConfiguration): RuleNodeConfiguration;
    testScript(debugEventBody?: DebugRuleNodeEventBody): void;
    removeKey(key: string, keysField: string): void;
    addKey(event: MatChipInputEvent, keysField: string): void;
    protected onValidate(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<CreateAlarmConfigComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CreateAlarmConfigComponent, "tb-action-node-create-alarm-config", never, {}, {}, never, never, false, never>;
}
