import { DestroyRef, EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { AliasEntityType, EntityType } from '@shared/models/entity-type.models';
import { EntityService } from '@core/http/entity.service';
import { EntityId } from '@shared/models/id/entity-id';
import { Operation } from '@shared/models/security.models';
import { MatFormFieldAppearance } from '@angular/material/form-field';
import { BaseData } from '@shared/models/base-data';
import { EntityAutocompleteComponent } from '@shared/components/entity/entity-autocomplete.component';
import * as i0 from "@angular/core";
export declare class EntitySelectComponent implements ControlValueAccessor, OnInit {
    private store;
    private entityService;
    translate: TranslateService;
    private fb;
    private destroyRef;
    entityAutocompleteComponent: EntityAutocompleteComponent;
    entitySelectFormGroup: UntypedFormGroup;
    modelValue: EntityId;
    allowedEntityTypes: Array<EntityType | AliasEntityType>;
    useAliasEntityTypes: boolean;
    operation: Operation;
    required: boolean;
    disabled: boolean;
    additionEntityTypes: {
        [entityType in string]: string;
    };
    appearance: MatFormFieldAppearance;
    useEntityDisplayName: boolean;
    filterAllowedEntityTypes: boolean;
    defaultEntityType: AliasEntityType | EntityType;
    entityTypeLabel: string;
    entityChanged: EventEmitter<BaseData<EntityId>>;
    displayEntityTypeSelect: boolean;
    AliasEntityType: typeof AliasEntityType;
    entityTypeNullUUID: Set<string>;
    private propagateChange;
    constructor(store: Store<AppState>, entityService: EntityService, translate: TranslateService, fb: UntypedFormBuilder, destroyRef: DestroyRef);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: EntityId | null): void;
    updateView(entityType: EntityType | AliasEntityType | null, entityId: string | null): void;
    changeEntity(entity: BaseData<EntityId>): void;
    entityAutocompleteMarkAsTouched(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntitySelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntitySelectComponent, "tb-entity-select", never, { "allowedEntityTypes": { "alias": "allowedEntityTypes"; "required": false; }; "useAliasEntityTypes": { "alias": "useAliasEntityTypes"; "required": false; }; "operation": { "alias": "operation"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "additionEntityTypes": { "alias": "additionEntityTypes"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; "useEntityDisplayName": { "alias": "useEntityDisplayName"; "required": false; }; "filterAllowedEntityTypes": { "alias": "filterAllowedEntityTypes"; "required": false; }; "defaultEntityType": { "alias": "defaultEntityType"; "required": false; }; "entityTypeLabel": { "alias": "entityTypeLabel"; "required": false; }; }, { "entityChanged": "entityChanged"; }, never, never, false, never>;
}
