import { AfterViewInit, OnInit } from '@angular/core';
import { ControlValueAccessor, FormBuilder, FormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@app/core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { AliasEntityType, EntityType } from '@app/shared/models/entity-type.models';
import { EntityService } from '@core/http/entity.service';
import * as i0 from "@angular/core";
export declare class EntityTypeSelectComponent implements ControlValueAccessor, OnInit, AfterViewInit {
    private store;
    private entityService;
    translate: TranslateService;
    private fb;
    entityTypeFormGroup: FormGroup;
    modelValue: EntityType | AliasEntityType | null;
    allowedEntityTypes: Array<EntityType | AliasEntityType>;
    useAliasEntityTypes: boolean;
    private showLabelValue;
    get showLabel(): boolean;
    set showLabel(value: boolean);
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    disabled: boolean;
    entityTypes: Array<EntityType | AliasEntityType>;
    private propagateChange;
    constructor(store: Store<AppState>, entityService: EntityService, translate: TranslateService, fb: FormBuilder);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: EntityType | AliasEntityType | null): void;
    updateView(value: EntityType | AliasEntityType | null): void;
    displayEntityTypeFn(entityType?: EntityType | AliasEntityType | null): string | undefined;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityTypeSelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntityTypeSelectComponent, "tb-entity-type-select", never, { "allowedEntityTypes": "allowedEntityTypes"; "useAliasEntityTypes": "useAliasEntityTypes"; "showLabel": "showLabel"; "required": "required"; "disabled": "disabled"; }, {}, never, never>;
}
