import { AfterViewInit, OnInit } from '@angular/core';
import { ControlValueAccessor, FormBuilder, FormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { AliasEntityType, EntityType } from '@shared/models/entity-type.models';
import { EntityService } from '@core/http/entity.service';
import { EntityId } from '@shared/models/id/entity-id';
import { Operation } from '@shared/models/security.models';
import * as i0 from "@angular/core";
export declare class EntitySelectComponent implements ControlValueAccessor, OnInit, AfterViewInit {
    private store;
    private entityService;
    translate: TranslateService;
    private fb;
    entitySelectFormGroup: FormGroup;
    modelValue: EntityId;
    allowedEntityTypes: Array<EntityType | AliasEntityType>;
    useAliasEntityTypes: boolean;
    operation: Operation;
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    disabled: boolean;
    displayEntityTypeSelect: boolean;
    AliasEntityType: typeof AliasEntityType;
    private readonly defaultEntityType;
    private propagateChange;
    constructor(store: Store<AppState>, entityService: EntityService, translate: TranslateService, fb: FormBuilder);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: EntityId | null): void;
    updateView(entityType: EntityType | AliasEntityType | null, entityId: string | null): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntitySelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntitySelectComponent, "tb-entity-select", never, { "allowedEntityTypes": "allowedEntityTypes"; "useAliasEntityTypes": "useAliasEntityTypes"; "operation": "operation"; "required": "required"; "disabled": "disabled"; }, {}, never, never>;
}
