import { AfterViewInit, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@app/core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { EntityType } from '@app/shared/models/entity-type.models';
import { BroadcastService } from '@app/core/services/broadcast.service';
import { MatFormFieldAppearance } from '@angular/material/form-field';
import { EntityService } from '@core/http/entity.service';
import * as i0 from "@angular/core";
export declare class EntitySubTypeAutocompleteComponent implements ControlValueAccessor, OnInit, AfterViewInit, OnDestroy {
    private store;
    private broadcast;
    translate: TranslateService;
    private fb;
    private entityService;
    subTypeFormGroup: UntypedFormGroup;
    modelValue: string | null;
    entityType: EntityType;
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    disabled: boolean;
    excludeSubTypes: Array<string>;
    appearance: MatFormFieldAppearance;
    subTypeInput: ElementRef;
    selectEntitySubtypeText: string;
    entitySubtypeText: string;
    entitySubtypeRequiredText: string;
    entitySubtypeMaxLength: string;
    filteredSubTypes: Observable<Array<string>>;
    subTypes: Observable<Array<string>>;
    private broadcastSubscription;
    searchText: string;
    private dirty;
    private propagateChange;
    constructor(store: Store<AppState>, broadcast: BroadcastService, translate: TranslateService, fb: UntypedFormBuilder, entityService: EntityService);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: string | null): void;
    onFocus(): void;
    updateView(value: string | null): void;
    displaySubTypeFn(subType?: string): string | undefined;
    fetchSubTypes(searchText?: string, strictMatch?: boolean): Observable<Array<string>>;
    getSubTypes(): Observable<Array<string>>;
    clear(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntitySubTypeAutocompleteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntitySubTypeAutocompleteComponent, "tb-entity-subtype-autocomplete", never, { "entityType": { "alias": "entityType"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "excludeSubTypes": { "alias": "excludeSubTypes"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; }, {}, never, never, false, never>;
}
