import { AfterViewInit, OnDestroy, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@app/core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { EntityType } from '@app/shared/models/entity-type.models';
import { BroadcastService } from '@app/core/services/broadcast.service';
import { SubscriptSizing } from '@angular/material/form-field';
import { EntityService } from '@core/http/entity.service';
import * as i0 from "@angular/core";
export declare class EntitySubTypeSelectComponent implements ControlValueAccessor, OnInit, AfterViewInit, OnDestroy {
    private store;
    private broadcast;
    translate: TranslateService;
    private fb;
    private entityService;
    subTypeFormGroup: UntypedFormGroup;
    modelValue: string | null;
    subscriptSizing: SubscriptSizing;
    entityType: EntityType;
    showLabel: boolean;
    required: boolean;
    disabled: boolean;
    typeTranslatePrefix: string;
    entitySubtypeTitle: string;
    entitySubtypeRequiredText: string;
    subTypesOptions: Observable<Array<string>>;
    private subTypesOptionsSubject;
    private subTypes;
    subTypesLoaded: boolean;
    private broadcastSubscription;
    private propagateChange;
    constructor(store: Store<AppState>, broadcast: BroadcastService, translate: TranslateService, fb: UntypedFormBuilder, entityService: EntityService);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: string | null): void;
    updateView(value: string | null): void;
    displaySubTypeFn(subType?: string): string | undefined;
    findSubTypes(searchText: string): Observable<Array<string>>;
    getSubTypes(): Observable<Array<string>>;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntitySubTypeSelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntitySubTypeSelectComponent, "tb-entity-subtype-select", never, { "subscriptSizing": { "alias": "subscriptSizing"; "required": false; }; "entityType": { "alias": "entityType"; "required": false; }; "showLabel": { "alias": "showLabel"; "required": false; }; "required": { "alias": "required"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "typeTranslatePrefix": { "alias": "typeTranslatePrefix"; "required": false; }; }, {}, never, never, false, never>;
}
