import { AfterViewInit, OnDestroy, OnInit } from '@angular/core';
import { ControlValueAccessor, FormBuilder, FormGroup } from '@angular/forms';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@app/core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { DeviceService } from '@core/http/device.service';
import { EntitySubtype, EntityType } from '@app/shared/models/entity-type.models';
import { BroadcastService } from '@app/core/services/broadcast.service';
import { AssetService } from '@core/http/asset.service';
import { EdgeService } from '@core/http/edge.service';
import { EntityViewService } from '@core/http/entity-view.service';
import * as i0 from "@angular/core";
export declare class EntitySubTypeSelectComponent implements ControlValueAccessor, OnInit, AfterViewInit, OnDestroy {
    private store;
    private broadcast;
    translate: TranslateService;
    private deviceService;
    private assetService;
    private edgeService;
    private entityViewService;
    private fb;
    subTypeFormGroup: FormGroup;
    modelValue: string | null;
    entityType: EntityType;
    showLabel: boolean;
    required: boolean;
    disabled: boolean;
    typeTranslatePrefix: string;
    entitySubtypeTitle: string;
    entitySubtypeRequiredText: string;
    subTypesOptions: Observable<Array<EntitySubtype | string>>;
    private subTypesOptionsSubject;
    subTypes: Observable<Array<EntitySubtype | string>>;
    subTypesLoaded: boolean;
    private broadcastSubscription;
    private propagateChange;
    constructor(store: Store<AppState>, broadcast: BroadcastService, translate: TranslateService, deviceService: DeviceService, assetService: AssetService, edgeService: EdgeService, entityViewService: EntityViewService, fb: FormBuilder);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: string | null): void;
    updateView(value: string | null): void;
    displaySubTypeFn(subType?: EntitySubtype | string): string | undefined;
    findSubTypes(searchText?: string): Observable<Array<EntitySubtype | string>>;
    getSubTypes(): Observable<Array<EntitySubtype | string>>;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntitySubTypeSelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntitySubTypeSelectComponent, "tb-entity-subtype-select", never, { "entityType": "entityType"; "showLabel": "showLabel"; "required": "required"; "disabled": "disabled"; "typeTranslatePrefix": "typeTranslatePrefix"; }, {}, never, never>;
}
