import { AfterViewInit, ChangeDetectorRef, ElementRef, OnDestroy, OnInit, TemplateRef } from '@angular/core';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import { ScadaSymbolObject, ScadaSymbolObjectCallbacks } from '@home/components/widget/lib/scada/scada-symbol.models';
import { Observable } from 'rxjs';
import { ComponentStyle } from '@shared/models/widget-settings.models';
import { ImageService } from '@core/http/image.service';
import { WidgetComponent } from '@home/components/widget/widget.component';
import { WidgetContext } from '@home/models/widget-component.models';
import { MatIconRegistry } from '@angular/material/icon';
import { RafService } from '@core/services/raf.service';
import * as i0 from "@angular/core";
export declare class ScadaSymbolWidgetComponent implements OnInit, AfterViewInit, OnDestroy, ScadaSymbolObjectCallbacks {
    widgetComponent: WidgetComponent;
    protected imagePipe: ImagePipe;
    protected sanitizer: DomSanitizer;
    private imageService;
    private iconRegistry;
    private raf;
    protected cd: ChangeDetectorRef;
    scadaSymbolShape: ElementRef<HTMLElement>;
    ctx: WidgetContext;
    widgetTitlePanel: TemplateRef<any>;
    private loadingSubject;
    private settings;
    private scadaSymbolContent$;
    backgroundStyle$: Observable<ComponentStyle>;
    overlayStyle: ComponentStyle;
    padding: string;
    loading$: Observable<boolean>;
    scadaSymbolObject: ScadaSymbolObject;
    noScadaSymbol: boolean;
    constructor(widgetComponent: WidgetComponent, imagePipe: ImagePipe, sanitizer: DomSanitizer, imageService: ImageService, iconRegistry: MatIconRegistry, raf: RafService, cd: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onInit(): void;
    onScadaSymbolObjectLoadingState(loading: boolean): void;
    onScadaSymbolObjectError(error: string): void;
    onScadaSymbolObjectMessage(message: string): void;
    private initObject;
    static ɵfac: i0.ɵɵFactoryDeclaration<ScadaSymbolWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ScadaSymbolWidgetComponent, "tb-scada-symbol-widget", never, { "ctx": { "alias": "ctx"; "required": false; }; "widgetTitlePanel": { "alias": "widgetTitlePanel"; "required": false; }; }, {}, never, never, false, never>;
}
