import { AfterViewInit, ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormControl, UntypedFormGroup, FormGroupDirective, NgForm } from '@angular/forms';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@app/core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { IAliasController } from '@core/api/widget-api.models';
import { TruncatePipe } from '@shared/pipe/truncate.pipe';
import { MatAutocomplete, MatAutocompleteTrigger } from '@angular/material/autocomplete';
import { ErrorStateMatcher } from '@angular/material/core';
import { FilterSelectCallbacks } from '@home/components/filter/filter-select.component.models';
import { Filter } from '@shared/models/query/query.models';
import * as i0 from "@angular/core";
export declare class FilterSelectComponent implements ControlValueAccessor, OnInit, AfterViewInit, ErrorStateMatcher {
    private store;
    private errorStateMatcher;
    translate: TranslateService;
    truncate: TruncatePipe;
    private fb;
    selectFilterFormGroup: UntypedFormGroup;
    modelValue: string | null;
    aliasController: IAliasController;
    callbacks: FilterSelectCallbacks;
    showLabel: boolean;
    filterAutocomplete: MatAutocomplete;
    autoCompleteTrigger: MatAutocompleteTrigger;
    private requiredValue;
    get tbRequired(): boolean;
    set tbRequired(value: boolean);
    disabled: boolean;
    filterInput: ElementRef;
    filterList: Array<Filter>;
    filteredFilters: Observable<Array<Filter>>;
    searchText: string;
    private dirty;
    private creatingFilter;
    private propagateChange;
    constructor(store: Store<AppState>, errorStateMatcher: ErrorStateMatcher, translate: TranslateService, truncate: TruncatePipe, fb: UntypedFormBuilder);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    isErrorState(control: UntypedFormControl | null, form: FormGroupDirective | NgForm | null): boolean;
    ngAfterViewInit(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: string | null): void;
    onFocus(): void;
    updateView(value: Filter | null): void;
    displayFilterFn(filter?: Filter): string | undefined;
    fetchFilters(searchText?: string): Observable<Array<Filter>>;
    clear(value?: string): void;
    textIsNotEmpty(text: string): boolean;
    filterEnter($event: KeyboardEvent): void;
    createFilter($event: Event, filter: string, focusOnCancel?: boolean): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<FilterSelectComponent, [null, { skipSelf: true; }, null, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FilterSelectComponent, "tb-filter-select", never, { "aliasController": { "alias": "aliasController"; "required": false; }; "callbacks": { "alias": "callbacks"; "required": false; }; "showLabel": { "alias": "showLabel"; "required": false; }; "tbRequired": { "alias": "tbRequired"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; }, {}, never, never, false, never>;
}
