import { DestroyRef, OnChanges, OnDestroy, OnInit, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormControl } from '@angular/forms';
import { EditorOptions } from 'tinymce';
import { HtmlWithImagePipe } from '@shared/pipe/html-with-image.pipe';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import { ReportVariable } from '@home/pages/reporting/template/components/report-component.models';
import { EditorComponent } from '@tinymce/tinymce-angular';
import { MatIconRegistry } from '@angular/material/icon';
import * as i0 from "@angular/core";
export declare class ReportRichTextComponent implements OnInit, ControlValueAccessor, OnChanges, OnDestroy {
    private fb;
    private translate;
    private dialog;
    private iconRegistry;
    private htmlWithImagePipe;
    private destroyRef;
    editorComponent: import("@angular/core").Signal<EditorComponent>;
    disabled: boolean;
    variables: ReportVariable[];
    background: string;
    tinyMceOptions: Partial<EditorOptions>;
    richTextFormControl: UntypedFormControl;
    private modelValue;
    private propagateChange;
    private domParser;
    constructor(fb: UntypedFormBuilder, translate: TranslateService, dialog: MatDialog, iconRegistry: MatIconRegistry, htmlWithImagePipe: HtmlWithImagePipe, destroyRef: DestroyRef);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: string): void;
    private updateModel;
    private setupEditor;
    private updateEditorBackground;
    private setupTbImagePlugin;
    private setupMediumFontWeight;
    private toggleMediumWeightFormat;
    private setupVariables;
    private setImageSrcCallback;
    private getImageSrcCallback;
    private customImageUrlCallback;
    private processImages;
    private editorImageAction;
    private extractImageData;
    private insertOrUpdateImage;
    private variableIcon;
    static ɵfac: i0.ɵɵFactoryDeclaration<ReportRichTextComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ReportRichTextComponent, "tb-report-rich-text", never, { "disabled": { "alias": "disabled"; "required": false; }; "variables": { "alias": "variables"; "required": false; }; "background": { "alias": "background"; "required": false; }; }, {}, never, never, false, never>;
}
