import { Injector, NgZone } from '@angular/core';
import { UtilsService } from '@core/services/utils.service';
import { WidgetContext } from '@home/models/widget-component.models';
import { Datasource, widgetType } from '@shared/models/widget.models';
import { Timewindow } from '@shared/models/time/time.models';
import { Observable } from 'rxjs';
import { WidgetSubscriptionCallbacks } from '@core/api/widget-api.models';
import { DashboardUtilsService } from '@core/services/dashboard-utils.service';
import { EntityDataService } from '@core/api/entity-data.service';
import { TranslateService } from '@ngx-translate/core';
import { TimeService } from '@core/services/time.service';
import { RafService } from '@core/services/raf.service';
import { DatePipe } from '@angular/common';
import * as i0 from "@angular/core";
export type GenerateDataFunction = (random: () => number, time: number) => any;
export declare class ReportWidgetContextService {
    private utils;
    private ngZone;
    private dashboardUtils;
    private timeService;
    private raf;
    private translate;
    private entityDataService;
    private date;
    private injector;
    constructor(utils: UtilsService, ngZone: NgZone, dashboardUtils: DashboardUtilsService, timeService: TimeService, raf: RafService, translate: TranslateService, entityDataService: EntityDataService, date: DatePipe, injector: Injector);
    createWidgetContext(type: widgetType, settings: any, timewindow: Timewindow, datasources: Datasource[], units: string, decimals: number, stateData: boolean, callbacks: WidgetSubscriptionCallbacks, genDataFunc?: GenerateDataFunction): Observable<WidgetContext>;
    destroyWidgetContext(ctx: WidgetContext): void;
    private createWidget;
    private prepareDatasources;
    private prepareDataKey;
    private createKeyRandom;
    private reportPreviewKeyData;
    private createDefaultSubscription;
    private createSubscription;
    private createSubscriptionContext;
    static ɵfac: i0.ɵɵFactoryDeclaration<ReportWidgetContextService, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<ReportWidgetContextService>;
}
