import { AfterViewInit, OnDestroy, ViewContainerRef } from '@angular/core';
import { TimeseriesChartReportComponentConfig } from '@shared/models/report-component.models';
import { AbstractReportComponentPreview } from '@home/pages/reporting/template/components/report-component.component';
import { IWidgetSubscription, WidgetSubscriptionCallbacks } from '@core/api/widget-api.models';
import { ComponentStyle } from '@shared/models/widget-settings.models';
import { TimeSeriesChartType } from '@home/components/widget/lib/chart/time-series-chart.models';
import * as i0 from "@angular/core";
export declare class TimeSeriesChartPreviewComponent extends AbstractReportComponentPreview<TimeseriesChartReportComponentConfig> implements AfterViewInit, OnDestroy, WidgetSubscriptionCallbacks {
    widgetContainer: ViewContainerRef;
    barChartWithLabels: boolean;
    rangeChart: boolean;
    chartType: TimeSeriesChartType;
    private reportWidgetContextService;
    private translate;
    imageWidth: string;
    imageHeightPx: number;
    imageAlign: string;
    showTitle: boolean;
    title: string;
    titleStyle: ComponentStyle;
    hasData: boolean;
    noDataMessage: string;
    chartTypeTitle: string;
    private viewInited;
    private widgetContext;
    private widgetComponentRef;
    private widgetComponent;
    private updateWidgetPreview;
    onComponentUpdated(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onDataUpdated(_subscription: IWidgetSubscription, _detectChanges: boolean): void;
    onLatestDataUpdated(_subscription: IWidgetSubscription, _detectChanges: boolean): void;
    private destroyWidget;
    private updateTimeSeriesWidgetPreview;
    private getDefaultSettings;
    static ɵfac: i0.ɵɵFactoryDeclaration<TimeSeriesChartPreviewComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TimeSeriesChartPreviewComponent, "tb-time-series-chart-preview", never, { "barChartWithLabels": { "alias": "barChartWithLabels"; "required": false; }; "rangeChart": { "alias": "rangeChart"; "required": false; }; "chartType": { "alias": "chartType"; "required": false; }; }, {}, never, never, false, never>;
}
