import { ChangeDetectorRef, DestroyRef, Renderer2 } from '@angular/core';
import { EntityId } from '@shared/models/id/entity-id';
import { EntitiesTableComponent } from '@home/components/entity/entities-table.component';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { CalculatedFieldsService } from '@core/http/calculated-fields.service';
import { ImportExportService } from '@shared/import-export/import-export.service';
import { EntityDebugSettingsService } from '@home/components/entity/debug/entity-debug-settings.service';
import { DatePipe } from '@angular/common';
import { AlarmRulesTableConfig } from "@home/components/alarm-rules/alarm-rules-table-config";
import { UtilsService } from "@core/services/utils.service";
import { ActivatedRoute, Router } from "@angular/router";
import { UserPermissionsService } from "@core/http/user-permissions.service";
import * as i0 from "@angular/core";
export declare class AlarmRulesTableComponent {
    private calculatedFieldsService;
    private translate;
    private dialog;
    private store;
    private datePipe;
    private cd;
    private renderer;
    private importExportService;
    private entityDebugSettingsService;
    private utilsService;
    private destroyRef;
    private route;
    private router;
    private userPermissionsService;
    entitiesTable: EntitiesTableComponent;
    active: import("@angular/core").InputSignal<boolean>;
    entityId: import("@angular/core").InputSignal<EntityId>;
    entityName: import("@angular/core").InputSignal<string>;
    ownerId: import("@angular/core").InputSignal<EntityId>;
    readonly: import("@angular/core").InputSignal<boolean>;
    hideClearEventAction: import("@angular/core").InputSignal<boolean>;
    alarmRulesTableConfig: AlarmRulesTableConfig;
    pageMode: boolean;
    constructor(calculatedFieldsService: CalculatedFieldsService, translate: TranslateService, dialog: MatDialog, store: Store<AppState>, datePipe: DatePipe, cd: ChangeDetectorRef, renderer: Renderer2, importExportService: ImportExportService, entityDebugSettingsService: EntityDebugSettingsService, utilsService: UtilsService, destroyRef: DestroyRef, route: ActivatedRoute, router: Router, userPermissionsService: UserPermissionsService);
    static ɵfac: i0.ɵɵFactoryDeclaration<AlarmRulesTableComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AlarmRulesTableComponent, "tb-alarm-rules-table", never, { "active": { "alias": "active"; "required": false; "isSignal": true; }; "entityId": { "alias": "entityId"; "required": false; "isSignal": true; }; "entityName": { "alias": "entityName"; "required": false; "isSignal": true; }; "ownerId": { "alias": "ownerId"; "required": false; "isSignal": true; }; "readonly": { "alias": "readonly"; "required": false; "isSignal": true; }; "hideClearEventAction": { "alias": "hideClearEventAction"; "required": false; "isSignal": true; }; }, {}, never, never, false, never>;
}
