import { DestroyRef, ElementRef, InjectionToken, OnInit, TemplateRef, ViewContainerRef } from '@angular/core';
import { ControlValueAccessor, FormBuilder, FormGroup } from '@angular/forms';
import { Overlay, OverlayRef } from '@angular/cdk/overlay';
import { TranslateService } from '@ngx-translate/core';
import { EntityType } from '@shared/models/entity-type.models';
import { UtilsService } from '@core/services/utils.service';
import { AlarmRuleFilterConfig } from "@shared/models/alarm-rule.models";
import { UserPermissionsService } from "@core/http/user-permissions.service";
import * as i0 from "@angular/core";
export declare const ALARM_FILTER_CONFIG_DATA: InjectionToken<any>;
export interface AlarmRuleFilterConfigData {
    panelMode: boolean;
    userMode: boolean;
    alarmRuleFilterConfig: AlarmRuleFilterConfig;
    initialAlarmRuleFilterConfig?: AlarmRuleFilterConfig;
}
export declare class AlarmRuleFilterConfigComponent implements OnInit, ControlValueAccessor {
    private data;
    private overlayRef;
    private fb;
    private translate;
    private overlay;
    private nativeElement;
    private viewContainerRef;
    private utils;
    private destroyRef;
    private userPermissionsService;
    alarmRuleFilterPanel: TemplateRef<any>;
    disabled: boolean;
    buttonMode: boolean;
    initialAlarmRuleFilterConfig: AlarmRuleFilterConfig;
    panelMode: boolean;
    buttonDisplayValue: any;
    alarmRuleFilterConfigForm: FormGroup;
    alarmFilterOverlayRef: OverlayRef;
    panelResult: AlarmRuleFilterConfig;
    entityType: typeof EntityType;
    listEntityTypes: EntityType[];
    entityTypeTranslations: Map<EntityType | import("@shared/models/entity-type.models").AliasEntityType, import("@shared/models/entity-type.models").EntityTypeTranslation>;
    private alarmRuleFilterConfig;
    private resizeWindows;
    private propagateChange;
    constructor(data: AlarmRuleFilterConfigData | undefined, overlayRef: OverlayRef, fb: FormBuilder, translate: TranslateService, overlay: Overlay, nativeElement: ElementRef, viewContainerRef: ViewContainerRef, utils: UtilsService, destroyRef: DestroyRef, userPermissionsService: UserPermissionsService);
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(alarmRuleFilterConfig?: AlarmRuleFilterConfig): void;
    toggleAlarmRuleFilterPanel($event: Event): void;
    cancel(): void;
    update(): void;
    reset(): void;
    private alarmRuleFilterConfigEquals;
    private updateAlarmRuleConfigForm;
    private alarmRuleConfigUpdated;
    private alarmRuleFilterConfigFromFormValue;
    private updateButtonDisplayValue;
    private customTranslate;
    static ɵfac: i0.ɵɵFactoryDeclaration<AlarmRuleFilterConfigComponent, [{ optional: true; }, { optional: true; }, null, null, null, null, null, null, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AlarmRuleFilterConfigComponent, "tb-alarm-rule-filter-config", never, { "disabled": { "alias": "disabled"; "required": false; }; "buttonMode": { "alias": "buttonMode"; "required": false; }; "initialAlarmRuleFilterConfig": { "alias": "initialAlarmRuleFilterConfig"; "required": false; }; }, {}, never, never, false, never>;
}
