import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import { PageLink } from '@shared/models/page/page-link';
import { Observable } from 'rxjs';
import { PageData } from '@shared/models/page/page-data';
import { EntityId } from '@shared/models/id/entity-id';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { DestroyRef, Renderer2 } from '@angular/core';
import { CalculatedFieldsService } from '@core/http/calculated-fields.service';
import { CalculatedField, CalculatedFieldInfo, CalculatedFieldsQuery } from '@shared/models/calculated-field.models';
import { ImportExportService } from '@shared/import-export/import-export.service';
import { EntityDebugSettingsService } from '@home/components/entity/debug/entity-debug-settings.service';
import { DatePipe } from '@angular/common';
import { UtilsService } from "@core/services/utils.service";
import { Router } from '@angular/router';
import { UserPermissionsService } from "@core/http/user-permissions.service";
type AlarmRuleTableEntity = CalculatedField | CalculatedFieldInfo;
export declare class AlarmRulesTableConfig extends EntityTableConfig<AlarmRuleTableEntity> {
    private calculatedFieldsService;
    private translate;
    private dialog;
    private datePipe;
    private entityId;
    private store;
    private destroyRef;
    private renderer;
    private entityName;
    private ownerId;
    private importExportService;
    private entityDebugSettingsService;
    private utilsService;
    private router;
    private readonly;
    private hideClearEventAction;
    private userPermissionsService;
    pageMode: boolean;
    readonly tenantId: string;
    additionalDebugActionConfig: {
        title: any;
        action: (calculatedField: AlarmRuleTableEntity) => any;
    };
    alarmRuleFilterConfig: CalculatedFieldsQuery;
    constructor(calculatedFieldsService: CalculatedFieldsService, translate: TranslateService, dialog: MatDialog, datePipe: DatePipe, entityId: EntityId, store: Store<AppState>, destroyRef: DestroyRef, renderer: Renderer2, entityName: string, ownerId: EntityId, importExportService: ImportExportService, entityDebugSettingsService: EntityDebugSettingsService, utilsService: UtilsService, router: Router, readonly: boolean, hideClearEventAction: boolean, userPermissionsService: UserPermissionsService, pageMode?: boolean);
    fetchCalculatedFields(pageLink: PageLink): Observable<PageData<AlarmRuleTableEntity>>;
    private allowWritePermission;
    onOpenDebugConfig($event: Event, calculatedField: AlarmRuleTableEntity): void;
    private editCalculatedField;
    private copyCalculatedField;
    private getCalculatedAlarmDialog;
    private openDebugEventsDialog;
    private openDebugTab;
    private exportAlarmRule;
    private importCalculatedField;
    private updateImportedCalculatedField;
    private onDebugConfigChanged;
    private getTestScriptDialog;
    private openCalculatedField;
    private onCFAction;
}
export {};
