import { DestroyRef } from '@angular/core';
import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { FormGroup } from '@angular/forms';
import { Router } from '@angular/router';
import { DialogComponent } from '@shared/components/dialog.component';
import { CalculatedField, CalculatedFieldArgument, CalculatedFieldType } from '@shared/models/calculated-field.models';
import { EntityType } from '@shared/models/entity-type.models';
import { ScriptLanguage } from '@shared/models/rule-node.models';
import { CalculatedFieldsService } from '@core/http/calculated-fields.service';
import { EntityId } from '@shared/models/id/entity-id';
import { AdditionalDebugActionConfig } from '@home/components/entity/debug/entity-debug-settings.model';
import { AlarmRuleTestScriptFn } from "@shared/models/alarm-rule.models";
import { Observable } from "rxjs";
import { UserPermissionsService } from "@core/http/user-permissions.service";
import { StringItemsOption } from "@shared/components/string-items-list.component";
import { BaseData } from "@shared/models/base-data";
import { CalculatedFieldFormService } from '@core/services/calculated-field-form.service';
import { EntitySelectComponent } from '@shared/components/entity/entity-select.component';
import * as i0 from "@angular/core";
export interface AlarmRuleDialogData {
    value?: CalculatedField;
    buttonTitle: string;
    entityId: EntityId;
    tenantId: string;
    entityName?: string;
    ownerId: EntityId;
    additionalDebugActionConfig: AdditionalDebugActionConfig<(calculatedField: CalculatedField) => void>;
    isDirty?: boolean;
    readonly: boolean;
    getTestScriptDialogFn: AlarmRuleTestScriptFn;
}
export declare class AlarmRuleDialogComponent extends DialogComponent<AlarmRuleDialogComponent, CalculatedField> {
    protected store: Store<AppState>;
    protected router: Router;
    data: AlarmRuleDialogData;
    protected dialogRef: MatDialogRef<AlarmRuleDialogComponent, CalculatedField>;
    private calculatedFieldsService;
    private destroyRef;
    private cfFormService;
    private userPermissionsService;
    entitySelect: EntitySelectComponent;
    fieldFormGroup: FormGroup;
    additionalDebugActionConfig: {
        action: () => void;
        title: string;
    };
    alarmRuleEntityTypeList: EntityType[];
    readonly EntityType: typeof EntityType;
    readonly entityTypeTranslations: Map<EntityType | import("@shared/models/entity-type.models").AliasEntityType, import("@shared/models/entity-type.models").EntityTypeTranslation>;
    readonly CalculatedFieldType: typeof CalculatedFieldType;
    readonly ScriptLanguage: typeof ScriptLanguage;
    separatorKeysCodes: number[];
    entityName: string;
    ownerId: EntityId;
    defaultEntityType: EntityType;
    disabledClearRuleButton: boolean;
    disabledArguments: boolean;
    isLoading: boolean;
    constructor(store: Store<AppState>, router: Router, data: AlarmRuleDialogData, dialogRef: MatDialogRef<AlarmRuleDialogComponent, CalculatedField>, calculatedFieldsService: CalculatedFieldsService, destroyRef: DestroyRef, cfFormService: CalculatedFieldFormService, userPermissionsService: UserPermissionsService);
    get configFormGroup(): FormGroup;
    get arguments(): Record<string, CalculatedFieldArgument>;
    removeClearAlarmRule(): void;
    addClearAlarmRule(): void;
    get fromGroupValue(): CalculatedField;
    cancel(): void;
    add(): void;
    private applyDialogData;
    onTestScript(expression: string): Observable<string>;
    private updateRulesValidators;
    get predefinedTypeValues(): StringItemsOption[];
    changeEntity(entity: BaseData<EntityId>): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AlarmRuleDialogComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AlarmRuleDialogComponent, "tb-alarm-rule-dialog", never, {}, {}, never, never, false, never>;
}
