import { AfterViewInit, ChangeDetectorRef, ElementRef, NgZone } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { FormBuilder, FormControl, FormGroup, FormGroupDirective, NgForm } from '@angular/forms';
import { EntityId } from '@shared/models/id/entity-id';
import { AttributeService } from '@core/http/attribute.service';
import { TranslateService } from '@ngx-translate/core';
import { AttributeData } from '@shared/models/telemetry/telemetry.models';
import { PageComponent } from '@shared/components/page.component';
import { PageLink } from '@shared/models/page/page-link';
import { MatSort } from '@angular/material/sort';
import { TelemetryWebsocketService } from '@core/ws/telemetry-websocket.service';
import { MatTableDataSource } from '@angular/material/table';
import { DialogService } from '@core/services/dialog.service';
import { WidgetContext } from '@home/models/widget-component.models';
import { UtilsService } from '@core/services/utils.service';
import { ConnectorConfigurationModes, ConnectorType, GatewayConnector, GatewayLogLevel, MappingType, PortLimits } from './gateway-widget.models';
import { MatDialog } from '@angular/material/dialog';
import { ErrorStateMatcher } from '@angular/material/core';
import * as i0 from "@angular/core";
export declare class ForceErrorStateMatcher implements ErrorStateMatcher {
    isErrorState(control: FormControl | null, form: FormGroupDirective | NgForm | null): boolean;
}
export declare class GatewayConnectorComponent extends PageComponent implements AfterViewInit {
    protected store: Store<AppState>;
    private fb;
    private translate;
    private attributeService;
    private dialogService;
    private dialog;
    private telemetryWsService;
    private zone;
    private utils;
    private cd;
    ctx: WidgetContext;
    device: EntityId;
    nameInput: ElementRef;
    sort: MatSort;
    pageLink: PageLink;
    connectorType: typeof ConnectorType;
    dataSource: MatTableDataSource<AttributeData>;
    displayedColumns: string[];
    mqttVersions: {
        name: number;
        value: number;
    }[];
    gatewayConnectorDefaultTypes: Map<ConnectorType, string>;
    connectorConfigurationModes: typeof ConnectorConfigurationModes;
    connectorForm: FormGroup;
    textSearchMode: boolean;
    activeConnectors: Array<string>;
    gatewayLogLevel: GatewayLogLevel[];
    mappingTypes: typeof MappingType;
    portLimits: typeof PortLimits;
    mode: ConnectorConfigurationModes;
    initialConnector: GatewayConnector;
    private inactiveConnectors;
    private attributeDataSource;
    private inactiveConnectorsDataSource;
    private serverDataSource;
    private activeData;
    private inactiveData;
    private sharedAttributeData;
    private basicConfigSub;
    private subscriptionOptions;
    private destroy$;
    private subscription;
    constructor(store: Store<AppState>, fb: FormBuilder, translate: TranslateService, attributeService: AttributeService, dialogService: DialogService, dialog: MatDialog, telemetryWsService: TelemetryWebsocketService, zone: NgZone, utils: UtilsService, cd: ChangeDetectorRef);
    get portErrorTooltip(): string;
    ngAfterViewInit(): void;
    private uniqNameRequired;
    ngOnDestroy(): void;
    saveConnector(): void;
    private updateData;
    isConnectorSynced(attribute: AttributeData): boolean;
    private combineData;
    private clearOutConnectorForm;
    selectConnector($event: Event, attribute: AttributeData): void;
    isSameConnector(attribute: AttributeData): boolean;
    showToast(message: string): void;
    returnType(attribute: AttributeData): string;
    deleteConnector(attribute: AttributeData, $event: Event): void;
    connectorLogs(attribute: AttributeData, $event: Event): void;
    connectorRpc(attribute: AttributeData, $event: Event): void;
    enableConnector(attribute: AttributeData): void;
    getErrorsCount(attribute: AttributeData): string;
    addConnector($event: Event): void;
    generate(formControlName: string): void;
    private onDataUpdateError;
    private onDataUpdated;
    private generateSubscription;
    private addMQTTConfigControls;
    private createBasicConfigWatcher;
    private confirmConnectorChange;
    private setFormValue;
    private setClientData;
    static ɵfac: i0.ɵɵFactoryDeclaration<GatewayConnectorComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<GatewayConnectorComponent, "tb-gateway-connector", never, { "ctx": "ctx"; "device": "device"; }, {}, never, never, false, never>;
}
