import { ChangeDetectorRef, ElementRef, EventEmitter, OnDestroy, OnInit, Renderer2, ViewContainerRef } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntitiesVersionControlService } from '@core/http/entities-version-control.service';
import { EntityId } from '@shared/models/id/entity-id';
import { TbPopoverComponent } from '@shared/components/popover.component';
import { MatButton } from '@angular/material/button';
import { TbPopoverService } from '@shared/components/popover.service';
import { EntityType } from '@shared/models/entity-type.models';
import * as i0 from "@angular/core";
export declare class EntityVersionDiffComponent extends PageComponent implements OnInit, OnDestroy {
    protected store: Store<AppState>;
    private entitiesVersionControlService;
    private cd;
    private renderer;
    private elementRef;
    private viewContainerRef;
    private popoverService;
    diffViewerElmRef: ElementRef<HTMLElement>;
    versionName: string;
    versionId: string;
    groupType: EntityType;
    entityId: EntityId;
    externalEntityId: EntityId;
    readonly: boolean;
    versionRestored: EventEmitter<void>;
    onClose: () => void;
    popoverComponent: TbPopoverComponent;
    differ: AceDiff;
    contentReady: boolean;
    preferredDiffHeight: string;
    isFullscreen: boolean;
    hasNext: boolean;
    hasPrevious: boolean;
    diffCount: number;
    constructor(store: Store<AppState>, entitiesVersionControlService: EntitiesVersionControlService, cd: ChangeDetectorRef, renderer: Renderer2, elementRef: ElementRef, viewContainerRef: ViewContainerRef, popoverService: TbPopoverService);
    ngOnInit(): void;
    versionIdContent(): string;
    prevDifference($event: Event): void;
    nextDifference($event: Event): void;
    private moveToDiff;
    onFullscreenChanged(fullscreen: boolean): void;
    private getDiffs;
    private getCurrentRow;
    private nextDiff;
    private prevDiff;
    private findNextLine;
    private findPrevLine;
    private updateHasNextAndPrevious;
    private resizeEditors;
    ngOnDestroy(): void;
    close(): void;
    toggleRestoreEntityVersion($event: Event, restoreVersionButton: MatButton): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityVersionDiffComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntityVersionDiffComponent, "tb-entity-version-diff", never, { "versionName": { "alias": "versionName"; "required": false; }; "versionId": { "alias": "versionId"; "required": false; }; "groupType": { "alias": "groupType"; "required": false; }; "entityId": { "alias": "entityId"; "required": false; }; "externalEntityId": { "alias": "externalEntityId"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; "onClose": { "alias": "onClose"; "required": false; }; "popoverComponent": { "alias": "popoverComponent"; "required": false; }; }, { "versionRestored": "versionRestored"; }, never, never, false, never>;
}
