import { ChangeDetectorRef } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityComponent } from '../../components/entity/entity.component';
import { FormBuilder, FormGroup } from '@angular/forms';
import { EntityType } from '@shared/models/entity-type.models';
import { TranslateService } from '@ngx-translate/core';
import { EntityViewInfo } from '@app/shared/models/entity-view.models';
import { Observable } from 'rxjs';
import { DataKeyType } from '@shared/models/telemetry/telemetry.models';
import { EntityId } from '@app/shared/models/id/entity-id';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import * as i0 from "@angular/core";
export declare class EntityViewComponent extends EntityComponent<EntityViewInfo> {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    protected entityValue: EntityViewInfo;
    protected entitiesTableConfigValue: EntityTableConfig<EntityViewInfo>;
    fb: FormBuilder;
    protected cd: ChangeDetectorRef;
    entityType: typeof EntityType;
    dataKeyType: typeof DataKeyType;
    entityViewScope: 'tenant' | 'customer' | 'customer_user' | 'edge';
    allowedEntityTypes: EntityType[];
    maxStartTimeMs: Observable<number | null>;
    minEndTimeMs: Observable<number | null>;
    selectedEntityId: Observable<EntityId | null>;
    constructor(store: Store<AppState>, translate: TranslateService, entityValue: EntityViewInfo, entitiesTableConfigValue: EntityTableConfig<EntityViewInfo>, fb: FormBuilder, cd: ChangeDetectorRef);
    ngOnInit(): void;
    hideDelete(): boolean;
    isAssignedToCustomer(entity: EntityViewInfo): boolean;
    buildForm(entity: EntityViewInfo): FormGroup;
    updateForm(entity: EntityViewInfo): void;
    onEntityViewIdCopied($event: any): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityViewComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntityViewComponent, "tb-entity-view", never, {}, {}, never, never>;
}
