import { ActivatedRouteSnapshot, Resolve, Router } from '@angular/router';
import { CellActionDescriptor, EntityColumn, EntityTableConfig, GroupActionDescriptor, HeaderActionDescriptor } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { EntityAction } from '@home/models/entity/entity-component.models';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { CustomerService } from '@core/http/customer.service';
import { BroadcastService } from '@core/services/broadcast.service';
import { MatDialog } from '@angular/material/dialog';
import { DialogService } from '@core/services/dialog.service';
import { EntityViewInfo } from '@app/shared/models/entity-view.models';
import { EntityViewService } from '@core/http/entity-view.service';
import { EdgeService } from '@core/http/edge.service';
import { UtilsService } from '@core/services/utils.service';
import { AllEntitiesTableConfigService } from '@home/components/entity/all-entities-table-config.service';
import { AuthUser } from '@shared/models/user.model';
import { HomeDialogsService } from '@home/dialogs/home-dialogs.service';
import * as i0 from "@angular/core";
export declare class EntityViewsTableConfigResolver implements Resolve<EntityTableConfig<EntityViewInfo>> {
    private allEntitiesTableConfigService;
    private store;
    private broadcast;
    private entityViewService;
    private customerService;
    private edgeService;
    private dialogService;
    private homeDialogs;
    private translate;
    private datePipe;
    private utils;
    private router;
    private dialog;
    constructor(allEntitiesTableConfigService: AllEntitiesTableConfigService<EntityViewInfo>, store: Store<AppState>, broadcast: BroadcastService, entityViewService: EntityViewService, customerService: CustomerService, edgeService: EdgeService, dialogService: DialogService, homeDialogs: HomeDialogsService, translate: TranslateService, datePipe: DatePipe, utils: UtilsService, router: Router, dialog: MatDialog);
    resolve(route: ActivatedRouteSnapshot): Observable<EntityTableConfig<EntityViewInfo>>;
    configDefaults(config: EntityTableConfig<EntityViewInfo>): void;
    configureColumns(authUser: AuthUser, config: EntityTableConfig<EntityViewInfo>): Array<EntityColumn<EntityViewInfo>>;
    configureEntityFunctions(config: EntityTableConfig<EntityViewInfo>): void;
    configureCellActions(config: EntityTableConfig<EntityViewInfo>): Array<CellActionDescriptor<EntityViewInfo>>;
    configureGroupActions(config: EntityTableConfig<EntityViewInfo>): Array<GroupActionDescriptor<EntityViewInfo>>;
    configureAddActions(config: EntityTableConfig<EntityViewInfo>): Array<HeaderActionDescriptor>;
    private openEntityView;
    manageOwnerAndGroups($event: Event, entityView: EntityViewInfo, config: EntityTableConfig<EntityViewInfo>): void;
    onEntityViewAction(action: EntityAction<EntityViewInfo>, config: EntityTableConfig<EntityViewInfo>): boolean;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityViewsTableConfigResolver, never>;
    static ɵprov: i0.ɵɵInjectableDeclaration<EntityViewsTableConfigResolver>;
}
