import { ChangeDetectorRef, EventEmitter, OnDestroy } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UntypedFormGroup } from '@angular/forms';
import * as i0 from "@angular/core";
export declare class DetailsPanelComponent extends PageComponent implements OnDestroy {
    protected store: Store<AppState>;
    private cd;
    headerHeightPx: number;
    headerTitle: string;
    headerSubtitle: string;
    isReadOnly: boolean;
    isAlwaysEdit: boolean;
    isShowSearch: boolean;
    backgroundColor: string;
    showCloseDetails: boolean;
    private theFormValue;
    private formSubscription;
    set theForm(value: UntypedFormGroup);
    get theForm(): UntypedFormGroup;
    closeDetails: EventEmitter<void>;
    toggleDetailsEditMode: EventEmitter<boolean>;
    applyDetails: EventEmitter<void>;
    closeSearch: EventEmitter<void>;
    isEditValue: boolean;
    showSearchPane: boolean;
    isEditChange: EventEmitter<boolean>;
    get isEdit(): boolean;
    set isEdit(val: boolean);
    constructor(store: Store<AppState>, cd: ChangeDetectorRef);
    ngOnDestroy(): void;
    onCloseDetails(): void;
    onToggleDetailsEditMode(): void;
    onApplyDetails(): void;
    onToggleSearch(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<DetailsPanelComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DetailsPanelComponent, "tb-details-panel", never, { "headerHeightPx": { "alias": "headerHeightPx"; "required": false; }; "headerTitle": { "alias": "headerTitle"; "required": false; }; "headerSubtitle": { "alias": "headerSubtitle"; "required": false; }; "isReadOnly": { "alias": "isReadOnly"; "required": false; }; "isAlwaysEdit": { "alias": "isAlwaysEdit"; "required": false; }; "isShowSearch": { "alias": "isShowSearch"; "required": false; }; "backgroundColor": { "alias": "backgroundColor"; "required": false; }; "showCloseDetails": { "alias": "showCloseDetails"; "required": false; }; "theForm": { "alias": "theForm"; "required": false; }; "isEdit": { "alias": "isEdit"; "required": false; }; }, { "closeDetails": "closeDetails"; "toggleDetailsEditMode": "toggleDetailsEditMode"; "applyDetails": "applyDetails"; "closeSearch": "closeSearch"; "isEditChange": "isEditChange"; }, never, [".prefix-title-buttons", ".header-pane", ".search-pane", ".details-buttons", "*"], false, never>;
}
