import { Injector, OnInit } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { MillisecondsToTimeStringPipe, PageComponent } from '@shared/public-api';
import { Store } from '@ngrx/store';
import { AppState } from '@core/public-api';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import { AlarmsCountMapping } from './alarms-count-mapping.models';
import * as i0 from "@angular/core";
export declare class AlarmsCountMappingTableComponent extends PageComponent implements ControlValueAccessor, OnInit {
    protected store: Store<AppState>;
    translate: TranslateService;
    injector: Injector;
    private millisecondsToTimeStringPipe;
    private dialog;
    disabled: boolean;
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    mappings: Array<AlarmsCountMapping>;
    private propagateChange;
    constructor(store: Store<AppState>, translate: TranslateService, injector: Injector, millisecondsToTimeStringPipe: MillisecondsToTimeStringPipe, dialog: MatDialog);
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState?(isDisabled: boolean): void;
    writeValue(mappings: Array<AlarmsCountMapping>): void;
    mappingDisplayValue(alarmsCountMapping: AlarmsCountMapping): string;
    private filterText;
    private statusFilterText;
    private severityFilterText;
    private typeFilterText;
    private updateFilterText;
    removeAlarmsCountMapping(index: number): void;
    addAlarmsCountMapping($event: Event): void;
    editAlarmsCountMapping($event: Event, aggMapping: AlarmsCountMapping): void;
    private openAlarmsCountMappingDialog;
    private updateModel;
    static ɵfac: i0.ɵɵFactoryDeclaration<AlarmsCountMappingTableComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AlarmsCountMappingTableComponent, "tb-alarms-count-mapping-table", never, { "disabled": { "alias": "disabled"; "required": false; }; "required": { "alias": "required"; "required": false; }; }, {}, never, never, false, never>;
}
