import { ElementRef, EventEmitter, Renderer2 } from '@angular/core';
import { HeaderFooter, TbReportFormat } from '@shared/models/report.models';
import { ReportComponentConfig } from '@shared/models/report-component.models';
import { ReportComponentsComponent } from '@home/pages/reporting/template/components/report-components.component';
import * as i0 from "@angular/core";
export declare class ReportTemplateHeaderFooterComponent {
    private renderer;
    get currentHeader(): HeaderFooter;
    header: boolean;
    headerFooter: HeaderFooter;
    headerToggleValue: 'header' | 'firstPageHeader';
    format: TbReportFormat;
    background: string;
    width: number;
    scale: number;
    marginTop: number;
    marginLeft: number;
    marginRight: number;
    marginBottom: number;
    componentsChanged: EventEmitter<any>;
    componentEdit: EventEmitter<ReportComponentConfig>;
    componentRemoved: EventEmitter<ReportComponentConfig>;
    currentHeaderChanged: EventEmitter<"header" | "firstPageHeader">;
    enabledHeaderChanged: EventEmitter<any>;
    expandAnimationStart: EventEmitter<any>;
    expandAnimationFinish: EventEmitter<any>;
    reportComponentsComponents: import("@angular/core").Signal<readonly ReportComponentsComponent[]>;
    reportHeaderToolbarButtonsEl: import("@angular/core").Signal<ElementRef<any>>;
    disableHeaderButtonEl: import("@angular/core").Signal<ElementRef<any>>;
    reportHeaderComponentsEl: import("@angular/core").Signal<ElementRef<any>>;
    expanded: boolean;
    private expandAnimation;
    constructor(renderer: Renderer2);
    toggleCurrentHeader(): void;
    disableHeader(): void;
    enableHeader(): void;
    reportComponentsChanged(): void;
    editReportComponent(reportComponent: ReportComponentConfig): void;
    reportComponentRemoved(reportComponent: ReportComponentConfig): void;
    toggleExpanded(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ReportTemplateHeaderFooterComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ReportTemplateHeaderFooterComponent, "tb-report-template-header-footer", never, { "header": { "alias": "header"; "required": false; }; "headerFooter": { "alias": "headerFooter"; "required": false; }; "headerToggleValue": { "alias": "headerToggleValue"; "required": false; }; "format": { "alias": "format"; "required": false; }; "background": { "alias": "background"; "required": false; }; "width": { "alias": "width"; "required": false; }; "scale": { "alias": "scale"; "required": false; }; "marginTop": { "alias": "marginTop"; "required": false; }; "marginLeft": { "alias": "marginLeft"; "required": false; }; "marginRight": { "alias": "marginRight"; "required": false; }; "marginBottom": { "alias": "marginBottom"; "required": false; }; }, { "componentsChanged": "componentsChanged"; "componentEdit": "componentEdit"; "componentRemoved": "componentRemoved"; "currentHeaderChanged": "currentHeaderChanged"; "enabledHeaderChanged": "enabledHeaderChanged"; "expandAnimationStart": "expandAnimationStart"; "expandAnimationFinish": "expandAnimationFinish"; }, never, never, false, never>;
}
