import { OnInit } from '@angular/core';
import { ErrorStateMatcher } from '@angular/material/core';
import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { FormBuilder, FormControl, FormGroup, FormGroupDirective, NgForm } from '@angular/forms';
import { DialogComponent } from '@shared/components/dialog.component';
import { Router } from '@angular/router';
import { EntityType } from '@shared/models/entity-type.models';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import { EntityGroupService } from '@core/http/entity-group.service';
import { BroadcastService } from '@core/services/broadcast.service';
import { AddEntityGroupsToEdgeDialogData } from '@home/dialogs/add-entity-groups-to-edge-dialog.models';
import * as i0 from "@angular/core";
export declare class AddEntityGroupsToEdgeDialogComponent extends DialogComponent<AddEntityGroupsToEdgeDialogComponent> implements OnInit, ErrorStateMatcher {
    protected store: Store<AppState>;
    protected router: Router;
    protected userPermissionsService: UserPermissionsService;
    protected entityGroupService: EntityGroupService;
    protected broadcast: BroadcastService;
    data: AddEntityGroupsToEdgeDialogData;
    private errorStateMatcher;
    dialogRef: MatDialogRef<AddEntityGroupsToEdgeDialogComponent>;
    fb: FormBuilder;
    addEntityGroupToEdgeFormGroup: FormGroup;
    submitted: boolean;
    entityType: typeof EntityType;
    groupType: EntityType;
    edgeId: string;
    customerId: string;
    childGroupId: string;
    addEntityGroupsToEdgeTitle: string;
    confirmSelectTitle: string;
    notFoundText: string;
    requiredText: string;
    edgeEntityGroupIds: string[];
    constructor(store: Store<AppState>, router: Router, userPermissionsService: UserPermissionsService, entityGroupService: EntityGroupService, broadcast: BroadcastService, data: AddEntityGroupsToEdgeDialogData, errorStateMatcher: ErrorStateMatcher, dialogRef: MatDialogRef<AddEntityGroupsToEdgeDialogComponent>, fb: FormBuilder);
    ngOnInit(): void;
    isErrorState(control: FormControl | null, form: FormGroupDirective | NgForm | null): boolean;
    cancel(): void;
    addEntityGroupsToEdge(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AddEntityGroupsToEdgeDialogComponent, [null, null, null, null, null, null, { skipSelf: true; }, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AddEntityGroupsToEdgeDialogComponent, "tb-add-entity-groups-to-edge-dialog", never, {}, {}, never, never>;
}
