import { AfterViewInit, ChangeDetectorRef, DestroyRef, Renderer2, ViewContainerRef } from '@angular/core';
import { ControlValueAccessor, FormBuilder, ValidationErrors, Validator } from '@angular/forms';
import { ArgumentEntityType, CalculatedFieldGeofencing, CalculatedFieldGeofencingValue } from '@shared/models/calculated-field.models';
import { MatButton } from '@angular/material/button';
import { TbPopoverService } from '@shared/components/popover.service';
import { EntityId } from '@shared/models/id/entity-id';
import { EntityType } from '@shared/models/entity-type.models';
import { TbTableDatasource } from '@shared/components/table/table-datasource.abstract';
import { EntityService } from '@core/http/entity.service';
import { MatSort } from '@angular/material/sort';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import * as i0 from "@angular/core";
export declare class CalculatedFieldGeofencingZoneGroupsTableComponent implements ControlValueAccessor, Validator, AfterViewInit {
    private fb;
    private popoverService;
    private viewContainerRef;
    private cd;
    private renderer;
    private entityService;
    private destroyRef;
    private store;
    entityId: EntityId;
    tenantId: string;
    entityName: string;
    ownerId: EntityId;
    readonly: boolean;
    isEditValue: boolean;
    sort: MatSort;
    errorText: string;
    zoneGroupsFormArray: import("@angular/forms").FormArray<import("@angular/forms").FormControl<CalculatedFieldGeofencingValue>>;
    entityNameMap: Map<string, string>;
    sortOrder: {
        direction: string;
        property: string;
    };
    dataSource: CalculatedFieldZoneDatasource;
    disable: boolean;
    readonly GeofencingReportStrategyTranslations: Map<import("@shared/models/calculated-field.models").GeofencingReportStrategy, string>;
    readonly entityTypeTranslations: Map<EntityType | import("@shared/models/entity-type.models").AliasEntityType, import("@shared/models/entity-type.models").EntityTypeTranslation>;
    readonly ArgumentEntityType: typeof ArgumentEntityType;
    readonly maxArgumentsPerCF: number;
    readonly NULL_UUID = "13814000-1dd2-11b2-8080-808080808080";
    private popoverComponent;
    private propagateChange;
    constructor(fb: FormBuilder, popoverService: TbPopoverService, viewContainerRef: ViewContainerRef, cd: ChangeDetectorRef, renderer: Renderer2, entityService: EntityService, destroyRef: DestroyRef, store: Store<AppState>);
    ngAfterViewInit(): void;
    registerOnChange(fn: (zonesObj: Record<string, CalculatedFieldGeofencing>) => void): void;
    registerOnTouched(_: any): void;
    validate(): ValidationErrors | null;
    setDisabledState(isDisabled: boolean): void;
    onDelete($event: Event, zone: CalculatedFieldGeofencingValue): void;
    manageZone($event: Event, matButton: MatButton, zone?: CalculatedFieldGeofencingValue, readonly?: boolean): void;
    private updateDataSource;
    private updateErrorText;
    private getZonesObject;
    writeValue(zonesObj: Record<string, CalculatedFieldGeofencing>): void;
    getEntityDetailsPageURL(id: string, type: EntityType): string;
    private populateZonesFormArray;
    private updateEntityNameMap;
    private fetchEntityNames;
    private getSortValue;
    private sortData;
    static ɵfac: i0.ɵɵFactoryDeclaration<CalculatedFieldGeofencingZoneGroupsTableComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CalculatedFieldGeofencingZoneGroupsTableComponent, "tb-calculated-field-geofencing-zone-groups-table", never, { "entityId": { "alias": "entityId"; "required": true; }; "tenantId": { "alias": "tenantId"; "required": true; }; "entityName": { "alias": "entityName"; "required": true; }; "ownerId": { "alias": "ownerId"; "required": true; }; "readonly": { "alias": "readonly"; "required": false; }; "isEditValue": { "alias": "isEditValue"; "required": false; }; }, {}, never, never, false, never>;
    static ngAcceptInputType_readonly: unknown;
    static ngAcceptInputType_isEditValue: unknown;
}
declare class CalculatedFieldZoneDatasource extends TbTableDatasource<CalculatedFieldGeofencingValue> {
    constructor();
}
export {};
