import { AfterViewInit, EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor, FormBuilder, FormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { TranslateService } from '@ngx-translate/core';
import { EntityType } from '@shared/models/entity-type.models';
import { EntityService } from '@core/http/entity.service';
import { EntityId } from '@shared/models/id/entity-id';
import { EntityGroupInfo } from '@shared/models/entity-group.models';
import * as i0 from "@angular/core";
export declare class EntityGroupSelectComponent implements ControlValueAccessor, OnInit, AfterViewInit {
    private store;
    private entityService;
    translate: TranslateService;
    private fb;
    entityGroupSelectFormGroup: FormGroup;
    modelValue: string;
    allowedGroupTypes: Array<EntityType>;
    excludeGroupTypes: Array<EntityType>;
    defaultGroupType: EntityType;
    excludeGroupIds: Array<string>;
    excludeGroupAll: boolean;
    placeholderText: string;
    notFoundText: string;
    requiredText: string;
    ownerId: EntityId;
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    disabled: boolean;
    currentGroupType: EventEmitter<EntityType>;
    currentGroupInfo: EventEmitter<EntityGroupInfo>;
    displayGroupTypeSelect: boolean;
    entityGroupTypes: Array<EntityType>;
    private propagateChange;
    constructor(store: Store<AppState>, entityService: EntityService, translate: TranslateService, fb: FormBuilder);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: EntityId | null): void;
    entityGroupLoaded(entityGroup: EntityGroupInfo): void;
    getCurrentGroupType(): EntityType;
    updateView(groupId: string | null): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityGroupSelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntityGroupSelectComponent, "tb-entity-group-select", never, { "allowedGroupTypes": "allowedGroupTypes"; "excludeGroupTypes": "excludeGroupTypes"; "defaultGroupType": "defaultGroupType"; "excludeGroupIds": "excludeGroupIds"; "excludeGroupAll": "excludeGroupAll"; "placeholderText": "placeholderText"; "notFoundText": "notFoundText"; "requiredText": "requiredText"; "ownerId": "ownerId"; "required": "required"; "disabled": "disabled"; }, { "currentGroupType": "currentGroupType"; "currentGroupInfo": "currentGroupInfo"; }, never, never>;
}
