import { AfterViewInit, ElementRef, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Observable } from 'rxjs';
import { Store } from '@ngrx/store';
import { AppState } from '@app/core/core.state';
import { EntityId } from '@shared/models/id/entity-id';
import { EntityGroupService } from '@core/http/entity-group.service';
import { EntityInfoData } from '@shared/models/entity.models';
import { MatAutocomplete } from '@angular/material/autocomplete';
import * as i0 from "@angular/core";
export declare class OwnerAutocompleteComponent implements ControlValueAccessor, OnInit, AfterViewInit, OnChanges {
    private store;
    private entityGroupService;
    private fb;
    selectOwnerFormGroup: UntypedFormGroup;
    modelValue: EntityId | null;
    excludeOwnerIds: Array<string>;
    placeholderText: string;
    notFoundText: string;
    requiredText: string;
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    useOwnerInfoValue: boolean;
    defaultOwnerId: EntityId | null;
    disabled: boolean;
    matAutocomplete: MatAutocomplete;
    ownerInput: ElementRef<HTMLInputElement>;
    filteredOwners: Observable<Array<EntityInfoData>>;
    searchText: string;
    private dirty;
    private excludeOwnerIdsChanged;
    private clearButtonClicked;
    private propagateChange;
    constructor(store: Store<AppState>, entityGroupService: EntityGroupService, fb: UntypedFormBuilder);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    setDisabledState(isDisabled: boolean): void;
    selectDefaultOwnerIfNeeded(): void;
    writeValue(value: EntityId | EntityInfoData | null): void;
    onFocus(): void;
    onBlur(): void;
    onPanelClosed(): void;
    reset(): void;
    updateView(value: EntityId | null): void;
    displayOwnerFn(owner?: EntityInfoData): string | undefined;
    fetchOwners(searchText?: string): Observable<Array<EntityInfoData>>;
    clear(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<OwnerAutocompleteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<OwnerAutocompleteComponent, "tb-owner-autocomplete", never, { "excludeOwnerIds": "excludeOwnerIds"; "placeholderText": "placeholderText"; "notFoundText": "notFoundText"; "requiredText": "requiredText"; "required": "required"; "useOwnerInfoValue": "useOwnerInfoValue"; "defaultOwnerId": "defaultOwnerId"; "disabled": "disabled"; }, {}, never, never, false, never>;
}
