import { ChangeDetectorRef, OnInit, TemplateRef } from '@angular/core';
import { WidgetContext } from '@home/models/widget-component.models';
import { ColorProcessor, ComponentStyle } from '@shared/models/widget-settings.models';
import { WidgetComponent } from '@home/components/widget/widget.component';
import { CountCardLayout, CountWidgetSettings } from '@home/components/widget/lib/count/count-widget.models';
import * as i0 from "@angular/core";
export declare class CountWidgetComponent implements OnInit {
    private widgetComponent;
    private cd;
    settings: CountWidgetSettings;
    countCardLayout: typeof CountCardLayout;
    ctx: WidgetContext;
    widgetTitlePanel: TemplateRef<any>;
    alarmElseEntity: boolean;
    layout: CountCardLayout;
    showLabel: boolean;
    label: string;
    labelStyle: ComponentStyle;
    labelColor: ColorProcessor;
    showIcon: boolean;
    icon: string;
    iconStyle: ComponentStyle;
    iconColor: ColorProcessor;
    showIconBackground: boolean;
    iconBackgroundSize: string;
    iconBackgroundStyle: ComponentStyle;
    iconBackgroundColor: ColorProcessor;
    valueText: string;
    valueStyle: ComponentStyle;
    valueColor: ColorProcessor;
    showChevron: boolean;
    chevronStyle: ComponentStyle;
    hasCardClickAction: boolean;
    constructor(widgetComponent: WidgetComponent, cd: ChangeDetectorRef);
    ngOnInit(): void;
    onInit(): void;
    onDataUpdated(): void;
    cardClick($event: Event): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<CountWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CountWidgetComponent, "tb-count-widget", never, { "ctx": "ctx"; "widgetTitlePanel": "widgetTitlePanel"; "alarmElseEntity": "alarmElseEntity"; }, {}, never, never, false, never>;
}
