import * as i0 from "@angular/core";
import * as i1 from "./admin/admin.module";
import * as i2 from "./home-links/home-links.module";
import * as i3 from "./profile/profile.module";
import * as i4 from "@home/pages/security/security.module";
import * as i5 from "./tenant-profile/tenant-profile.module";
import * as i6 from "@modules/home/pages/tenant/tenant.module";
import * as i7 from "./device-profile/device-profile.module";
import * as i8 from "@modules/home/pages/device/device.module";
import * as i9 from "@modules/home/pages/asset/asset.module";
import * as i10 from "@home/pages/edge/edge.module";
import * as i11 from "@modules/home/pages/entity-view/entity-view.module";
import * as i12 from "@modules/home/pages/customer/customer.module";
import * as i13 from "@modules/home/pages/rulechain/rulechain.module";
import * as i14 from "@modules/home/pages/widget/widget-library.module";
import * as i15 from "@modules/home/pages/dashboard/dashboard.module";
import * as i16 from "@modules/home/pages/audit-log/audit-log.module";
import * as i17 from "@home/pages/api-usage/api-usage.module";
import * as i18 from "@modules/home/pages/user/user.module";
import * as i19 from "@home/pages/role/role.module";
import * as i20 from "@home/pages/converter/converter.module";
import * as i21 from "@home/pages/integration/integration.module";
import * as i22 from "@home/pages/group/entity-group.module";
import * as i23 from "@home/pages/iframe/iframe-view.module";
import * as i24 from "@home/pages/scheduler/scheduler.module";
import * as i25 from "@home/pages/ota-update/ota-update.module";
import * as i26 from "@home/pages/solution-template/solution-templates.module";
import * as i27 from "@home/pages/vc/vc.module";
export declare class HomePagesModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<HomePagesModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<HomePagesModule, never, never, [typeof i1.AdminModule, typeof i2.HomeLinksModule, typeof i3.ProfileModule, typeof i4.SecurityModule, typeof i5.TenantProfileModule, typeof i6.TenantModule, typeof i7.DeviceProfileModule, typeof i8.DeviceModule, typeof i9.AssetModule, typeof i10.EdgeModule, typeof i11.EntityViewModule, typeof i12.CustomerModule, typeof i13.RuleChainModule, typeof i14.WidgetLibraryModule, typeof i15.DashboardModule, typeof i16.AuditLogModule, typeof i17.ApiUsageModule, typeof i18.UserModule, typeof i19.RoleModule, typeof i20.ConverterModule, typeof i21.IntegrationModule, typeof i22.EntityGroupModule, typeof i23.IFrameViewModule, typeof i24.SchedulerModule, typeof i25.OtaUpdateModule, typeof i26.SolutionTemplatesModule, typeof i27.VcModule]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<HomePagesModule>;
}
