import { OnInit } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UntypedFormArray, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { HasConfirmForm } from '@core/guards/confirm-on-exit.guard';
import { TranslateService } from '@ngx-translate/core';
import { ActivatedRoute } from '@angular/router';
import { NotificationDeliveryMethod } from '@shared/models/notification.models';
import { NotificationService } from '@core/http/notification.service';
import { DialogService } from '@core/services/dialog.service';
import * as i0 from "@angular/core";
export declare class NotificationSettingsComponent extends PageComponent implements OnInit, HasConfirmForm {
    protected store: Store<AppState>;
    private route;
    private translate;
    private dialogService;
    private notificationService;
    private fb;
    notificationSettings: UntypedFormGroup;
    notificationDeliveryMethods: NotificationDeliveryMethod[];
    notificationDeliveryMethodInfoMap: Map<NotificationDeliveryMethod, import("@shared/models/notification.models").NotificationDeliveryMethodInfo>;
    private deliveryMethods;
    constructor(store: Store<AppState>, route: ActivatedRoute, translate: TranslateService, dialogService: DialogService, notificationService: NotificationService, fb: UntypedFormBuilder);
    ngOnInit(): void;
    private buildNotificationSettingsForm;
    private patchNotificationSettings;
    private prepareNotificationSettings;
    resetSettings(): void;
    getChecked: (method?: NotificationDeliveryMethod) => boolean;
    getSomeChecked: () => any;
    getIndeterminate: (deliveryMethod?: NotificationDeliveryMethod) => boolean;
    changeInstanceTypeCheckBox: (value: boolean, deliveryMethod?: NotificationDeliveryMethod) => void;
    get notificationSettingsFormArray(): UntypedFormArray;
    save(): void;
    confirmForm(): UntypedFormGroup;
    static ɵfac: i0.ɵɵFactoryDeclaration<NotificationSettingsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NotificationSettingsComponent, "tb-notification-settings", never, {}, {}, never, never, false, never>;
}
