import { EventEmitter, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { MatDialog } from '@angular/material/dialog';
import { Dashboard, WidgetLayout } from '@shared/models/dashboard.models';
import { IAliasController, IStateController } from '@core/api/widget-api.models';
import { Widget, WidgetConfigMode } from '@shared/models/widget.models';
import { WidgetComponentService } from '@home/components/widget/widget-component.service';
import { WidgetConfigComponentData } from '../../models/widget-component.models';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import * as i0 from "@angular/core";
export declare class EditWidgetComponent extends PageComponent implements OnInit, OnChanges {
    protected store: Store<AppState>;
    private dialog;
    private fb;
    private widgetComponentService;
    dashboard: Dashboard;
    aliasController: IAliasController;
    stateController: IStateController;
    widgetEditMode: boolean;
    widget: Widget;
    widgetLayout: WidgetLayout;
    applyWidgetConfig: EventEmitter<void>;
    revertWidgetConfig: EventEmitter<void>;
    widgetFormGroup: UntypedFormGroup;
    widgetConfig: WidgetConfigComponentData;
    previewMode: boolean;
    hasBasicMode: boolean;
    get widgetConfigMode(): WidgetConfigMode;
    set widgetConfigMode(widgetConfigMode: WidgetConfigMode);
    private currentWidgetConfigChanged;
    constructor(store: Store<AppState>, dialog: MatDialog, fb: UntypedFormBuilder, widgetComponentService: WidgetComponentService);
    ngOnInit(): void;
    ngOnChanges(changes: SimpleChanges): void;
    onApplyWidgetConfig(): void;
    onRevertWidgetConfig(): void;
    private loadWidgetConfig;
    static ɵfac: i0.ɵɵFactoryDeclaration<EditWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EditWidgetComponent, "tb-edit-widget", never, { "dashboard": "dashboard"; "aliasController": "aliasController"; "stateController": "stateController"; "widgetEditMode": "widgetEditMode"; "widget": "widget"; "widgetLayout": "widgetLayout"; }, { "applyWidgetConfig": "applyWidgetConfig"; "revertWidgetConfig": "revertWidgetConfig"; }, never, never, false, never>;
}
