import { EventEmitter, OnInit } from '@angular/core';
import { ControlValueAccessor, FormGroupDirective, NgForm, UntypedFormBuilder, UntypedFormControl, UntypedFormGroup } from '@angular/forms';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { DocumentationLink } from '@shared/models/user-settings.models';
import { ErrorStateMatcher } from '@angular/material/core';
import * as i0 from "@angular/core";
export declare class DocLinkComponent extends PageComponent implements OnInit, ControlValueAccessor, ErrorStateMatcher {
    protected store: Store<AppState>;
    private fb;
    private errorStateMatcher;
    disabled: boolean;
    addOnly: boolean;
    disableEdit: boolean;
    docLinkAdded: EventEmitter<DocumentationLink>;
    docLinkAddCanceled: EventEmitter<void>;
    docLinkUpdated: EventEmitter<DocumentationLink>;
    docLinkDeleted: EventEmitter<void>;
    editModeChanged: EventEmitter<boolean>;
    editMode: boolean;
    addMode: boolean;
    docLink: DocumentationLink;
    private propagateChange;
    editDocLinkFormGroup: UntypedFormGroup;
    private submitted;
    constructor(store: Store<AppState>, fb: UntypedFormBuilder, errorStateMatcher: ErrorStateMatcher);
    ngOnInit(): void;
    isErrorState(control: UntypedFormControl | null, form: FormGroupDirective | NgForm | null): boolean;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: DocumentationLink): void;
    switchToEditMode(): void;
    apply(): void;
    cancelEdit(): void;
    add(): void;
    cancelAdd(): void;
    delete(): void;
    isEditing(): boolean;
    private updateModel;
    static ɵfac: i0.ɵɵFactoryDeclaration<DocLinkComponent, [null, null, { skipSelf: true; }]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DocLinkComponent, "tb-doc-link", never, { "disabled": { "alias": "disabled"; "required": false; }; "addOnly": { "alias": "addOnly"; "required": false; }; "disableEdit": { "alias": "disableEdit"; "required": false; }; }, { "docLinkAdded": "docLinkAdded"; "docLinkAddCanceled": "docLinkAddCanceled"; "docLinkUpdated": "docLinkUpdated"; "docLinkDeleted": "docLinkDeleted"; "editModeChanged": "editModeChanged"; }, never, never, false, never>;
}
