import { FunctionArg, FunctionArgType, TbEditorCompletions } from '@shared/models/ace/completion.models';
export declare const entityIdHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/id/entity-id.ts#L20\">EntityId</a>";
export declare const baseDataHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/base-data.ts#L22\">Base data</a>";
export declare const alarmDataHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/query/query.models.ts#L573\">Alarm data</a>";
export declare const alarmDataQueryHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/query/query.models.ts#L558\">Alarm data query</a>";
export declare const attributeScopeHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts#L37\">Attribute scope</a>";
export declare const entityTypeHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/entity-type.models.ts#L36\">EntityType</a>";
export declare const pageDataHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/page/page-data.ts#L17\">PageData</a>";
export declare const deviceInfoHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/device.models.ts#L33\">DeviceInfo</a>";
export declare const assetInfoHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/asset.models.ts#L32\">AssetInfo</a>";
export declare const entityViewInfoHref = "<a href = \"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/entity-view.models.ts#L47\">EntityViewInfo</a>";
export declare const entityRelationsQueryHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/relation.models.ts#L69\">EntityRelationsQuery</a>";
export declare const entityRelationInfoHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/relation.models.ts#L87\">EntityRelationInfo</a>";
export declare const dashboardInfoHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/dashboard.models.ts#L25\">DashboardInfo</a>";
export declare const deviceHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/device.models.ts#L24\">Device</a>";
export declare const assetHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/asset.models.ts#L23\">Asset</a>";
export declare const entityViewHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/entity-view.models.ts#L35\">entityView</a>";
export declare const entityRelationHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/relation.models.ts#L79\">Entity relation</a>";
export declare const dashboardHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/dashboard.models.ts#L102\">Dashboard</a>";
export declare const customerHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/customer.model.ts#L21\">Customer</a>";
export declare const attributeDataHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts#L76\">Attribute Data</a>";
export declare const timeseriesDataHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/627c0577b08452308f925cecb3860e35292c649e/ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts#L91\">Timeseries Data</a>";
export declare const aggregationTypeHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/a8ea887eacf7729e603ace13ce2d7d89dae82931/ui-ngx/src/app/shared/models/time/time.models.ts#L54\">Aggregation Type</a>";
export declare const dataSortOrderHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/627c0577b08452308f925cecb3860e35292c649e/ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts#L95\">Data Sort Order</a>";
export declare const userHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/user.model.ts#L23\">User</a>";
export declare const entityDataHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/query/query.models.ts#L567\">Entity data</a>";
export declare const entityDataQueryHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/query/query.models.ts#L555\">Entity Data Query</a>";
export declare const deviceCredentialsHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/13e6b10b7ab830e64d31b99614a9d95a1a25928a/ui-ngx/src/app/shared/models/device.models.ts#L50\">DeviceCredentials</a>";
export declare const entityFilterHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/query/query.models.ts#L487\">Entity filter</a>";
export declare const entityInfoHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/entity.models.ts#L20\">Entity info</a>";
export declare const aliasEntityTypeHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/entity-type.models.ts#L51\">Alias Entity Type</a>";
export declare const aliasFilterTypeHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/entity-type.models.ts#L51\">Alias filter type</a>";
export declare const entityAliasHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/alias.models.ts#L150\">Entity alias</a>";
export declare const dataKeyTypeHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/telemetry/telemetry.models.ts#L27\">Data key type</a>";
export declare const subscriptionInfoHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/api/widget-api.models.ts#L155\">Subscription info</a>";
export declare const dataSourceHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/widget.models.ts#L257\">Datasource</a>";
export declare const stateParamsHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/api/widget-api.models.ts#L129\">State params</a>";
export declare const aliasInfoHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/core/api/widget-api.models.ts#L88\">Alias info</a>";
export declare const entityAliasFilterHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/alias.models.ts#L134\">Entity alias filter</a>";
export declare const entityAliasFilterResultHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/alias.models.ts#L158\">Entity alias filter result</a>";
export declare const importEntityDataHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/entity.models.ts#L28\">Import entity data</a>";
export declare const importEntitiesResultInfoHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/shared/models/entity.models.ts#L42\">Import entities result info</a>";
export declare const customDialogComponentHref = "<a href=\"https://github.com/thingsboard/thingsboard/blob/master/ui-ngx/src/app/modules/home/components/widget/dialog/custom-dialog.component.ts#L48\">CustomDialogComponent</a>";
export declare const pageLinkArg: FunctionArg;
export declare const requestConfigArg: FunctionArg;
export declare function observableReturnType(objectType: string): FunctionArgType;
export declare function observableReturnTypeVariable(variableType: string): FunctionArgType;
export declare function observableVoid(): FunctionArgType;
export declare function observableArrayReturnType(objectType: string): FunctionArgType;
export declare function observableBaseDataReturnType(): FunctionArgType;
export declare function observableArrayBaseDataReturnType(): FunctionArgType;
export declare function observablePageDataReturnType(objectType: string): FunctionArgType;
export declare const serviceCompletions: TbEditorCompletions;
