import { Injector } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { BasicWidgetConfigComponent } from '@home/components/widget/config/widget-config.component.models';
import { WidgetConfigComponentData } from '@home/models/widget-component.models';
import { WidgetConfigComponent } from '@home/components/widget/widget-config.component';
import * as i0 from "@angular/core";
export declare class BatteryLevelBasicConfigComponent extends BasicWidgetConfigComponent {
    protected store: Store<AppState>;
    protected widgetConfigComponent: WidgetConfigComponent;
    private $injector;
    private fb;
    get displayTimewindowConfig(): boolean;
    onlyHistoryTimewindow(): boolean;
    batteryLevelLayouts: import("@home/components/widget/lib/indicator/battery-level-widget.models").BatteryLevelLayout[];
    batteryLevelLayoutTranslationMap: Map<import("@home/components/widget/lib/indicator/battery-level-widget.models").BatteryLevelLayout, string>;
    batteryLevelLayoutImageMap: Map<import("@home/components/widget/lib/indicator/battery-level-widget.models").BatteryLevelLayout, string>;
    batteryLevelWidgetConfigForm: UntypedFormGroup;
    valuePreviewFn: any;
    constructor(store: Store<AppState>, widgetConfigComponent: WidgetConfigComponent, $injector: Injector, fb: UntypedFormBuilder);
    protected configForm(): UntypedFormGroup;
    protected setupDefaults(configData: WidgetConfigComponentData): void;
    protected onConfigSet(configData: WidgetConfigComponentData): void;
    protected prepareOutputConfig(config: any): WidgetConfigComponentData;
    protected validatorTriggers(): string[];
    protected updateValidators(emitEvent: boolean, trigger?: string): void;
    private getCardButtons;
    private setCardButtons;
    private _valuePreviewFn;
    static ɵfac: i0.ɵɵFactoryDeclaration<BatteryLevelBasicConfigComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<BatteryLevelBasicConfigComponent, "tb-battery-level-basic-config", never, {}, {}, never, never, false, never>;
}
