import { AfterViewInit, ChangeDetectorRef, ElementRef, OnDestroy, OnInit, Renderer2, TemplateRef } from '@angular/core';
import { WidgetContext } from '@home/models/widget-component.models';
import { ColorProcessor, ComponentStyle } from '@shared/models/widget-settings.models';
import { WidgetComponent } from '@home/components/widget/widget.component';
import { ValueChartCardLayout, ValueChartCardWidgetSettings } from '@home/components/widget/lib/cards/value-chart-card-widget.models';
import { Observable } from 'rxjs';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import * as i0 from "@angular/core";
export declare class ValueChartCardWidgetComponent implements OnInit, AfterViewInit, OnDestroy {
    private imagePipe;
    private sanitizer;
    private renderer;
    private widgetComponent;
    private cd;
    chartElement: ElementRef;
    valueChartCardContent: ElementRef<HTMLElement>;
    valueChartCardValue: ElementRef<HTMLElement>;
    settings: ValueChartCardWidgetSettings;
    ctx: WidgetContext;
    widgetTitlePanel: TemplateRef<any>;
    layout: ValueChartCardLayout;
    autoScale: boolean;
    showValue: boolean;
    valueText: string;
    valueStyle: ComponentStyle;
    valueColor: ColorProcessor;
    backgroundStyle$: Observable<ComponentStyle>;
    overlayStyle: ComponentStyle;
    padding: string;
    private lineChart;
    private lineChartDataKey;
    private valueKey;
    private contentResize$;
    private decimals;
    private units;
    private valueFontSize;
    constructor(imagePipe: ImagePipe, sanitizer: DomSanitizer, renderer: Renderer2, widgetComponent: WidgetComponent, cd: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onInit(): void;
    onDataUpdated(): void;
    onLatestDataUpdated(): void;
    onEditModeChanged(): void;
    onDestroy(): void;
    private onResize;
    private setValueFontSize;
    static ɵfac: i0.ɵɵFactoryDeclaration<ValueChartCardWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ValueChartCardWidgetComponent, "tb-value-chart-card-widget", never, { "ctx": { "alias": "ctx"; "required": false; }; "widgetTitlePanel": { "alias": "widgetTitlePanel"; "required": false; }; }, {}, never, never, false, never>;
}
