import { OnChanges, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, FormBuilder, ValidationErrors, Validator } from '@angular/forms';
import { CalculatedFieldScriptConfiguration, CalculatedFieldSimpleConfiguration, CalculatedFieldSimpleOutput, OutputType } from '@shared/models/calculated-field.models';
import { EntityId } from '@shared/models/id/entity-id';
import { Observable } from 'rxjs';
import { ScriptLanguage } from '@shared/models/rule-node.models';
import * as i0 from "@angular/core";
type SimpeConfiguration = CalculatedFieldSimpleConfiguration | CalculatedFieldScriptConfiguration;
export declare class SimpleConfigurationComponent implements ControlValueAccessor, Validator, OnChanges {
    private fb;
    isScript: boolean;
    entityId: EntityId;
    tenantId: string;
    entityName: string;
    ownerId: EntityId;
    testScript: () => Observable<string>;
    isEditValue: boolean;
    readonly: boolean;
    simpleConfiguration: import("@angular/forms").FormGroup<{
        arguments: import("@angular/forms").FormControl<{}>;
        expressionSIMPLE: import("@angular/forms").FormControl<string>;
        expressionSCRIPT: import("@angular/forms").FormControl<string>;
        output: import("@angular/forms").FormControl<CalculatedFieldSimpleOutput>;
        useLatestTs: import("@angular/forms").FormControl<boolean>;
    }>;
    readonly ScriptLanguage: typeof ScriptLanguage;
    readonly OutputType: typeof OutputType;
    functionArgs$: Observable<string[]>;
    argumentsEditorCompleter$: Observable<import("../../../../../../shared/models/ace/completion.models").TbEditorCompleter>;
    argumentsHighlightRules$: Observable<import("../../../../../../shared/models/ace/ace.models").AceHighlightRules>;
    disabled: boolean;
    private propagateChange;
    constructor(fb: FormBuilder);
    ngOnChanges(changes: SimpleChanges): void;
    validate(): ValidationErrors | null;
    writeValue(value: SimpeConfiguration): void;
    registerOnChange(fn: (config: SimpeConfiguration) => void): void;
    registerOnTouched(_: any): void;
    setDisabledState(isDisabled: boolean): void;
    onTestScript(): void;
    private updatedModel;
    private updatedFormWithScript;
    private toggleScopeByOutputType;
    static ɵfac: i0.ɵɵFactoryDeclaration<SimpleConfigurationComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SimpleConfigurationComponent, "tb-simple-configuration", never, { "isScript": { "alias": "isScript"; "required": false; }; "entityId": { "alias": "entityId"; "required": true; }; "tenantId": { "alias": "tenantId"; "required": true; }; "entityName": { "alias": "entityName"; "required": true; }; "ownerId": { "alias": "ownerId"; "required": true; }; "testScript": { "alias": "testScript"; "required": true; }; "isEditValue": { "alias": "isEditValue"; "required": false; }; "readonly": { "alias": "readonly"; "required": false; }; }, {}, never, never, false, never>;
    static ngAcceptInputType_isEditValue: unknown;
    static ngAcceptInputType_readonly: unknown;
}
export {};
