import { ChangeDetectorRef, EventEmitter, OnInit } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { TbPopoverComponent } from '@shared/components/popover.component';
import { FormBuilder } from '@angular/forms';
import { EntityDebugSettings } from '@shared/models/entity.models';
import { AdditionalDebugActionConfig } from '@home/components/entity/debug/entity-debug-settings.model';
import { EntityType } from '@shared/models/entity-type.models';
import * as i0 from "@angular/core";
export declare class EntityDebugSettingsPanelComponent extends PageComponent implements OnInit {
    private fb;
    private cd;
    private popover;
    failuresEnabled: boolean;
    allEnabled: boolean;
    entityLabel: string;
    entityType: EntityType;
    allEnabledUntil: number;
    maxDebugModeDuration: number;
    additionalActionConfig: AdditionalDebugActionConfig;
    onFailuresControl: import("@angular/forms").FormControl<boolean>;
    debugAllControl: import("@angular/forms").FormControl<boolean>;
    maxMessagesCount: string;
    maxTimeFrameDuration: number;
    initialAllEnabled: boolean;
    isDebugAllActive$: import("rxjs").Observable<boolean>;
    onSettingsApplied: EventEmitter<EntityDebugSettings>;
    constructor(fb: FormBuilder, cd: ChangeDetectorRef, popover: TbPopoverComponent<EntityDebugSettingsPanelComponent>);
    ngOnInit(): void;
    onCancel(): void;
    onApply(): void;
    onReset(): void;
    private getByEntityTypeDebugLimit;
    static ɵfac: i0.ɵɵFactoryDeclaration<EntityDebugSettingsPanelComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EntityDebugSettingsPanelComponent, "tb-entity-debug-settings-panel", never, { "failuresEnabled": { "alias": "failuresEnabled"; "required": false; }; "allEnabled": { "alias": "allEnabled"; "required": false; }; "entityLabel": { "alias": "entityLabel"; "required": false; }; "entityType": { "alias": "entityType"; "required": false; }; "allEnabledUntil": { "alias": "allEnabledUntil"; "required": false; }; "maxDebugModeDuration": { "alias": "maxDebugModeDuration"; "required": false; }; "additionalActionConfig": { "alias": "additionalActionConfig"; "required": false; }; }, {}, never, never, true, never>;
    static ngAcceptInputType_failuresEnabled: unknown;
    static ngAcceptInputType_allEnabled: unknown;
}
