import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { RuleChain, RuleChainParams } from '@shared/models/rule-chain.models';
import { RuleChainService } from '@core/http/rule-chain.service';
import { DialogService } from '@core/services/dialog.service';
import { MatDialog } from '@angular/material/dialog';
import { ImportExportService } from '@home/components/import-export/import-export.service';
import { ItemBufferService } from '@core/services/item-buffer.service';
import { EdgeService } from '@core/http/edge.service';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { ActivatedRouteSnapshot, Router } from '@angular/router';
import { UtilsService } from '@core/services/utils.service';
import { UserPermissionsService } from '@core/http/user-permissions.service';
export declare class RuleChainsTableConfig extends EntityTableConfig<RuleChain> {
    private ruleChainService;
    private dialogService;
    private dialog;
    private importExport;
    private itembuffer;
    private edgeService;
    private translate;
    private datePipe;
    private router;
    private utils;
    private userPermissionsService;
    private params;
    constructor(ruleChainService: RuleChainService, dialogService: DialogService, dialog: MatDialog, importExport: ImportExportService, itembuffer: ItemBufferService, edgeService: EdgeService, translate: TranslateService, datePipe: DatePipe, router: Router, utils: UtilsService, userPermissionsService: UserPermissionsService, params: ActivatedRouteSnapshot | RuleChainParams);
    private setComponentsData;
    private configureEntityTableColumns;
    private configureGroupActions;
    private unassignRuleChainsFromEdge;
    private configureAddActions;
    private importRuleChain;
    private checkMissingToRelatedRuleChains;
    private assignRuleChainsToEdge;
    private configureCellActions;
    private configureEntityFunctions;
    private fetchRuleChains;
    private fetchEdgeRuleChains;
    private saveRuleChain;
    private onRuleChainAction;
    private openRuleChain;
    private exportRuleChain;
    private setRootRuleChain;
    private setEdgeRootRuleChain;
    private setEdgeTemplateRootRuleChain;
    private unassignFromEdge;
    private setAutoAssignToEdgeRuleChain;
    private unsetAutoAssignToEdgeRuleChain;
    private isNonRootRuleChain;
    private isAutoAssignToEdgeRuleChain;
    private isNotAutoAssignToEdgeRuleChain;
    private configureRuleChainScope;
    private configureTableTitle;
}
