import { Injector } from '@angular/core';
import { Datasource, WidgetSettings, WidgetSettingsComponent } from '@shared/models/widget.models';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { TimeSeriesChartType, TimeSeriesChartYAxisId } from '@home/components/widget/lib/chart/time-series-chart.models';
import { WidgetConfigComponentData } from '@home/models/widget-component.models';
import { WidgetService } from '@core/http/widget.service';
import { TimeSeriesChartTooltipTrigger } from '@home/components/widget/lib/chart/time-series-chart-tooltip.models';
import * as i0 from "@angular/core";
export declare class TimeSeriesChartWidgetSettingsComponent extends WidgetSettingsComponent {
    protected store: Store<AppState>;
    private $injector;
    private widgetService;
    private fb;
    get datasource(): Datasource;
    get yAxisIds(): TimeSeriesChartYAxisId[];
    TimeSeriesChartType: typeof TimeSeriesChartType;
    EChartsTooltipTrigger: typeof TimeSeriesChartTooltipTrigger;
    legendPositions: import("@shared/models/widget.models").LegendPosition[];
    legendPositionTranslationMap: Map<import("@shared/models/widget.models").LegendPosition, string>;
    timeSeriesChartWidgetSettingsForm: UntypedFormGroup;
    tooltipValuePreviewFn: any;
    tooltipDatePreviewFn: any;
    chartType: TimeSeriesChartType;
    functionScopeVariables: string[];
    constructor(store: Store<AppState>, $injector: Injector, widgetService: WidgetService, fb: UntypedFormBuilder);
    yAxisRemoved(yAxisId: TimeSeriesChartYAxisId): void;
    protected settingsForm(): UntypedFormGroup;
    protected onWidgetConfigSet(widgetConfig: WidgetConfigComponentData): void;
    protected defaultSettings(): WidgetSettings;
    protected onSettingsSet(settings: WidgetSettings): void;
    protected validatorTriggers(): string[];
    protected updateValidators(emitEvent: boolean): void;
    private removeYaxisId;
    private _tooltipValuePreviewFn;
    private _tooltipDatePreviewFn;
    static ɵfac: i0.ɵɵFactoryDeclaration<TimeSeriesChartWidgetSettingsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TimeSeriesChartWidgetSettingsComponent, "tb-time-series-chart-widget-settings", never, {}, {}, never, never, false, never>;
}
