import { InjectionToken, OnDestroy, OnInit, ViewContainerRef } from '@angular/core';
import { AggregationType, HistoryWindowType, RealtimeWindowType, Timewindow, TimewindowType } from '@shared/models/time/time.models';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { TimeService } from '@core/services/time.service';
import { OverlayRef } from '@angular/cdk/overlay';
import { ToggleHeaderOption } from '@shared/components/toggle-header.component';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import * as i0 from "@angular/core";
export interface TimewindowPanelData {
    historyOnly: boolean;
    forAllTimeEnabled: boolean;
    quickIntervalOnly: boolean;
    timewindow: Timewindow;
    aggregation: boolean;
    timezone: boolean;
    isEdit: boolean;
}
export declare const TIMEWINDOW_PANEL_DATA: InjectionToken<any>;
export declare class TimewindowPanelComponent extends PageComponent implements OnInit, OnDestroy {
    data: TimewindowPanelData;
    overlayRef: OverlayRef;
    protected store: Store<AppState>;
    fb: UntypedFormBuilder;
    private timeService;
    private translate;
    viewContainerRef: ViewContainerRef;
    private dialog;
    historyOnly: boolean;
    forAllTimeEnabled: boolean;
    quickIntervalOnly: boolean;
    aggregation: boolean;
    timezone: boolean;
    isEdit: boolean;
    timewindow: Timewindow;
    timewindowForm: UntypedFormGroup;
    historyTypes: typeof HistoryWindowType;
    realtimeTypes: typeof RealtimeWindowType;
    timewindowTypes: typeof TimewindowType;
    aggregationTypes: typeof AggregationType;
    aggregations: string[];
    aggregationTypesTranslations: Map<AggregationType, string>;
    result: Timewindow;
    timewindowTypeOptions: ToggleHeaderOption[];
    realtimeTimewindowOptions: ToggleHeaderOption[];
    historyTimewindowOptions: ToggleHeaderOption[];
    realtimeTypeSelectionAvailable: boolean;
    realtimeIntervalSelectionAvailable: boolean;
    historyTypeSelectionAvailable: boolean;
    historyIntervalSelectionAvailable: boolean;
    aggregationOptionsAvailable: boolean;
    private destroy$;
    constructor(data: TimewindowPanelData, overlayRef: OverlayRef, store: Store<AppState>, fb: UntypedFormBuilder, timeService: TimeService, translate: TranslateService, viewContainerRef: ViewContainerRef, dialog: MatDialog);
    ngOnInit(): void;
    ngOnDestroy(): void;
    private updateValidators;
    private onTimewindowTypeChange;
    update(): void;
    private prepareTimewindowConfig;
    private updateTimewindowForm;
    cancel(): void;
    minRealtimeAggInterval(): number;
    maxRealtimeAggInterval(): number;
    currentRealtimeTimewindow(): number;
    minHistoryAggInterval(): number;
    maxHistoryAggInterval(): number;
    currentHistoryTimewindow(): any;
    openTimewindowConfig(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<TimewindowPanelComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TimewindowPanelComponent, "tb-timewindow-panel", never, {}, {}, never, never, false, never>;
}
