import { ChangeDetectorRef, OnDestroy, OnInit, ViewContainerRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { MillisecondsToTimeStringPipe } from '@shared/pipe/milliseconds-to-time-string.pipe';
import { Timewindow } from '@shared/models/time/time.models';
import { DatePipe } from '@angular/common';
import { CdkOverlayOrigin, Overlay } from '@angular/cdk/overlay';
import { BreakpointObserver } from '@angular/cdk/layout';
import { TimeService } from '@core/services/time.service';
import { TooltipPosition } from '@angular/material/tooltip';
import * as i0 from "@angular/core";
export declare class TimewindowComponent implements OnInit, OnDestroy, ControlValueAccessor {
    private translate;
    private timeService;
    private millisecondsToTimeStringPipe;
    private datePipe;
    private overlay;
    private cd;
    viewContainerRef: ViewContainerRef;
    breakpointObserver: BreakpointObserver;
    private document;
    private window;
    historyOnlyValue: boolean;
    set historyOnly(val: boolean);
    get historyOnly(): boolean;
    alwaysDisplayTypePrefixValue: boolean;
    set alwaysDisplayTypePrefix(val: boolean);
    get alwaysDisplayTypePrefix(): boolean;
    quickIntervalOnlyValue: boolean;
    set quickIntervalOnly(val: boolean);
    get quickIntervalOnly(): boolean;
    aggregationValue: boolean;
    set aggregation(val: boolean);
    get aggregation(): boolean;
    timezoneValue: boolean;
    set timezone(val: boolean);
    get timezone(): boolean;
    isToolbarValue: boolean;
    set isToolbar(val: boolean);
    get isToolbar(): boolean;
    asButtonValue: boolean;
    set asButton(val: boolean);
    get asButton(): boolean;
    isEditValue: boolean;
    set isEdit(val: boolean);
    get isEdit(): boolean;
    direction: 'left' | 'right';
    tooltipPosition: TooltipPosition;
    disabled: boolean;
    timewindowPanelOrigin: CdkOverlayOrigin;
    innerValue: Timewindow;
    timewindowDisabled: boolean;
    private propagateChange;
    constructor(translate: TranslateService, timeService: TimeService, millisecondsToTimeStringPipe: MillisecondsToTimeStringPipe, datePipe: DatePipe, overlay: Overlay, cd: ChangeDetectorRef, viewContainerRef: ViewContainerRef, breakpointObserver: BreakpointObserver, document: Document, window: Window);
    ngOnInit(): void;
    ngOnDestroy(): void;
    openEditMode(): void;
    private _createTimewindowPanelInjector;
    private onHistoryOnlyChanged;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(obj: Timewindow): void;
    notifyChanged(): void;
    updateDisplayValue(): void;
    hideLabel(): boolean;
    private isTimewindowDisabled;
    static ɵfac: i0.ɵɵFactoryDeclaration<TimewindowComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TimewindowComponent, "tb-timewindow", never, { "historyOnly": "historyOnly"; "alwaysDisplayTypePrefix": "alwaysDisplayTypePrefix"; "quickIntervalOnly": "quickIntervalOnly"; "aggregation": "aggregation"; "timezone": "timezone"; "isToolbar": "isToolbar"; "asButton": "asButton"; "isEdit": "isEdit"; "direction": "direction"; "tooltipPosition": "tooltipPosition"; "disabled": "disabled"; }, {}, never, never>;
}
