import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { DebugEventType, Event, EventBody, EventType } from '@shared/models/event.models';
import { TimePageLink } from '@shared/models/page/page-link';
import { TranslateService } from '@ngx-translate/core';
import { DatePipe } from '@angular/common';
import { MatDialog } from '@angular/material/dialog';
import { EntityId } from '@shared/models/id/entity-id';
import { EventService } from '@app/core/http/event.service';
import { Observable } from 'rxjs';
import { PageData } from '@shared/models/page/page-data';
import { DialogService } from '@core/services/dialog.service';
import { ContentType } from '@shared/models/constants';
import { Overlay } from '@angular/cdk/overlay';
import { ChangeDetectorRef, EventEmitter, ViewContainerRef } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
export declare class EventTableConfig extends EntityTableConfig<Event, TimePageLink> {
    private eventService;
    private dialogService;
    private translate;
    private datePipe;
    private dialog;
    entityId: EntityId;
    tenantId: string;
    private defaultEventType;
    private disabledEventTypes;
    private debugEventTypes;
    private overlay;
    private viewContainerRef;
    private cd;
    private store;
    private isReadOnly;
    testButtonLabel?: string;
    private debugEventSelected?;
    hideClearEventAction: boolean;
    disableDebugEventAction: boolean;
    eventTypeValue: EventType | DebugEventType;
    private filterParams;
    private filterColumns;
    private readonly maxDebugModeDurationMinutes;
    set eventType(eventType: EventType | DebugEventType);
    get eventType(): EventType | DebugEventType;
    eventTypes: Array<EventType | DebugEventType>;
    constructor(eventService: EventService, dialogService: DialogService, translate: TranslateService, datePipe: DatePipe, dialog: MatDialog, entityId: EntityId, tenantId: string, defaultEventType: EventType | DebugEventType, disabledEventTypes: Array<EventType | DebugEventType>, debugEventTypes: Array<DebugEventType>, overlay: Overlay, viewContainerRef: ViewContainerRef, cd: ChangeDetectorRef, store: Store<AppState>, isReadOnly: boolean, testButtonLabel?: string, debugEventSelected?: EventEmitter<EventBody>, hideClearEventAction?: boolean, disableDebugEventAction?: boolean);
    clearEvents($event: any): void;
    fetchEvents(pageLink: TimePageLink): Observable<PageData<Event>>;
    updateColumns(updateTableColumns?: boolean): void;
    updateCellAction(): void;
    showContent($event: MouseEvent, content: string, title: string, contentType?: ContentType, sortKeys?: boolean): void;
    private updateFilterColumns;
    private clearFiter;
    private editEventFilter;
}
