import { ChangeDetectorRef, ElementRef, OnDestroy, OnInit } from '@angular/core';
import { WidgetContext } from '@home/models/widget-component.models';
import { BasicActionWidgetComponent } from '@home/components/widget/lib/action/action-widget.models';
import * as i0 from "@angular/core";
export declare class KnobComponent extends BasicActionWidgetComponent implements OnInit, OnDestroy {
    protected cd: ChangeDetectorRef;
    knobRef: ElementRef<HTMLElement>;
    knobContainerRef: ElementRef<HTMLElement>;
    knobTopPointerContainerRef: ElementRef<HTMLElement>;
    knobTopPointerRef: ElementRef<HTMLElement>;
    knobValueContainerRef: ElementRef<HTMLElement>;
    knobValueRef: ElementRef<HTMLElement>;
    knobTitleContainerRef: ElementRef<HTMLElement>;
    knobTitleRef: ElementRef<HTMLElement>;
    knobMinmaxContainerRef: ElementRef<HTMLElement>;
    textMeasureRef: ElementRef<HTMLElement>;
    canvasBarElementRef: ElementRef<HTMLElement>;
    ctx: WidgetContext;
    value: string;
    title: string;
    minValue: number;
    maxValue: number;
    newValue: number;
    private decimals;
    private startDeg;
    private currentDeg;
    private rotation;
    private lastDeg;
    private moving;
    private minDeg;
    private maxDeg;
    private executingUpdateValue;
    private scheduledValue;
    private rpcValue;
    private knob;
    private knobContainer;
    private knobTopPointerContainer;
    private knobTopPointer;
    private knobValueContainer;
    private knobValue;
    private knobTitleContainer;
    private knobTitle;
    private knobMinmaxContainer;
    private minmaxLabel;
    private textMeasure;
    private canvasBarElement;
    private canvasBar;
    private knobResize$;
    private valueSetter;
    private valueFormat;
    constructor(cd: ChangeDetectorRef);
    ngOnInit(): void;
    ngOnDestroy(): void;
    private init;
    private degreeToRatio;
    private ratioToDegree;
    private turn;
    private resize;
    private checkValueSize;
    private setFontSize;
    private measureTextWidth;
    private setValue;
    private updateColor;
    private onValue;
    private formatValue;
    private rpcUpdateValue;
    static ɵfac: i0.ɵɵFactoryDeclaration<KnobComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<KnobComponent, "tb-knob", never, { "ctx": { "alias": "ctx"; "required": false; }; }, {}, never, never, false, never>;
}
