import { AfterViewInit, ChangeDetectorRef, ElementRef, OnDestroy, OnInit, Renderer2 } from '@angular/core';
import { BasicActionWidgetComponent } from '@home/components/widget/lib/action/action-widget.models';
import { SingleSwitchLayout, SingleSwitchWidgetSettings } from '@home/components/widget/lib/rpc/single-switch-widget.models';
import { ComponentStyle } from '@shared/models/widget-settings.models';
import { Observable } from 'rxjs';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import { UtilsService } from '@core/services/utils.service';
import * as i0 from "@angular/core";
export declare class SingleSwitchWidgetComponent extends BasicActionWidgetComponent implements OnInit, AfterViewInit, OnDestroy {
    protected imagePipe: ImagePipe;
    protected sanitizer: DomSanitizer;
    private renderer;
    private utils;
    protected cd: ChangeDetectorRef;
    private elementRef;
    singleSwitchPanel: ElementRef<HTMLElement>;
    singleSwitchContent: ElementRef<HTMLElement>;
    singleSwitchLabelRow: ElementRef<HTMLElement>;
    singleSwitchToggleRow: ElementRef<HTMLElement>;
    settings: SingleSwitchWidgetSettings;
    backgroundStyle$: Observable<ComponentStyle>;
    overlayStyle: ComponentStyle;
    padding: string;
    overlayInset: string;
    value: boolean;
    disabled: boolean;
    layout: SingleSwitchLayout;
    showIcon: boolean;
    icon: string;
    iconStyle: ComponentStyle;
    showLabel: boolean;
    label$: Observable<string>;
    labelStyle: ComponentStyle;
    showOnLabel: boolean;
    onLabel: string;
    onLabelStyle: ComponentStyle;
    showOffLabel: boolean;
    offLabel: string;
    offLabelStyle: ComponentStyle;
    disabledColor: string;
    autoScale: boolean;
    private panelResize$;
    private onValueSetter;
    private offValueSetter;
    private singleSwitchCssClass;
    constructor(imagePipe: ImagePipe, sanitizer: DomSanitizer, renderer: Renderer2, utils: UtilsService, cd: ChangeDetectorRef, elementRef: ElementRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onInit(): void;
    onToggleChange(event: MouseEvent): void;
    private onValue;
    private onDisabled;
    private onResize;
    static ɵfac: i0.ɵɵFactoryDeclaration<SingleSwitchWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SingleSwitchWidgetComponent, "tb-single-switch-widget", never, {}, {}, never, never, false, never>;
}
