import { AfterViewInit, ChangeDetectorRef, DestroyRef, ElementRef, NgZone, OnDestroy, OnInit, Renderer2 } from '@angular/core';
import { BasicActionWidgetComponent } from '@home/components/widget/lib/action/action-widget.models';
import { ComponentStyle } from '@shared/models/widget-settings.models';
import { BehaviorSubject, Observable } from 'rxjs';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import { MatIconRegistry } from '@angular/material/icon';
import { ValueStepperWidgetSettings } from '@home/components/widget/lib/rpc/value-stepper-widget.models';
import { UtilsService } from '@core/services/utils.service';
import * as i0 from "@angular/core";
export declare class ValueStepperWidgetComponent extends BasicActionWidgetComponent implements OnInit, AfterViewInit, OnDestroy {
    protected imagePipe: ImagePipe;
    protected sanitizer: DomSanitizer;
    private renderer;
    private iconRegistry;
    private utils;
    private elementRef;
    protected cd: ChangeDetectorRef;
    protected zone: NgZone;
    leftButton: ElementRef<HTMLElement>;
    rightButton: ElementRef<HTMLElement>;
    stepperContent: ElementRef<HTMLElement>;
    valueBox: ElementRef<HTMLElement>;
    valueElement: ElementRef<HTMLElement>;
    settings: ValueStepperWidgetSettings;
    backgroundStyle$: Observable<ComponentStyle>;
    overlayStyle: ComponentStyle;
    padding: string;
    valueStyle: ComponentStyle;
    valueStyleColor: string;
    disabledColor: string;
    value: number;
    autoScale: boolean;
    showValueBox: boolean;
    showLeftButton: boolean;
    showRightButton: boolean;
    valueText: string;
    disabledState$: BehaviorSubject<boolean>;
    private prevValue;
    private shapeResize$;
    private drawSvgShapePending;
    private svgShapeLeft;
    private svgShapeRight;
    private powerButtonSvgShapeLeft;
    private powerButtonSvgShapeRight;
    private disabledState;
    leftDisabledState: boolean;
    rightDisabledState: boolean;
    private valueSetterLeft;
    private valueSetterRight;
    private leftDisabledState$;
    private rightDisabledState$;
    private valueFormat;
    protected destroyRef: DestroyRef;
    constructor(imagePipe: ImagePipe, sanitizer: DomSanitizer, renderer: Renderer2, iconRegistry: MatIconRegistry, utils: UtilsService, elementRef: ElementRef, cd: ChangeDetectorRef, zone: NgZone);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onInit(): void;
    private onValue;
    private updateValueText;
    private onClick;
    private drawSvg;
    private updateLeftDisabledState;
    private updateRightDisabledState;
    private onResize;
    static ɵfac: i0.ɵɵFactoryDeclaration<ValueStepperWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ValueStepperWidgetComponent, "tb-value-stepper-widget", never, {}, {}, never, never, false, never>;
}
