import { ElementRef } from '@angular/core';
import { WidgetSettings, WidgetSettingsComponent } from '@shared/models/widget.models';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { MatChipInputEvent, MatChipGrid } from '@angular/material/chips';
import { MatAutocomplete, MatAutocompleteSelectedEvent } from '@angular/material/autocomplete';
import { Observable, Subject } from 'rxjs';
import * as i0 from "@angular/core";
export declare class NavigationCardsWidgetSettingsComponent extends WidgetSettingsComponent {
    protected store: Store<AppState>;
    private fb;
    filterItemsChipList: MatChipGrid;
    filterItemAutocomplete: MatAutocomplete;
    filterItemInput: ElementRef<HTMLInputElement>;
    filterItems: Array<string>;
    separatorKeysCodes: number[];
    navigationCardsWidgetSettingsForm: UntypedFormGroup;
    filteredFilterItems: Observable<Array<string>>;
    filterItemSearchText: string;
    filterItemInputChange: Subject<string>;
    constructor(store: Store<AppState>, fb: UntypedFormBuilder);
    protected settingsForm(): UntypedFormGroup;
    protected defaultSettings(): WidgetSettings;
    protected onSettingsSet(settings: WidgetSettings): void;
    protected validatorTriggers(): string[];
    protected updateValidators(emitEvent: boolean): void;
    private fetchFilterItems;
    private addFilterItem;
    onFilterItemRemoved(filterItem: string): void;
    onFilterItemInputFocus(): void;
    addFilterItemFromChipInput(event: MatChipInputEvent): void;
    filterItemSelected(event: MatAutocompleteSelectedEvent): void;
    clearFilterItemInput(value?: string): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<NavigationCardsWidgetSettingsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<NavigationCardsWidgetSettingsComponent, "tb-navigation-cards-widget-settings", never, {}, {}, never, never, false, never>;
}
