import { DestroyRef, OnInit, Renderer2, ViewContainerRef } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { MatButton } from '@angular/material/button';
import { TbPopoverService } from '@shared/components/popover.service';
import { MarkerIconSettings, MarkerShapeSettings, MarkerType } from '@shared/models/widget/maps/map.models';
import { Observable } from 'rxjs';
import { DomSanitizer, SafeHtml, SafeUrl } from '@angular/platform-browser';
import { MatIconRegistry } from '@angular/material/icon';
import { MapSettingsContext } from '@home/components/widget/lib/settings/common/map/map-settings.component.models';
import { DatasourceType } from '@shared/models/widget.models';
import * as i0 from "@angular/core";
export declare class MarkerShapeSettingsComponent implements ControlValueAccessor, OnInit {
    private popoverService;
    private fb;
    private destroyRef;
    private iconRegistry;
    private domSanitizer;
    private renderer;
    private viewContainerRef;
    MarkerType: typeof MarkerType;
    disabled: boolean;
    context: MapSettingsContext;
    dsType: DatasourceType;
    dsEntityAliasId: string;
    dsDeviceId: string;
    markerType: MarkerType;
    trip: boolean;
    modelValue: MarkerShapeSettings | MarkerIconSettings;
    shapeSettingsFormGroup: UntypedFormGroup;
    shapePreview$: Observable<SafeUrl>;
    iconPreview$: Observable<SafeHtml>;
    private propagateChange;
    constructor(popoverService: TbPopoverService, fb: UntypedFormBuilder, destroyRef: DestroyRef, iconRegistry: MatIconRegistry, domSanitizer: DomSanitizer, renderer: Renderer2, viewContainerRef: ViewContainerRef);
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: MarkerShapeSettings | MarkerIconSettings): void;
    openShapePopup($event: Event, matButton: MatButton): void;
    private updateModel;
    private updatePreview;
    static ɵfac: i0.ɵɵFactoryDeclaration<MarkerShapeSettingsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MarkerShapeSettingsComponent, "tb-marker-shape-settings", never, { "disabled": { "alias": "disabled"; "required": false; }; "context": { "alias": "context"; "required": false; }; "dsType": { "alias": "dsType"; "required": false; }; "dsEntityAliasId": { "alias": "dsEntityAliasId"; "required": false; }; "dsDeviceId": { "alias": "dsDeviceId"; "required": false; }; "markerType": { "alias": "markerType"; "required": false; }; "trip": { "alias": "trip"; "required": false; }; }, {}, never, never, false, never>;
}
