import { ChangeDetectorRef, EventEmitter, OnInit } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { TbPopoverComponent } from '@shared/components/popover.component';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { WidgetButtonToggleComponent } from '@shared/components/button/widget-button-toggle.component';
import { ButtonToggleAppearance, SegmentedButtonStyles, WidgetButtonToggleCustomStyle, WidgetButtonToggleState } from '@home/components/widget/lib/button/segmented-button-widget.models';
import * as i0 from "@angular/core";
export declare class WidgetButtonToggleCustomStylePanelComponent extends PageComponent implements OnInit {
    private fb;
    protected store: Store<AppState>;
    private cd;
    widgetButtonTogglePreview: WidgetButtonToggleComponent;
    appearance: ButtonToggleAppearance;
    value: boolean;
    borderRadius: string;
    autoScale: boolean;
    state: WidgetButtonToggleState;
    customStyle: WidgetButtonToggleCustomStyle;
    private popoverValue;
    set popover(popover: TbPopoverComponent<WidgetButtonToggleCustomStylePanelComponent>);
    get popover(): TbPopoverComponent<WidgetButtonToggleCustomStylePanelComponent>;
    customStyleApplied: EventEmitter<WidgetButtonToggleCustomStyle>;
    widgetButtonToggleStatesTranslationsMap: Map<WidgetButtonToggleState, string>;
    WidgetButtonToggleState: typeof WidgetButtonToggleState;
    previewAppearance: ButtonToggleAppearance;
    copyFromStates: WidgetButtonToggleState[];
    customStyleFormGroup: UntypedFormGroup;
    style: SegmentedButtonStyles;
    constructor(fb: UntypedFormBuilder, store: Store<AppState>, cd: ChangeDetectorRef);
    ngOnInit(): void;
    copyStyle(state: WidgetButtonToggleState): void;
    cancel(): void;
    applyCustomStyle(): void;
    private setStyle;
    private updateValidators;
    private updatePreviewAppearance;
    static ɵfac: i0.ɵɵFactoryDeclaration<WidgetButtonToggleCustomStylePanelComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<WidgetButtonToggleCustomStylePanelComponent, "tb-widget-button-toggle-custom-style-panel", never, { "appearance": { "alias": "appearance"; "required": false; }; "value": { "alias": "value"; "required": false; }; "borderRadius": { "alias": "borderRadius"; "required": false; }; "autoScale": { "alias": "autoScale"; "required": false; }; "state": { "alias": "state"; "required": false; }; "customStyle": { "alias": "customStyle"; "required": false; }; "popover": { "alias": "popover"; "required": false; }; }, { "customStyleApplied": "customStyleApplied"; }, never, never, false, never>;
}
