import { WidgetMobileActionType } from '@shared/models/widget.models';
import { TbFunction } from '@shared/models/js-function.models';
export declare const getDefaultProcessImageFunction: (type: WidgetMobileActionType) => TbFunction;
export declare const getDefaultProcessLaunchResultFunction: (type: WidgetMobileActionType) => TbFunction;
export declare const getDefaultProcessQrCodeFunction: () => string;
export declare const getDefaultProcessLocationFunction: () => string;
export declare const getDefaultProvisionSuccessFunction: () => string;
export declare const getDefaultGetLocationFunction: () => string;
export declare const getDefaultGetPhoneNumberFunction: () => string;
export declare const getDefaultHandleEmptyResultFunction: (type: WidgetMobileActionType) => TbFunction;
export declare const getDefaultHandleErrorFunction: (type: WidgetMobileActionType) => TbFunction;
export declare const getDefaultHandleNonMobileFallBackFunction: () => string;
