import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { BasicWidgetConfigComponent } from '@home/components/widget/config/widget-config.component.models';
import { WidgetConfigComponentData } from '@home/models/widget-component.models';
import { TargetDevice } from '@shared/models/widget.models';
import { WidgetConfigComponent } from '@home/components/widget/widget-config.component';
import { ValueType } from '@shared/models/constants';
import * as i0 from "@angular/core";
export declare class SingleSwitchBasicConfigComponent extends BasicWidgetConfigComponent {
    protected store: Store<AppState>;
    protected widgetConfigComponent: WidgetConfigComponent;
    private fb;
    get targetDevice(): TargetDevice;
    singleSwitchLayouts: import("@home/components/widget/lib/rpc/single-switch-widget.models").SingleSwitchLayout[];
    singleSwitchLayoutTranslationMap: Map<import("@home/components/widget/lib/rpc/single-switch-widget.models").SingleSwitchLayout, string>;
    singleSwitchLayoutImageMap: Map<import("@home/components/widget/lib/rpc/single-switch-widget.models").SingleSwitchLayout, string>;
    valueType: typeof ValueType;
    singleSwitchWidgetConfigForm: UntypedFormGroup;
    constructor(store: Store<AppState>, widgetConfigComponent: WidgetConfigComponent, fb: UntypedFormBuilder);
    protected configForm(): UntypedFormGroup;
    protected onConfigSet(configData: WidgetConfigComponentData): void;
    protected prepareOutputConfig(config: any): WidgetConfigComponentData;
    protected validatorTriggers(): string[];
    protected updateValidators(emitEvent: boolean, trigger?: string): void;
    private getCardButtons;
    private setCardButtons;
    static ɵfac: i0.ɵɵFactoryDeclaration<SingleSwitchBasicConfigComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SingleSwitchBasicConfigComponent, "tb-single-switch-basic-config", never, {}, {}, never, never, false, never>;
}
