import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { BasicWidgetConfigComponent } from '@home/components/widget/config/widget-config.component.models';
import { WidgetConfigComponentData } from '@home/models/widget-component.models';
import { TargetDevice } from '@shared/models/widget.models';
import { WidgetConfigComponent } from '@home/components/widget/widget-config.component';
import { ValueType } from '@shared/models/constants';
import * as i0 from "@angular/core";
type ButtonAppearanceType = 'left' | 'right';
export declare class ValueStepperBasicConfigComponent extends BasicWidgetConfigComponent {
    protected store: Store<AppState>;
    protected widgetConfigComponent: WidgetConfigComponent;
    private fb;
    get targetDevice(): TargetDevice;
    valueStepperTypeTranslationMap: Map<import("@home/components/widget/lib/rpc/value-stepper-widget.models").ValueStepperType, string>;
    valueStepperTypes: import("@home/components/widget/lib/rpc/value-stepper-widget.models").ValueStepperType[];
    valueStepperTypeImageMap: Map<import("@home/components/widget/lib/rpc/value-stepper-widget.models").ValueStepperType, string>;
    buttonAppearanceType: ButtonAppearanceType;
    valueType: typeof ValueType;
    valueStepperWidgetConfigForm: UntypedFormGroup;
    valuePreviewFn: any;
    constructor(store: Store<AppState>, widgetConfigComponent: WidgetConfigComponent, fb: UntypedFormBuilder);
    protected configForm(): UntypedFormGroup;
    protected onConfigSet(configData: WidgetConfigComponentData): void;
    protected prepareOutputConfig(config: any): WidgetConfigComponentData;
    protected validatorTriggers(): string[];
    protected updateValidators(emitEvent: boolean, trigger?: string): void;
    private buttonValidators;
    private getCardButtons;
    private setCardButtons;
    private _valuePreviewFn;
    static ɵfac: i0.ɵɵFactoryDeclaration<ValueStepperBasicConfigComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ValueStepperBasicConfigComponent, "tb-value-stepper-basic-config", never, {}, {}, never, never, false, never>;
}
export {};
