import { OnInit } from '@angular/core';
import { ErrorStateMatcher } from '@angular/material/core';
import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { FormGroupDirective, NgForm, UntypedFormBuilder, UntypedFormControl, UntypedFormGroup } from '@angular/forms';
import { Router } from '@angular/router';
import { DialogComponent } from '@shared/components/dialog.component';
import { DataKey, DataKeyConfigMode, Widget, widgetType } from '@shared/models/widget.models';
import { DataKeyConfigComponent } from '@home/components/widget/config/data-key-config.component';
import { Dashboard } from '@shared/models/dashboard.models';
import { IAliasController } from '@core/api/widget-api.models';
import { ToggleHeaderOption } from '@shared/components/toggle-header.component';
import { TranslateService } from '@ngx-translate/core';
import { WidgetConfigCallbacks } from '@home/components/widget/config/widget-config.component.models';
import * as i0 from "@angular/core";
export interface DataKeyConfigDialogData {
    dataKey: DataKey;
    dataKeyConfigMode?: DataKeyConfigMode;
    dataKeySettingsSchema: any;
    dataKeySettingsDirective: string;
    dashboard: Dashboard;
    aliasController: IAliasController;
    widget: Widget;
    widgetType: widgetType;
    deviceId?: string;
    entityAliasId?: string;
    showPostProcessing?: boolean;
    callbacks?: WidgetConfigCallbacks;
    hideDataKeyName?: boolean;
    hideDataKeyLabel?: boolean;
    hideDataKeyColor?: boolean;
    hideDataKeyUnits?: boolean;
    hideDataKeyDecimals?: boolean;
}
export declare class DataKeyConfigDialogComponent extends DialogComponent<DataKeyConfigDialogComponent, DataKey> implements OnInit, ErrorStateMatcher {
    protected store: Store<AppState>;
    protected router: Router;
    data: DataKeyConfigDialogData;
    private errorStateMatcher;
    dialogRef: MatDialogRef<DataKeyConfigDialogComponent, DataKey>;
    private translate;
    fb: UntypedFormBuilder;
    dataKeyConfig: DataKeyConfigComponent;
    hasAdvanced: boolean;
    dataKeyConfigHeaderOptions: ToggleHeaderOption[];
    dataKeyConfigMode: DataKeyConfigMode;
    dataKeyFormGroup: UntypedFormGroup;
    submitted: boolean;
    constructor(store: Store<AppState>, router: Router, data: DataKeyConfigDialogData, errorStateMatcher: ErrorStateMatcher, dialogRef: MatDialogRef<DataKeyConfigDialogComponent, DataKey>, translate: TranslateService, fb: UntypedFormBuilder);
    ngOnInit(): void;
    isErrorState(control: UntypedFormControl | null, form: FormGroupDirective | NgForm | null): boolean;
    cancel(): void;
    save(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<DataKeyConfigDialogComponent, [null, null, null, { skipSelf: true; }, null, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DataKeyConfigDialogComponent, "tb-data-key-config-dialog", never, {}, {}, never, never, false, never>;
}
