import { OnChanges, OnDestroy, SimpleChanges, ViewContainerRef } from '@angular/core';
import { AbstractControl, ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup, ValidationErrors, Validator } from '@angular/forms';
import { Subscription } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { JsonFormComponent } from '@shared/components/json-form/json-form.component';
import { JsonFormComponentData } from '@shared/components/json-form/json-form-component.models';
import { Widget } from '@shared/models/widget.models';
import { Dashboard } from '@shared/models/dashboard.models';
import { WidgetService } from '@core/http/widget.service';
import { IAliasController } from '@core/api/widget-api.models';
import { WidgetConfigComponentData } from '@home/models/widget-component.models';
import { WidgetConfigCallbacks } from '@home/components/widget/config/widget-config.component.models';
import * as i0 from "@angular/core";
export declare class WidgetSettingsComponent implements ControlValueAccessor, OnDestroy, OnChanges, Validator {
    private translate;
    private widgetService;
    private fb;
    definedSettingsContainer: ViewContainerRef;
    jsonFormComponent: JsonFormComponent;
    disabled: boolean;
    aliasController: IAliasController;
    callbacks: WidgetConfigCallbacks;
    dashboard: Dashboard;
    widget: Widget;
    widgetConfig: WidgetConfigComponentData;
    private settingsDirective;
    definedDirectiveError: string;
    widgetSettingsFormGroup: UntypedFormGroup;
    changeSubscription: Subscription;
    private definedSettingsComponentRef;
    private definedSettingsComponent;
    private widgetSettingsFormData;
    private propagateChange;
    constructor(translate: TranslateService, widgetService: WidgetService, fb: UntypedFormBuilder);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnChanges(changes: SimpleChanges): void;
    ngOnDestroy(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: JsonFormComponentData): void;
    useDefinedDirective(): boolean;
    useJsonForm(): boolean;
    private updateModel;
    private validateDefinedDirective;
    validate(control: AbstractControl): ValidationErrors | null;
    static ɵfac: i0.ɵɵFactoryDeclaration<WidgetSettingsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<WidgetSettingsComponent, "tb-widget-settings", never, { "disabled": { "alias": "disabled"; "required": false; }; "aliasController": { "alias": "aliasController"; "required": false; }; "callbacks": { "alias": "callbacks"; "required": false; }; "dashboard": { "alias": "dashboard"; "required": false; }; "widget": { "alias": "widget"; "required": false; }; "widgetConfig": { "alias": "widgetConfig"; "required": false; }; }, {}, never, never, false, never>;
}
