import { Injector } from '@angular/core';
import { UntypedFormBuilder, UntypedFormGroup } from '@angular/forms';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { BasicWidgetConfigComponent } from '@home/components/widget/config/widget-config.component.models';
import { WidgetConfigComponentData } from '@home/models/widget-component.models';
import { DataKey, Datasource } from '@shared/models/widget.models';
import { WidgetConfigComponent } from '@home/components/widget/widget-config.component';
import { TimeSeriesChartType } from '@home/components/widget/lib/chart/time-series-chart.models';
import * as i0 from "@angular/core";
export declare class BarChartWithLabelsBasicConfigComponent extends BasicWidgetConfigComponent {
    protected store: Store<AppState>;
    protected widgetConfigComponent: WidgetConfigComponent;
    private $injector;
    private fb;
    get datasource(): Datasource;
    legendPositions: import("@shared/models/widget.models").LegendPosition[];
    legendPositionTranslationMap: Map<import("@shared/models/widget.models").LegendPosition, string>;
    barChartWidgetConfigForm: UntypedFormGroup;
    tooltipValuePreviewFn: any;
    tooltipDatePreviewFn: any;
    constructor(store: Store<AppState>, widgetConfigComponent: WidgetConfigComponent, $injector: Injector, fb: UntypedFormBuilder);
    protected configForm(): UntypedFormGroup;
    protected defaultDataKeys(configData: WidgetConfigComponentData): DataKey[];
    protected onConfigSet(configData: WidgetConfigComponentData): void;
    protected prepareOutputConfig(config: any): WidgetConfigComponentData;
    protected validatorTriggers(): string[];
    protected updateValidators(emitEvent: boolean, trigger?: string): void;
    private getSeries;
    private setSeries;
    private getCardButtons;
    private setCardButtons;
    private _tooltipValuePreviewFn;
    private _tooltipDatePreviewFn;
    protected readonly TimeSeriesChartType: typeof TimeSeriesChartType;
    static ɵfac: i0.ɵɵFactoryDeclaration<BarChartWithLabelsBasicConfigComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<BarChartWithLabelsBasicConfigComponent, "tb-bar-chart-with-labels-basic-config", never, {}, {}, never, never, false, never>;
}
