import { ChangeDetectorRef, ElementRef, EventEmitter, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { AbstractControl, ControlValueAccessor, UntypedFormBuilder, UntypedFormControl, UntypedFormGroup, ValidationErrors } from '@angular/forms';
import { MatDialog } from '@angular/material/dialog';
import { WidgetConfigComponent } from '@home/components/widget/widget-config.component';
import { DataKey, DatasourceType, JsonSettingsSchema, Widget, widgetType } from '@shared/models/widget.models';
import { DataKeyType } from '@shared/models/telemetry/telemetry.models';
import { MatChipGrid, MatChipInputEvent } from '@angular/material/chips';
import { DataKeysCallbacks } from '@home/components/widget/config/data-keys.component.models';
import { MatAutocomplete, MatAutocompleteTrigger } from '@angular/material/autocomplete';
import { Observable } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { TruncatePipe } from '@shared/pipe/truncate.pipe';
import { Dashboard } from '@shared/models/dashboard.models';
import { IAliasController } from '@core/api/widget-api.models';
import { UtilsService } from '@core/services/utils.service';
import * as i0 from "@angular/core";
export declare const dataKeyValid: (key: DataKey) => boolean;
export declare const dataKeyRowValidator: (control: AbstractControl) => ValidationErrors | null;
export declare class DataKeyRowComponent implements ControlValueAccessor, OnInit, OnChanges {
    private fb;
    private dialog;
    private cd;
    translate: TranslateService;
    truncate: TruncatePipe;
    private utils;
    private widgetConfigComponent;
    dataKeyTypes: typeof DataKeyType;
    widgetTypes: typeof widgetType;
    separatorKeysCodes: number[];
    keyInput: ElementRef<HTMLInputElement>;
    matAutocomplete: MatAutocomplete;
    autocomplete: MatAutocompleteTrigger;
    chipList: MatChipGrid;
    disabled: boolean;
    required: boolean;
    datasourceType: DatasourceType;
    entityAliasId: string;
    deviceId: string;
    hasAdditionalLatestDataKeys: boolean;
    hideDataKeyLabel: boolean;
    hideDataKeyColor: boolean;
    hideDataKeyUnits: boolean;
    hideDataKeyDecimals: boolean;
    hideUnits: boolean;
    hideDecimals: boolean;
    singleRow: boolean;
    dataKeyType: DataKeyType;
    keySettingsTitle: string;
    removeKeyTitle: string;
    keyRemoved: EventEmitter<any>;
    keysFormControl: UntypedFormControl;
    keyFormControl: UntypedFormControl;
    keyRowFormGroup: UntypedFormGroup;
    modelValue: DataKey;
    filteredKeys: Observable<Array<DataKey>>;
    keySearchText: string;
    alarmKeys: Array<DataKey>;
    functionTypeKeys: Array<DataKey>;
    private latestKeySearchTextResult;
    private keyFetchObservable$;
    get widgetType(): widgetType;
    get callbacks(): DataKeysCallbacks;
    get widget(): Widget;
    get dashboard(): Dashboard;
    get aliasController(): IAliasController;
    get dataKeySettingsSchema(): JsonSettingsSchema;
    get dataKeySettingsDirective(): string;
    get latestDataKeySettingsSchema(): JsonSettingsSchema;
    get latestDataKeySettingsDirective(): string;
    get isEntityDatasource(): boolean;
    get displayUnitsOrDigits(): boolean;
    get isLatestDataKeys(): boolean;
    private propagateChange;
    constructor(fb: UntypedFormBuilder, dialog: MatDialog, cd: ChangeDetectorRef, translate: TranslateService, truncate: TruncatePipe, utils: UtilsService, widgetConfigComponent: WidgetConfigComponent);
    ngOnInit(): void;
    private reset;
    ngOnChanges(changes: SimpleChanges): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: DataKey): void;
    dataKeyHasAggregation(): boolean;
    dataKeyHasPostprocessing(): boolean;
    displayKeyFn(key?: DataKey): string | undefined;
    createKey(name: string, dataKeyType?: DataKeyType): void;
    addKey(event: MatChipInputEvent): void;
    editKey(advanced?: boolean): void;
    removeKey(): void;
    textIsNotEmpty(text: string): boolean;
    clearKeyChip(value?: string, focus?: boolean): void;
    onKeyInputFocus(): void;
    private fetchKeys;
    private getKeys;
    private createDataKeyFilter;
    private addKeyFromChipValue;
    private clearKeySearchCache;
    private updateModel;
    static ɵfac: i0.ɵɵFactoryDeclaration<DataKeyRowComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DataKeyRowComponent, "tb-data-key-row", never, { "disabled": "disabled"; "required": "required"; "datasourceType": "datasourceType"; "entityAliasId": "entityAliasId"; "deviceId": "deviceId"; "hasAdditionalLatestDataKeys": "hasAdditionalLatestDataKeys"; "hideDataKeyLabel": "hideDataKeyLabel"; "hideDataKeyColor": "hideDataKeyColor"; "hideDataKeyUnits": "hideDataKeyUnits"; "hideDataKeyDecimals": "hideDataKeyDecimals"; "hideUnits": "hideUnits"; "hideDecimals": "hideDecimals"; "singleRow": "singleRow"; "dataKeyType": "dataKeyType"; "keySettingsTitle": "keySettingsTitle"; "removeKeyTitle": "removeKeyTitle"; }, { "keyRemoved": "keyRemoved"; }, never, never, false, never>;
}
