import { OnInit, ViewContainerRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { Observable } from 'rxjs';
import { DashboardInfo } from '@app/shared/models/dashboard.models';
import { DashboardService } from '@core/http/dashboard.service';
import { Store } from '@ngrx/store';
import { AppState } from '@app/core/core.state';
import { TooltipPosition } from '@angular/material/tooltip';
import { CdkOverlayOrigin, Overlay } from '@angular/cdk/overlay';
import { BreakpointObserver } from '@angular/cdk/layout';
import * as i0 from "@angular/core";
export declare class DashboardSelectComponent implements ControlValueAccessor, OnInit {
    private store;
    private dashboardService;
    private overlay;
    private breakpointObserver;
    private viewContainerRef;
    private document;
    private window;
    dashboardsScope: 'customer' | 'tenant';
    customerId: string;
    tooltipPosition: TooltipPosition;
    private requiredValue;
    get required(): boolean;
    set required(value: boolean);
    disabled: boolean;
    dashboards$: Observable<Array<DashboardInfo>>;
    dashboardId: string | null;
    dashboardSelectPanelOrigin: CdkOverlayOrigin;
    private propagateChange;
    constructor(store: Store<AppState>, dashboardService: DashboardService, overlay: Overlay, breakpointObserver: BreakpointObserver, viewContainerRef: ViewContainerRef, document: Document, window: Window);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: string | null): void;
    dashboardIdChanged(): void;
    openDashboardSelectPanel(): void;
    private _createDashboardSelectPanelInjector;
    private updateView;
    private getDashboards;
    static ɵfac: i0.ɵɵFactoryDeclaration<DashboardSelectComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<DashboardSelectComponent, "tb-dashboard-select", never, { "dashboardsScope": "dashboardsScope"; "customerId": "customerId"; "tooltipPosition": "tooltipPosition"; "required": "required"; "disabled": "disabled"; }, {}, never, never>;
}
