import { AfterViewInit, ElementRef, EventEmitter, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { ControlValueAccessor } from '@angular/forms';
import { Subscription } from 'rxjs';
import { FlowDirective } from '@flowjs/ngx-flow';
import { TranslateService } from '@ngx-translate/core';
import { UtilsService } from '@core/services/utils.service';
import { DialogService } from '@core/services/dialog.service';
import { FileSizePipe } from '@shared/pipe/file-size.pipe';
import * as i0 from "@angular/core";
export declare class FileInputComponent extends PageComponent implements AfterViewInit, OnDestroy, ControlValueAccessor, OnChanges {
    protected store: Store<AppState>;
    private utils;
    private translate;
    private dialog;
    private fileSize;
    label: string;
    hint: string;
    accept: string;
    noFileText: string;
    inputId: string;
    allowedExtensions: string;
    dropLabel: string;
    maxSizeByte: number;
    contentConvertFunction: (content: string) => any;
    required: boolean;
    requiredAsError: boolean;
    disabled: boolean;
    existingFileName: string;
    readAsBinary: boolean;
    workFromFileObj: boolean;
    private multipleFileValue;
    set multipleFile(value: boolean);
    get multipleFile(): boolean;
    fileNameChanged: EventEmitter<string | string[]>;
    fileName: string | string[];
    fileContent: any;
    files: File[];
    flow: FlowDirective;
    flowInput: ElementRef;
    autoUploadSubscription: Subscription;
    private propagateChange;
    constructor(store: Store<AppState>, utils: UtilsService, translate: TranslateService, dialog: DialogService, fileSize: FileSizePipe);
    ngAfterViewInit(): void;
    private readerAsFile;
    private checkMaxSize;
    private filterFile;
    ngOnDestroy(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: any): void;
    ngOnChanges(changes: SimpleChanges): void;
    private updateModel;
    clearFile(): void;
    private updateMultipleFileMode;
    static ɵfac: i0.ɵɵFactoryDeclaration<FileInputComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<FileInputComponent, "tb-file-input", never, { "label": { "alias": "label"; "required": false; }; "hint": { "alias": "hint"; "required": false; }; "accept": { "alias": "accept"; "required": false; }; "noFileText": { "alias": "noFileText"; "required": false; }; "inputId": { "alias": "inputId"; "required": false; }; "allowedExtensions": { "alias": "allowedExtensions"; "required": false; }; "dropLabel": { "alias": "dropLabel"; "required": false; }; "maxSizeByte": { "alias": "maxSizeByte"; "required": false; }; "contentConvertFunction": { "alias": "contentConvertFunction"; "required": false; }; "required": { "alias": "required"; "required": false; }; "requiredAsError": { "alias": "requiredAsError"; "required": false; }; "disabled": { "alias": "disabled"; "required": false; }; "existingFileName": { "alias": "existingFileName"; "required": false; }; "readAsBinary": { "alias": "readAsBinary"; "required": false; }; "workFromFileObj": { "alias": "workFromFileObj"; "required": false; }; "multipleFile": { "alias": "multipleFile"; "required": false; }; }, { "fileNameChanged": "fileNameChanged"; }, never, never, false, never>;
}
