import { AfterContentInit, AfterViewChecked, ElementRef, ErrorHandler, OnDestroy, Renderer2 } from '@angular/core';
import { MatIconLocation, MatIconRegistry } from '@angular/material/icon';
import { ContentObserver } from '@angular/cdk/observers';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import * as i0 from "@angular/core";
export declare class TbIconComponent implements AfterContentInit, AfterViewChecked, OnDestroy {
    private contentObserver;
    private renderer;
    private _iconRegistry;
    private imagePipe;
    private sanitizer;
    private _location;
    private readonly _errorHandler;
    _iconNameContent: ElementRef;
    readonly _elementRef: ElementRef<HTMLElement>;
    private _defaultColor;
    get color(): string | null | undefined;
    set color(value: string | null | undefined);
    private _color;
    private icon;
    get viewValue(): string;
    private _contentChanges;
    private _previousFontSetClass;
    _useSvgIcon: boolean;
    _svgName: string | null;
    _svgNamespace: string | null;
    private _textElement;
    _useImageIcon: boolean;
    private _imageElement;
    private _previousPath?;
    private _elementsWithExternalReferences?;
    private _currentIconFetch;
    constructor(contentObserver: ContentObserver, renderer: Renderer2, _iconRegistry: MatIconRegistry, imagePipe: ImagePipe, sanitizer: DomSanitizer, _location: MatIconLocation, _errorHandler: ErrorHandler);
    ngAfterContentInit(): void;
    ngAfterViewChecked(): void;
    ngOnDestroy(): void;
    private _updateIcon;
    private _updateFontIcon;
    private _clearFontIcon;
    private _updateSvgIcon;
    private _setSvgElement;
    private _clearSvgElement;
    private _cacheChildrenWithExternalReferences;
    private _prependPathToReferences;
    private _updateImageIcon;
    private _setImageElement;
    private _clearImageIcon;
    static ɵfac: i0.ɵɵFactoryDeclaration<TbIconComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TbIconComponent, "tb-icon", ["tbIcon"], { "color": { "alias": "color"; "required": false; }; }, {}, never, ["*"], false, never>;
}
