import { PageComponent } from '@shared/components/page.component';
import { ChangeDetectorRef, EventEmitter, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UntypedFormControl } from '@angular/forms';
import { BehaviorSubject, Observable } from 'rxjs';
import { CdkVirtualScrollViewport } from '@angular/cdk/scrolling';
import { MaterialIcon } from '@shared/models/icon.models';
import { ResourcesService } from '@core/services/resources.service';
import { TbPopoverComponent } from '@shared/components/popover.component';
import { BreakpointObserver } from '@angular/cdk/layout';
import * as i0 from "@angular/core";
export declare class MaterialIconsComponent extends PageComponent implements OnInit {
    protected store: Store<AppState>;
    private resourcesService;
    private breakpointObserver;
    private cd;
    iconsPanel: CdkVirtualScrollViewport;
    selectedIcon: string;
    iconClearButton: boolean;
    popover: TbPopoverComponent<MaterialIconsComponent>;
    iconSelected: EventEmitter<string>;
    iconRows$: Observable<MaterialIcon[][]>;
    showAllSubject: BehaviorSubject<boolean>;
    searchIconControl: UntypedFormControl;
    iconsRowHeight: number;
    iconsPanelHeight: string;
    iconsPanelWidth: string;
    notFound: boolean;
    constructor(store: Store<AppState>, resourcesService: ResourcesService, breakpointObserver: BreakpointObserver, cd: ChangeDetectorRef);
    ngOnInit(): void;
    clearSearch(): void;
    selectIcon(icon: MaterialIcon): void;
    clearIcon(): void;
    private calculatePanelSize;
    private checkSize;
    static ɵfac: i0.ɵɵFactoryDeclaration<MaterialIconsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<MaterialIconsComponent, "tb-material-icons", never, { "selectedIcon": { "alias": "selectedIcon"; "required": false; }; "iconClearButton": { "alias": "iconClearButton"; "required": false; }; "popover": { "alias": "popover"; "required": false; }; }, { "iconSelected": "iconSelected"; }, never, never, false, never>;
}
