import { OnInit } from '@angular/core';
import { ControlValueAccessor, UntypedFormBuilder, UntypedFormGroup, ValidationErrors, Validator, ValidatorFn } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { Country, CountryData } from '@shared/models/country.models';
import { FloatLabelType, MatFormFieldAppearance } from '@angular/material/form-field';
import * as i0 from "@angular/core";
export declare class PhoneInputComponent implements OnInit, ControlValueAccessor, Validator {
    private translate;
    private fb;
    private countryCodeData;
    disabled: boolean;
    defaultCountry: string;
    enableFlagsSelect: boolean;
    required: boolean;
    floatLabel: FloatLabelType;
    appearance: MatFormFieldAppearance;
    placeholder: any;
    label: any;
    get showFlagSelect(): boolean;
    allCountries: Array<Country>;
    phonePlaceholder: string;
    flagIcon: string;
    phoneFormGroup: UntypedFormGroup;
    private isLoading;
    get isLoad(): boolean;
    set isLoad(value: boolean);
    private isLegacy;
    private getExampleNumber;
    private parsePhoneNumberFromString;
    private baseCode;
    private countryCallingCode;
    private modelValue;
    private changeSubscriptions;
    private validators;
    private propagateChange;
    constructor(translate: TranslateService, fb: UntypedFormBuilder, countryCodeData: CountryData);
    ngOnInit(): void;
    ngOnDestroy(): void;
    focus(): void;
    private getFlagAndPhoneNumberData;
    private getPhoneNumberData;
    private getFlagIcon;
    private updateModelValueInFormat;
    validatePhoneNumber(): ValidatorFn;
    private defineCountryFromNumber;
    validate(): ValidationErrors | null;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(phoneNumber: any): void;
    private updateModel;
    static ɵfac: i0.ɵɵFactoryDeclaration<PhoneInputComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<PhoneInputComponent, "tb-phone-input", never, { "disabled": { "alias": "disabled"; "required": false; }; "defaultCountry": { "alias": "defaultCountry"; "required": false; }; "enableFlagsSelect": { "alias": "enableFlagsSelect"; "required": false; }; "required": { "alias": "required"; "required": false; }; "floatLabel": { "alias": "floatLabel"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; "placeholder": { "alias": "placeholder"; "required": false; }; "label": { "alias": "label"; "required": false; }; }, {}, never, never, false, never>;
}
