import { OnInit, ElementRef } from '@angular/core';
import { ControlValueAccessor, FormControl, FormBuilder } from '@angular/forms';
import { Observable } from 'rxjs';
import { TranslateService } from '@ngx-translate/core';
import { MatFormFieldAppearance, SubscriptSizing } from '@angular/material/form-field';
import * as i0 from "@angular/core";
export declare class StringAutocompleteComponent implements ControlValueAccessor, OnInit {
    private fb;
    private translate;
    nameInput: ElementRef;
    disabled: boolean;
    required: boolean;
    fetchOptionsFn: (searchText?: string) => Observable<Array<string>>;
    placeholderText: string;
    subscriptSizing: SubscriptSizing;
    additionalClass: string | string[] | Record<string, boolean | undefined | null>;
    appearance: MatFormFieldAppearance;
    label: string;
    tooltipClass: string;
    errorText: string;
    showInlineError: boolean;
    selectionFormControl: FormControl;
    modelValue: string | null;
    filteredOptions$: Observable<Array<string>>;
    searchText: string;
    private dirty;
    private propagateChange;
    constructor(fb: FormBuilder, translate: TranslateService);
    ngOnInit(): void;
    writeValue(option?: string): void;
    onFocus(): void;
    updateView(value: string): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    clear(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<StringAutocompleteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<StringAutocompleteComponent, "tb-string-autocomplete", never, { "disabled": { "alias": "disabled"; "required": false; }; "required": { "alias": "required"; "required": false; }; "fetchOptionsFn": { "alias": "fetchOptionsFn"; "required": false; }; "placeholderText": { "alias": "placeholderText"; "required": false; }; "subscriptSizing": { "alias": "subscriptSizing"; "required": false; }; "additionalClass": { "alias": "additionalClass"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; "label": { "alias": "label"; "required": false; }; "tooltipClass": { "alias": "tooltipClass"; "required": false; }; "errorText": { "alias": "errorText"; "required": false; }; "showInlineError": { "alias": "showInlineError"; "required": false; }; }, {}, never, never, false, never>;
}
