import { DestroyRef, OnChanges, OnInit, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, FormBuilder, ValidationErrors, Validator } from '@angular/forms';
import { TimeUnit } from '@home/components/rule-node/rule-node-config.models';
import { MatFormFieldAppearance, SubscriptSizing } from '@angular/material/form-field';
import * as i0 from "@angular/core";
export declare class TimeUnitInputComponent implements ControlValueAccessor, Validator, OnInit, OnChanges {
    private fb;
    private destroyRef;
    labelText: string;
    hintText: string;
    required: boolean;
    requiredText: string;
    minTime: number;
    minErrorText: string;
    maxTime: number;
    maxErrorText: string;
    stepMultipleOf: number;
    stepMultipleOfErrorText: string;
    subscriptSizing: SubscriptSizing;
    appearance: MatFormFieldAppearance;
    inlineField: boolean;
    sameWidthInputs: boolean;
    containerClass: string | string[] | Record<string, boolean | undefined | null>;
    timeUnits: TimeUnit[];
    timeUnitTranslations: Map<TimeUnit, string>;
    timeInputForm: import("@angular/forms").FormGroup<{
        time: import("@angular/forms").FormControl<number>;
        timeUnit: import("@angular/forms").FormControl<TimeUnit>;
    }>;
    private timeIntervalsInSec;
    minValueValidator: number;
    private modelValue;
    private propagateChange;
    constructor(fb: FormBuilder, destroyRef: DestroyRef);
    ngOnInit(): void;
    get minValue(): number;
    get hasError(): string;
    ngOnChanges(changes: SimpleChanges): void;
    registerOnChange(fn: any): void;
    registerOnTouched(_fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(sec: number): void;
    validate(): ValidationErrors | null;
    private updatedModel;
    private parseTime;
    private createStepMultipleOfValidator;
    private updatedAllowTimeUnitInterval;
    private refreshTimeValidators;
    static ɵfac: i0.ɵɵFactoryDeclaration<TimeUnitInputComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<TimeUnitInputComponent, "tb-time-unit-input", never, { "labelText": { "alias": "labelText"; "required": false; }; "hintText": { "alias": "hintText"; "required": false; }; "required": { "alias": "required"; "required": false; }; "requiredText": { "alias": "requiredText"; "required": false; }; "minTime": { "alias": "minTime"; "required": false; }; "minErrorText": { "alias": "minErrorText"; "required": false; }; "maxTime": { "alias": "maxTime"; "required": false; }; "maxErrorText": { "alias": "maxErrorText"; "required": false; }; "stepMultipleOf": { "alias": "stepMultipleOf"; "required": false; }; "stepMultipleOfErrorText": { "alias": "stepMultipleOfErrorText"; "required": false; }; "subscriptSizing": { "alias": "subscriptSizing"; "required": false; }; "appearance": { "alias": "appearance"; "required": false; }; "inlineField": { "alias": "inlineField"; "required": false; }; "sameWidthInputs": { "alias": "sameWidthInputs"; "required": false; }; "containerClass": { "alias": "containerClass"; "required": false; }; }, {}, never, ["[matSuffix]"], false, never>;
}
