import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, FormControl, UntypedFormBuilder } from '@angular/forms';
import { Observable } from 'rxjs';
import { Unit } from '@shared/models/unit.models';
import { TranslateService } from '@ngx-translate/core';
import * as i0 from "@angular/core";
export declare class UnitInputComponent implements ControlValueAccessor, OnInit {
    private fb;
    private translate;
    unitsFormControl: FormControl;
    modelValue: string | null;
    disabled: boolean;
    unitInput: ElementRef;
    filteredUnits: Observable<Array<Unit | string>>;
    searchText: string;
    private dirty;
    private translatedUnits;
    private propagateChange;
    constructor(fb: UntypedFormBuilder, translate: TranslateService);
    ngOnInit(): void;
    writeValue(symbol?: string): void;
    onFocus(): void;
    updateView(value: Unit | string | null): void;
    displayUnitFn(unit?: Unit | string): string | undefined;
    fetchUnits(searchText?: string): Observable<Array<Unit | string>>;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    clear(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<UnitInputComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<UnitInputComponent, "tb-unit-input", never, { "disabled": "disabled"; }, {}, never, never, false, never>;
}
