import { ComponentFactoryResolver, Injector, OnInit } from '@angular/core';
import { ErrorStateMatcher } from '@angular/material/core';
import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { FormControl, FormGroupDirective, NgForm, FormGroup } from '@angular/forms';
import { EntityType, EntityTypeResource, EntityTypeTranslation } from '@shared/models/entity-type.models';
import { BaseData, HasId } from '@shared/models/base-data';
import { EntityId } from '@shared/models/id/entity-id';
import { TbAnchorComponent } from '@shared/components/tb-anchor.component';
import { DialogComponent } from '@shared/components/dialog.component';
import { Router } from '@angular/router';
import { GroupEntityComponent } from '@home/components/group/group-entity.component';
import { GroupEntityTableConfig } from '@home/models/group/group-entities-table-config.models';
import { AddGroupEntityDialogData } from '@home/models/group/group-entity-component.models';
import { EntityGroupInfo } from '@shared/models/entity-group.models';
import { EntityService } from '@core/http/entity.service';
import * as i0 from "@angular/core";
export declare class AddGroupEntityDialogComponent extends DialogComponent<AddGroupEntityDialogComponent, BaseData<HasId>> implements OnInit, ErrorStateMatcher {
    protected store: Store<AppState>;
    protected router: Router;
    data: AddGroupEntityDialogData<BaseData<HasId>>;
    dialogRef: MatDialogRef<AddGroupEntityDialogComponent, BaseData<HasId>>;
    private componentFactoryResolver;
    private injector;
    private errorStateMatcher;
    private entityService;
    entityComponent: GroupEntityComponent<BaseData<HasId>>;
    detailsForm: FormGroup;
    entitiesTableConfig: GroupEntityTableConfig<BaseData<HasId>>;
    entityGroup: EntityGroupInfo;
    entityType: EntityType;
    translations: EntityTypeTranslation;
    resources: EntityTypeResource<BaseData<HasId>>;
    entity: BaseData<EntityId>;
    submitted: boolean;
    entityDetailsFormAnchor: TbAnchorComponent;
    constructor(store: Store<AppState>, router: Router, data: AddGroupEntityDialogData<BaseData<HasId>>, dialogRef: MatDialogRef<AddGroupEntityDialogComponent, BaseData<HasId>>, componentFactoryResolver: ComponentFactoryResolver, injector: Injector, errorStateMatcher: ErrorStateMatcher, entityService: EntityService);
    ngOnInit(): void;
    helpLinkId(): string;
    isErrorState(control: FormControl | null, form: FormGroupDirective | NgForm | null): boolean;
    cancel(): void;
    add(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<AddGroupEntityDialogComponent, [null, null, null, null, null, null, { skipSelf: true; }, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<AddGroupEntityDialogComponent, "tb-add-group-entity-dialog", never, {}, {}, never, never>;
}
