import { ChangeDetectorRef, OnInit } from '@angular/core';
import { PageComponent } from '@shared/components/page.component';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { WidgetContext } from '@home/models/widget-component.models';
import { UtilsService } from '@core/services/utils.service';
import { LoadNodesCallback } from '@shared/components/nav-tree.component';
import { EdgeService } from '@core/http/edge.service';
import { EntityService } from '@core/http/entity.service';
import { TranslateService } from '@ngx-translate/core';
import * as i0 from "@angular/core";
export declare class EdgesOverviewWidgetComponent extends PageComponent implements OnInit {
    protected store: Store<AppState>;
    private edgeService;
    private entityService;
    private translateService;
    private utils;
    private cd;
    ctx: WidgetContext;
    toastTargetId: string;
    customerTitle: string;
    edgeIsDatasource: boolean;
    private widgetConfig;
    private subscription;
    private datasources;
    private settings;
    private nodeIdCounter;
    constructor(store: Store<AppState>, edgeService: EdgeService, entityService: EntityService, translateService: TranslateService, utils: UtilsService, cd: ChangeDetectorRef);
    ngOnInit(): void;
    loadNodes: LoadNodesCallback;
    private loadNodesForEdge;
    private createEntityNode;
    private entitiesToNodes;
    private getCustomerTitle;
    private initializeConfig;
    private updateTitle;
    static ɵfac: i0.ɵɵFactoryDeclaration<EdgesOverviewWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<EdgesOverviewWidgetComponent, "tb-edges-overview-widget", never, { "ctx": "ctx"; }, {}, never, never>;
}
