import { ChangeDetectorRef } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityComponent } from '../../components/entity/entity.component';
import { FormBuilder, FormGroup } from '@angular/forms';
import { EntityType } from '@shared/models/entity-type.models';
import { TranslateService } from '@ngx-translate/core';
import { CalculatedFieldInfo, CalculatedFieldType } from '@shared/models/calculated-field.models';
import { EntityId } from '@shared/models/id/entity-id';
import { BaseData } from '@shared/models/base-data';
import { Observable } from 'rxjs';
import { CalculatedFieldsTableConfig, CalculatedFieldsTableEntity } from '@home/components/calculated-fields/calculated-fields-table-config';
import { EntityService } from '@core/http/entity.service';
import * as i0 from "@angular/core";
export declare class CalculatedFieldComponent extends EntityComponent<CalculatedFieldsTableEntity> {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    protected entityValue: CalculatedFieldInfo;
    protected entitiesTableConfigValue: CalculatedFieldsTableConfig;
    protected fb: FormBuilder;
    protected cd: ChangeDetectorRef;
    private entityService;
    standalone: boolean;
    entityName: string;
    disabledConfiguration: boolean;
    ownerId: EntityId;
    readonly tenantId: string;
    readonly EntityType: typeof EntityType;
    readonly calculatedFieldsEntityTypeList: EntityType[];
    readonly CalculatedFieldType: typeof CalculatedFieldType;
    readonly fieldTypes: (CalculatedFieldType.SIMPLE | CalculatedFieldType.SCRIPT | CalculatedFieldType.GEOFENCING | CalculatedFieldType.PROPAGATION | CalculatedFieldType.RELATED_ENTITIES_AGGREGATION | CalculatedFieldType.ENTITY_AGGREGATION)[];
    readonly CalculatedFieldTypeTranslations: Map<CalculatedFieldType, import("@shared/models/calculated-field.models").CalculatedFieldTypeTranslate>;
    private cfFormService;
    private destroyRef;
    constructor(store: Store<AppState>, translate: TranslateService, entityValue: CalculatedFieldInfo, entitiesTableConfigValue: CalculatedFieldsTableConfig, fb: FormBuilder, cd: ChangeDetectorRef, entityService: EntityService);
    hideDelete(): boolean;
    additionalDebugActionConfig: {
        action: () => any;
        title: any;
    };
    get entityId(): EntityId;
    get entitiesTableConfig(): CalculatedFieldsTableConfig;
    changeEntity(entity: BaseData<EntityId>): void;
    buildForm(_entity?: CalculatedFieldInfo): FormGroup;
    updateForm(entity: CalculatedFieldInfo): void;
    onTestScript(expression?: string): Observable<string>;
    updateFormState(): void;
    getOwnerId(entityId: EntityId): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<CalculatedFieldComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<CalculatedFieldComponent, "tb-calculated-field", never, { "standalone": { "alias": "standalone"; "required": false; }; "entityName": { "alias": "entityName"; "required": false; }; }, {}, never, never, false, never>;
}
