import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { TranslateService } from '@ngx-translate/core';
import { MatDialog } from '@angular/material/dialog';
import { PageLink } from '@shared/models/page/page-link';
import { Observable } from 'rxjs';
import { PageData } from '@shared/models/page/page-data';
import { EntityId } from '@shared/models/id/entity-id';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { DestroyRef, Renderer2 } from '@angular/core';
import { CalculatedFieldsService } from '@core/http/calculated-fields.service';
import { CalculatedField, CalculatedFieldEventArguments, CalculatedFieldInfo, CalculatedFieldsQuery } from '@shared/models/calculated-field.models';
import { ImportExportService } from '@shared/import-export/import-export.service';
import { EntityDebugSettingsService } from '@home/components/entity/debug/entity-debug-settings.service';
import { DatePipe } from '@angular/common';
import { TbPopoverService } from '@shared/components/popover.service';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import { UtilsService } from "@core/services/utils.service";
import { Router } from '@angular/router';
export type CalculatedFieldsTableEntity = CalculatedField | CalculatedFieldInfo;
export declare class CalculatedFieldsTableConfig extends EntityTableConfig<CalculatedFieldsTableEntity> {
    private calculatedFieldsService;
    private translate;
    private dialog;
    private datePipe;
    private entityId;
    private store;
    private destroyRef;
    private renderer;
    private entityName;
    private ownerId;
    private importExportService;
    private entityDebugSettingsService;
    private utilsService;
    private router;
    private readonly;
    private hideClearEventAction;
    private popoverService;
    private userPermissionsService;
    pageMode: boolean;
    readonly tenantId: string;
    additionalDebugActionConfig: {
        title: any;
        action: (calculatedField: CalculatedFieldsTableEntity, openCalculatedFieldEdit?: boolean, afterCloseCallback?: (expression: string) => void) => any;
    };
    calculatedFieldFilterConfig: CalculatedFieldsQuery;
    constructor(calculatedFieldsService: CalculatedFieldsService, translate: TranslateService, dialog: MatDialog, datePipe: DatePipe, entityId: EntityId, store: Store<AppState>, destroyRef: DestroyRef, renderer: Renderer2, entityName: string, ownerId: EntityId, importExportService: ImportExportService, entityDebugSettingsService: EntityDebugSettingsService, utilsService: UtilsService, router: Router, readonly: boolean, hideClearEventAction: boolean, popoverService: TbPopoverService, userPermissionsService: UserPermissionsService, pageMode?: boolean);
    fetchCalculatedFields(pageLink: PageLink): Observable<PageData<CalculatedFieldsTableEntity>>;
    private onOpenDebugConfig;
    private openDebugTab;
    private editCalculatedField;
    private getCalculatedFieldDialog;
    private allowWritePermission;
    private openDebugEventsDialog;
    private exportCalculatedField;
    private copyCalculatedField;
    private importCalculatedField;
    private updateImportedCalculatedField;
    private onDebugConfigChanged;
    getTestScriptDialog(calculatedField: CalculatedFieldsTableEntity, argumentsObj?: CalculatedFieldEventArguments, openCalculatedFieldEdit?: boolean, expression?: string): Observable<string>;
    private openCalculatedField;
    private onCFAction;
    private openReprocessing;
}
