import { AfterViewInit, ElementRef, OnChanges, OnDestroy, SimpleChanges } from '@angular/core';
import { ControlValueAccessor, FormBuilder, UntypedFormGroup, ValidationErrors, Validator } from '@angular/forms';
import { Observable, Subject } from 'rxjs';
import { ConverterLibraryService } from '@core/http/converter-library.service';
import { IntegrationType } from '@shared/models/integration.models';
import { Converter, ConverterLibraryValue, ConverterType, Model, Vendor } from '@shared/models/converter.models';
import { ConverterComponent } from '@home/components/converter/converter.component';
import * as i0 from "@angular/core";
export declare class ConverterLibraryComponent implements ControlValueAccessor, Validator, OnChanges, AfterViewInit, OnDestroy {
    private fb;
    private converterLibraryService;
    converterType: ConverterType;
    integrationType: IntegrationType;
    set interacted(interacted: boolean);
    modelInput: ElementRef;
    vendorInput: ElementRef;
    dataConverterComponent: ConverterComponent;
    libraryFormGroup: UntypedFormGroup;
    vendors$: Observable<Array<Vendor>>;
    models$: Observable<Model[]>;
    converter$: Observable<Converter>;
    filteredModels$: Observable<Array<Model>>;
    filteredVendors$: Observable<Array<Vendor>>;
    vendorInputSubject: Subject<void>;
    modelInputSubject: Subject<void>;
    private destroy$;
    private onChange;
    constructor(fb: FormBuilder, converterLibraryService: ConverterLibraryService);
    get vendorValueChanges(): Observable<Vendor | string>;
    get modelValueChanges(): Observable<Model | string>;
    ngOnChanges(changes: SimpleChanges): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    setDisabledState(isDisabled: boolean): void;
    registerOnChange(fn: (converter: Converter) => void): void;
    registerOnTouched(_: any): void;
    writeValue(converterLibraryValue: ConverterLibraryValue): void;
    validate(): ValidationErrors | null;
    displayModelFn(model?: Model): string;
    displayVendorFn(vendor?: Vendor): string;
    onLinkClick(event: MouseEvent, url: string): void;
    clearModel(): void;
    clearVendor(): void;
    private updateScriptLangEnable;
    static ɵfac: i0.ɵɵFactoryDeclaration<ConverterLibraryComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ConverterLibraryComponent, "tb-converter-library", never, { "converterType": { "alias": "converterType"; "required": false; }; "integrationType": { "alias": "integrationType"; "required": false; }; "interacted": { "alias": "interacted"; "required": false; }; }, {}, never, never, false, never>;
}
