import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, FormBuilder, UntypedFormGroup } from '@angular/forms';
import { ConverterType, Model } from '@shared/models/converter.models';
import { IntegrationType } from '@shared/models/integration.models';
import { Observable } from 'rxjs';
import { ConverterLibraryService } from '@core/http/converter-library.service';
import * as i0 from "@angular/core";
export declare class ConverterLibraryModelAutocompleteComponent implements OnInit, ControlValueAccessor {
    private fb;
    private converterLibraryService;
    input: ElementRef;
    modelFormGroup: UntypedFormGroup;
    private modelValue;
    private _integrationType;
    private _converterType;
    private _vendorName;
    filteredModels$: Observable<Array<Model>>;
    searchText: string;
    private refresh$;
    private dirty;
    private modelsCache$;
    private propagateChange;
    set integrationType(value: IntegrationType);
    get integrationType(): IntegrationType;
    set converterType(value: ConverterType);
    get converterType(): ConverterType;
    set vendorName(value: string);
    get vendorName(): string;
    constructor(fb: FormBuilder, converterLibraryService: ConverterLibraryService);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    displayModelFn(model?: Model): string;
    writeValue(model: Model | string): void;
    private updateView;
    onFocus(): void;
    clear(): void;
    onLinkClick(event: MouseEvent, url: string): void;
    private reset;
    private fetchModels;
    private filterModels;
    onBlur(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ConverterLibraryModelAutocompleteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ConverterLibraryModelAutocompleteComponent, "tb-converter-library-model-autocomplete", never, { "integrationType": { "alias": "integrationType"; "required": false; }; "converterType": { "alias": "converterType"; "required": false; }; "vendorName": { "alias": "vendorName"; "required": false; }; }, {}, never, never, false, never>;
}
