import { ChangeDetectorRef, DestroyRef, OnInit } from '@angular/core';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { EntityComponent } from '../entity/entity.component';
import { FormBuilder, FormControl, FormGroup } from '@angular/forms';
import { TranslateService } from '@ngx-translate/core';
import { Converter, ConverterDebugInput, ConverterSourceType, ConverterType } from '@shared/models/converter.models';
import { ResourcesService } from '@core/services/resources.service';
import { ConverterService } from '@core/http/converter.service';
import { EntityTableConfig } from '@home/models/entity/entities-table-config.models';
import { MatDialog } from '@angular/material/dialog';
import { ScriptLanguage } from '@shared/models/rule-node.models';
import { IntegrationConvertersInfo } from '@shared/models/integration.models';
import { Observable } from 'rxjs';
import { ConverterLibraryService } from '@core/http/converter-library.service';
import { EntityType } from '@shared/models/entity-type.models';
import { IntegrationService } from '@core/http/integration.service';
import { StringItemsOption } from '@shared/components/string-items-list.component';
import { AdditionalDebugActionConfig } from '@home/components/entity/debug/entity-debug-settings.model';
import { UserPermissionsService } from '@core/http/user-permissions.service';
import * as i0 from "@angular/core";
export declare class ConverterComponent extends EntityComponent<Converter> implements OnInit {
    protected store: Store<AppState>;
    protected translate: TranslateService;
    private converterService;
    private integrationService;
    private dialog;
    private resourcesService;
    private converterLibraryService;
    protected entityValue: Converter;
    protected entitiesTableConfigValue: EntityTableConfig<Converter>;
    protected fb: FormBuilder;
    protected cd: ChangeDetectorRef;
    private destroyRef;
    private userPermissionsService;
    private predefinedConverterName;
    integrationWizardMode: boolean;
    interacted: boolean;
    allowedConvertorSourceType: ConverterSourceType[];
    private _converterTypeValue;
    set converterTypeValue(value: ConverterSourceType);
    get converterTypeValue(): ConverterSourceType;
    set converterName(value: string);
    integrationName: string;
    converterType: typeof ConverterType;
    converterTypes: ConverterType[];
    converterTypeTranslations: Map<ConverterType, string>;
    converterTypeTitleTranslations: Map<ConverterType, string>;
    tbelEnabled: boolean;
    scriptLanguage: typeof ScriptLanguage;
    EntityType: typeof EntityType;
    predefinedKeys: Array<string>;
    entityTypeKeysTranslationMap: Map<EntityType, Record<string, string>>;
    prevNewConverterFormValue: Converter;
    prevLibraryConverterFormValue: Converter;
    ConverterSourceType: typeof ConverterSourceType;
    integrationInfo$: Observable<IntegrationConvertersInfo>;
    private predefinedConverterKeys;
    private integrationsConvertersInfo;
    private defaultUpdateOnlyKeysByIntegrationType;
    private defaultConverterV2Configuration;
    constructor(store: Store<AppState>, translate: TranslateService, converterService: ConverterService, integrationService: IntegrationService, dialog: MatDialog, resourcesService: ResourcesService, converterLibraryService: ConverterLibraryService, entityValue: Converter, entitiesTableConfigValue: EntityTableConfig<Converter>, fb: FormBuilder, cd: ChangeDetectorRef, destroyRef: DestroyRef, userPermissionsService: UserPermissionsService);
    onConverterTypeChange(type: ConverterSourceType): void;
    private updateIntegrationsInfo;
    ngOnInit(): void;
    private resetToNewTab;
    hideDelete(): boolean;
    onConverterSelected(converter: Converter): void;
    private updatedConverterScriptLangDisableState;
    private updatedConverterLibraryDisableState;
    buildForm(entity: Converter): FormGroup;
    prepareFormValue(value: Converter): Converter;
    updatedValidators(): void;
    get additionalActionConfig(): AdditionalDebugActionConfig;
    private openDebugEventsDialog;
    private checkIsNewConverter;
    private updatedOnlyKeysValue;
    private updateDefaultConfiguration;
    private onConverterTypeChanged;
    private updateConverterVersion;
    private updatedConverterVersionDisableState;
    private updateConfigurationEntityName;
    private updatedPredefinedConverterKeys;
    private onSetDefaultScriptBody;
    private setupDefaultScriptBody;
    updateForm(entity: Converter, emitEvent?: boolean): void;
    get isConverterLibraryAndNotNull(): boolean;
    onConverterIdCopied(): void;
    openConverterTestDialog(): void;
    get mainConfigurationTitle(): string;
    get functionFormControl(): FormControl;
    get functionName(): string;
    get functionArgs(): string[];
    get functionHelpId(): string;
    get functionHelpPopupStyle(): Record<string, string>;
    get testFunctionButtonLabel(): string;
    get fetchLatestKey(): (searchText?: string) => Observable<Array<StringItemsOption>>;
    private fetchConverterKeys;
    private getLibraryDebugIn;
    private getDefaultDebugIn;
    showConverterTestDialog(debugIn: ConverterDebugInput, setFirstTab?: boolean): void;
    private openTestDialog;
    static ɵfac: i0.ɵɵFactoryDeclaration<ConverterComponent, [null, null, null, null, null, null, null, { optional: true; }, { optional: true; }, null, null, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ConverterComponent, "tb-converter", never, { "integrationWizardMode": { "alias": "integrationWizardMode"; "required": false; }; "interacted": { "alias": "interacted"; "required": false; }; "converterTypeValue": { "alias": "converterTypeValue"; "required": false; }; "converterName": { "alias": "converterName"; "required": false; }; "integrationName": { "alias": "integrationName"; "required": false; }; }, {}, never, never, false, never>;
}
