import { AfterViewInit, DestroyRef, ElementRef, QueryList } from '@angular/core';
import { ErrorStateMatcher } from '@angular/material/core';
import { MatDialogRef } from '@angular/material/dialog';
import { Store } from '@ngrx/store';
import { AppState } from '@core/core.state';
import { UntypedFormBuilder, UntypedFormControl, UntypedFormGroup, FormGroupDirective, NgForm } from '@angular/forms';
import { Router } from '@angular/router';
import { DialogComponent } from '@shared/components/dialog.component';
import { ContentType } from '@shared/models/constants';
import { JsonContentComponent } from '@shared/components/json-content.component';
import { ConverterDebugInput } from '@shared/models/converter.models';
import { ConverterService } from '@core/http/converter.service';
import { WhiteLabelingService } from '@core/http/white-labeling.service';
import { ScriptLanguage } from '@shared/models/rule-node.models';
import * as i0 from "@angular/core";
export interface ConverterTestDialogData {
    isDecoder: boolean;
    funcBody: string;
    scriptLang?: ScriptLanguage;
    debugIn: ConverterDebugInput;
}
export declare class ConverterTestDialogComponent extends DialogComponent<ConverterTestDialogComponent, string> implements AfterViewInit, ErrorStateMatcher {
    protected store: Store<AppState>;
    protected router: Router;
    data: ConverterTestDialogData;
    private errorStateMatcher;
    dialogRef: MatDialogRef<ConverterTestDialogComponent, string>;
    fb: UntypedFormBuilder;
    wl: WhiteLabelingService;
    private converterService;
    private destroyRef;
    width: string;
    height: string;
    topPanelElmRef: QueryList<ElementRef<HTMLElement>>;
    topLeftPanelElmRef: QueryList<ElementRef<HTMLElement>>;
    topRightPanelElmRef: QueryList<ElementRef<HTMLElement>>;
    bottomPanelElmRef: QueryList<ElementRef<HTMLElement>>;
    bottomLeftPanelElmRef: QueryList<ElementRef<HTMLElement>>;
    bottomRightPanelElmRef: QueryList<ElementRef<HTMLElement>>;
    payloadContent: JsonContentComponent;
    converterTestFormGroup: UntypedFormGroup;
    isDecoder: boolean;
    submitted: boolean;
    contentType: typeof ContentType;
    contentTypes: string[];
    contentTypesInfoMap: Map<ContentType, import("@shared/models/constants").ContentTypeData>;
    scriptLanguage: typeof ScriptLanguage;
    scriptLang: ScriptLanguage;
    constructor(store: Store<AppState>, router: Router, data: ConverterTestDialogData, errorStateMatcher: ErrorStateMatcher, dialogRef: MatDialogRef<ConverterTestDialogComponent, string>, fb: UntypedFormBuilder, wl: WhiteLabelingService, converterService: ConverterService, destroyRef: DestroyRef);
    init(): void;
    private prepareStringContent;
    private convertContent;
    private updateInputContent;
    ngAfterViewInit(): void;
    private initSplitLayout;
    isErrorState(control: UntypedFormControl | null, form: FormGroupDirective | NgForm | null): boolean;
    cancel(): void;
    test(): void;
    private testConverter;
    private checkInputParamErrors;
    save(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ConverterTestDialogComponent, [null, null, null, { skipSelf: true; }, null, null, null, null, null]>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ConverterTestDialogComponent, "tb-converter-test-dialog", never, {}, {}, never, never, false, never>;
}
