import { ElementRef, OnInit } from '@angular/core';
import { ControlValueAccessor, FormBuilder, UntypedFormGroup } from '@angular/forms';
import { ConverterType, Vendor } from '@shared/models/converter.models';
import { Observable } from 'rxjs';
import { ConverterLibraryService } from '@core/http/converter-library.service';
import { IntegrationType } from '@shared/models/integration.models';
import * as i0 from "@angular/core";
export declare class ConverterLibraryVendorAutocompleteComponent implements OnInit, ControlValueAccessor {
    private fb;
    private converterLibraryService;
    input: ElementRef;
    vendorFormGroup: UntypedFormGroup;
    private modelValue;
    private _integrationType;
    private _converterType;
    filteredVendors$: Observable<Array<Vendor>>;
    searchText: string;
    private refresh$;
    private dirty;
    private vendorsCache$;
    private propagateChange;
    set integrationType(value: IntegrationType);
    get integrationType(): IntegrationType;
    set converterType(value: ConverterType);
    get converterType(): ConverterType;
    constructor(fb: FormBuilder, converterLibraryService: ConverterLibraryService);
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    ngOnInit(): void;
    displayVendorFn(vendor?: Vendor): string;
    writeValue(vendor: Vendor | string): void;
    private updateView;
    onFocus(): void;
    clear(): void;
    private reset;
    private fetchVendors;
    private filterVendors;
    onBlur(): void;
    static ɵfac: i0.ɵɵFactoryDeclaration<ConverterLibraryVendorAutocompleteComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<ConverterLibraryVendorAutocompleteComponent, "tb-converter-library-vendor-autocomplete", never, { "integrationType": { "alias": "integrationType"; "required": false; }; "converterType": { "alias": "converterType"; "required": false; }; }, {}, never, never, false, never>;
}
