import { AfterViewInit, ChangeDetectorRef, ElementRef, OnDestroy, OnInit, Renderer2, TemplateRef } from '@angular/core';
import { WidgetContext } from '@home/models/widget-component.models';
import { DatePipe } from '@angular/common';
import { ColorProcessor, ComponentStyle } from '@shared/models/widget-settings.models';
import { WidgetComponent } from '@home/components/widget/widget.component';
import { BatteryLevelLayout, BatteryLevelWidgetSettings } from '@home/components/widget/lib/indicator/battery-level-widget.models';
import { ResizeObserver } from '@juggle/resize-observer';
import * as i0 from "@angular/core";
export declare class BatteryLevelWidgetComponent implements OnInit, OnDestroy, AfterViewInit {
    private date;
    private widgetComponent;
    private renderer;
    private cd;
    batteryLevelContent: ElementRef<HTMLElement>;
    batteryLevelBox: ElementRef<HTMLElement>;
    batteryLevelRectangle: ElementRef<HTMLElement>;
    batteryLevelValueBox: ElementRef<HTMLElement>;
    batteryLevelValue: ElementRef<HTMLElement>;
    settings: BatteryLevelWidgetSettings;
    ctx: WidgetContext;
    widgetTitlePanel: TemplateRef<any>;
    layout: BatteryLevelLayout;
    layoutClass: string;
    vertical: boolean;
    solid: boolean;
    showValue: boolean;
    autoScaleValueSize: boolean;
    valueText: string;
    valueStyle: ComponentStyle;
    valueColor: ColorProcessor;
    value: number;
    batterySections: boolean[];
    dividedBorderRadius: string;
    dividedGap: string;
    batteryLevelColor: ColorProcessor;
    batteryShapeColor: ColorProcessor;
    backgroundStyle: ComponentStyle;
    overlayStyle: ComponentStyle;
    batteryBoxResize$: ResizeObserver;
    hasCardClickAction: boolean;
    private decimals;
    private units;
    constructor(date: DatePipe, widgetComponent: WidgetComponent, renderer: Renderer2, cd: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onInit(): void;
    onDataUpdated(): void;
    trackBySection(index: number): number;
    cardClick($event: Event): void;
    private onResize;
    private setValueFontSize;
    static ɵfac: i0.ɵɵFactoryDeclaration<BatteryLevelWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<BatteryLevelWidgetComponent, "tb-battery-level-widget", never, { "ctx": "ctx"; "widgetTitlePanel": "widgetTitlePanel"; }, {}, never, never, false, never>;
}
