import { AfterViewInit, ChangeDetectorRef, ElementRef, OnDestroy, OnInit, Renderer2, TemplateRef } from '@angular/core';
import { WidgetContext } from '@home/models/widget-component.models';
import { ColorProcessor, ComponentStyle, DateFormatProcessor } from '@shared/models/widget-settings.models';
import { WidgetComponent } from '@home/components/widget/widget.component';
import { SignalStrengthLayout, SignalStrengthWidgetSettings } from '@home/components/widget/lib/indicator/signal-strength-widget.models';
import { TranslateService } from '@ngx-translate/core';
import { Observable } from 'rxjs';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import * as i0 from "@angular/core";
export declare class SignalStrengthWidgetComponent implements OnInit, OnDestroy, AfterViewInit {
    widgetComponent: WidgetComponent;
    private imagePipe;
    private sanitizer;
    private translate;
    private renderer;
    private cd;
    signalStrengthShape: ElementRef<HTMLElement>;
    signalStrengthTooltip: ElementRef<HTMLElement>;
    settings: SignalStrengthWidgetSettings;
    ctx: WidgetContext;
    widgetTitlePanel: TemplateRef<any>;
    layout: SignalStrengthLayout;
    activeBarsColor: ColorProcessor;
    showDate: boolean;
    dateFormat: DateFormatProcessor;
    dateStyle: ComponentStyle;
    showTooltip: boolean;
    tooltipStyle: ComponentStyle;
    showTooltipValue: boolean;
    tooltipValueText: string;
    tooltipValueLabelStyle: ComponentStyle;
    tooltipValueStyle: ComponentStyle;
    showTooltipDate: boolean;
    tooltipDateFormat: DateFormatProcessor;
    tooltipDateLabelStyle: ComponentStyle;
    tooltipDateStyle: ComponentStyle;
    backgroundStyle$: Observable<ComponentStyle>;
    overlayStyle: ComponentStyle;
    padding: string;
    shapeResize$: ResizeObserver;
    hasCardClickAction: boolean;
    private decimals;
    private units;
    private drawSvgShapePending;
    private svgShape;
    private bars;
    private centerTextElement;
    private lastCenterText;
    private inactiveBarsColorHex;
    private inactiveBarsOpacity;
    private rssi;
    private noSignal;
    private noData;
    private noSignalRssiValue;
    constructor(widgetComponent: WidgetComponent, imagePipe: ImagePipe, sanitizer: DomSanitizer, translate: TranslateService, renderer: Renderer2, cd: ChangeDetectorRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onInit(): void;
    onDataUpdated(): void;
    cardClick($event: Event): void;
    private drawSvg;
    private renderValues;
    private renderCenterText;
    private onResize;
    static ɵfac: i0.ɵɵFactoryDeclaration<SignalStrengthWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<SignalStrengthWidgetComponent, "tb-signal-strength-widget", never, { "ctx": { "alias": "ctx"; "required": false; }; "widgetTitlePanel": { "alias": "widgetTitlePanel"; "required": false; }; }, {}, never, never, false, never>;
}
