import { AfterViewInit, ChangeDetectorRef, ElementRef, OnDestroy, OnInit, Renderer2 } from '@angular/core';
import { BasicActionWidgetComponent } from '@home/components/widget/lib/action/action-widget.models';
import { StatusWidgetLayout, StatusWidgetSettings } from '@home/components/widget/lib/indicator/status-widget.models';
import { Observable } from 'rxjs';
import { ComponentStyle } from '@shared/models/widget-settings.models';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import { UtilsService } from '@core/services/utils.service';
import * as i0 from "@angular/core";
export declare class StatusWidgetComponent extends BasicActionWidgetComponent implements OnInit, AfterViewInit, OnDestroy {
    protected imagePipe: ImagePipe;
    protected sanitizer: DomSanitizer;
    private renderer;
    private utils;
    protected cd: ChangeDetectorRef;
    private elementRef;
    statusWidgetPanel: ElementRef<HTMLElement>;
    statusWidgetContent: ElementRef<HTMLElement>;
    settings: StatusWidgetSettings;
    backgroundStyle$: Observable<ComponentStyle>;
    overlayStyle: ComponentStyle;
    overlayInset: string;
    borderRadius: string;
    layout: StatusWidgetLayout;
    showLabel: boolean;
    label$: Observable<string>;
    labelStyle: ComponentStyle;
    showStatus: boolean;
    status$: Observable<string>;
    statusStyle: ComponentStyle;
    icon: string;
    iconStyle: ComponentStyle;
    private panelResize$;
    private onLabel$;
    private onStatus$;
    private onBackground$;
    private onBackgroundDisabled$;
    private offLabel$;
    private offStatus$;
    private offBackground$;
    private offBackgroundDisabled$;
    private state;
    private disabled;
    private disabledState;
    constructor(imagePipe: ImagePipe, sanitizer: DomSanitizer, renderer: Renderer2, utils: UtilsService, cd: ChangeDetectorRef, elementRef: ElementRef);
    ngOnInit(): void;
    ngAfterViewInit(): void;
    ngOnDestroy(): void;
    onInit(): void;
    private onState;
    private onDisabled;
    private updateDisabledState;
    private onResize;
    private updateStyle;
    static ɵfac: i0.ɵɵFactoryDeclaration<StatusWidgetComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<StatusWidgetComponent, "tb-status-widget", never, {}, {}, never, never, false, never>;
}
