import { ChangeDetectorRef, OnInit, Renderer2, ViewContainerRef } from '@angular/core';
import { ControlValueAccessor } from '@angular/forms';
import { BackgroundSettings, BackgroundType, ComponentStyle } from '@shared/models/widget-settings.models';
import { MatButton } from '@angular/material/button';
import { TbPopoverService } from '@shared/components/popover.service';
import { Observable } from 'rxjs';
import { ImagePipe } from '@shared/pipe/image.pipe';
import { DomSanitizer } from '@angular/platform-browser';
import * as i0 from "@angular/core";
export declare class BackgroundSettingsComponent implements OnInit, ControlValueAccessor {
    private imagePipe;
    private sanitizer;
    private popoverService;
    private renderer;
    private viewContainerRef;
    private cd;
    disabled: boolean;
    backgroundType: typeof BackgroundType;
    modelValue: BackgroundSettings;
    backgroundStyle$: Observable<ComponentStyle>;
    overlayStyle: ComponentStyle;
    private propagateChange;
    constructor(imagePipe: ImagePipe, sanitizer: DomSanitizer, popoverService: TbPopoverService, renderer: Renderer2, viewContainerRef: ViewContainerRef, cd: ChangeDetectorRef);
    ngOnInit(): void;
    registerOnChange(fn: any): void;
    registerOnTouched(fn: any): void;
    setDisabledState(isDisabled: boolean): void;
    writeValue(value: BackgroundSettings): void;
    openBackgroundSettingsPopup($event: Event, matButton: MatButton): void;
    private updateBackgroundStyle;
    static ɵfac: i0.ɵɵFactoryDeclaration<BackgroundSettingsComponent, never>;
    static ɵcmp: i0.ɵɵComponentDeclaration<BackgroundSettingsComponent, "tb-background-settings", never, { "disabled": { "alias": "disabled"; "required": false; }; }, {}, never, never, false, never>;
}
